import type { Bridge } from "./types";

/**
 * Missing mesh — bridge concepts and the technical / thoughtful ligaments
 * that would stop organs looking independent.
 *
 * Source of truth on GitHub: subhesco-bit/SUBH-DEEP @ consolidated/final
 * (DORA, BIEA, REOS missing layers, AFRERA_MISSING_PLATFORMS_ANALYSIS,
 * MASTER_MISSING_CONCEPT_INDEX, eventBus.js stub).
 * This catalog is complete as a naming: every missing joint has signal, today, contract, thought.
 * Status living is this organism only.
 */
export const MESH_BRIDGES: Bridge[] = [
  {
    id: "b-livestock-cell",
    from: "livestock",
    to: "farmer",
    name: "Animals are cell assets",
    kind: "technical",
    status: "partial",
    signal: "livestock.owned { farmerId, head, milkYield }",
    today: "livestockService sits beside farmerService. Headcount does not nourish FDI or household cashflow.",
    contract: "Every animal is a fact on the cell. Yield, veterinary cost, and chill cost write into FDI.",
    thought: "A second genome that does not feed the nucleus is a side module.",
  },
  {
    id: "b-livestock-cover",
    from: "livestock",
    to: "insurance",
    name: "Herd cover on the same immune system",
    kind: "technical",
    status: "missing",
    signal: "herd.covered { animalId, policyId, hazard }",
    today: "Crop policies exist. Livestock and veterinary specs do not share a claim pulse with weather or outage.",
    contract: "Outage that warms milk and disease that thins a herd both open cover on the spine.",
    thought: "Immunity that only knows grain will let the other genome die quietly.",
  },
  {
    id: "b-livestock-cash",
    from: "livestock",
    to: "finance",
    name: "Dairy cashflow metabolises credit",
    kind: "technical",
    status: "missing",
    signal: "milk.settled { farmerId, litres, rupees }",
    today: "Credit scoring does not hear litre-days. Dairy society management is GAP-0047, documented only.",
    contract: "Regular milk settlement is as legitimate a credit pulse as a crop offtake.",
    thought: "Daily milk is the most honest cashflow a cell has. Finance that ignores it is guessing.",
  },
  {
    id: "b-livestock-dairy",
    from: "livestock",
    to: "processing",
    name: "Milk becomes food, not a row",
    kind: "technical",
    status: "missing",
    signal: "milk.intake { litres, temp, farmerId } → process.batch",
    today: "Processing and livestock never share a lot. Chilling is nobody’s schedule.",
    contract: "Intake at the chiller is the harvest event of the second genome.",
    thought: "Digestion that only knows grain has forgotten half the village.",
  },
  {
    id: "b-livestock-shelf",
    from: "livestock",
    to: "marketplace",
    name: "Milk and meat as living lots",
    kind: "technical",
    status: "missing",
    signal: "lot.ready { kind: dairy|meat, qty, chillCost }",
    today: "Marketplace is a GI crop storefront. Dairy lots are not born from chill events.",
    contract: "A chilled litre can be listed with energy cost and farmer cell already on it.",
    thought: "If the shelf cannot sell what the herd just gave, the organism is only a crop app.",
  },
  {
    id: "b-process-shelf",
    from: "processing",
    to: "marketplace",
    name: "Digested lot returns as food",
    kind: "technical",
    status: "missing",
    signal: "process.completed { lotId, sku, yield, energyKwh }",
    today: "Processed SKUs are catalogued by hand. They do not carry the parent lot, energy, or farmer split.",
    contract: "Output lots inherit GI, cell, energy, and FUS from the intake lot.",
    thought: "Value addition that forgets the cell is a factory with a rural URL.",
  },
  {
    id: "b-process-intake",
    from: "warehouse",
    to: "processing",
    name: "Reserve feeds digestion",
    kind: "technical",
    status: "partial",
    signal: "storage.release { lotId, to: mill|chiller, qty }",
    today: "Organism: processMass shrinks remaining in place with declared loss. No child milled lot yet.",
    contract: "The same lot object moves. Moisture and GI do not get retyped.",
    thought: "Fat that cannot become muscle is obesity. Grain that cannot become food is a silo.",
  },
  {
    id: "b-process-fus",
    from: "processing",
    to: "fvie",
    name: "Process changes food utility",
    kind: "technical",
    status: "missing",
    signal: "food.utility.recompute { sku, process, satiety, convenience }",
    today: "FVIE is missing, so milling, puffing, and fermenting never change a score.",
    contract: "Each process is a transformation of FUS, not only of SKU code.",
    thought: "A mill that does not know satiety is just a motor.",
  },
  {
    id: "b-process-chain",
    from: "processing",
    to: "trace",
    name: "Handler added to the marker",
    kind: "technical",
    status: "missing",
    signal: "trace.append { lotId, handler, process, temp }",
    today: "Trace is minted, if at all, as a product badge. Process does not append.",
    contract: "Every handler is a link. A GI claim after anonymous milling is a lie.",
    thought: "Immunity that stops at the farm gate is a sticker.",
  },
  {
    id: "b-shared-twin",
    from: "shared",
    to: "village",
    name: "Village muscle lives on the twin",
    kind: "technical",
    status: "missing",
    signal: "asset.located { assetId, villageId, hours, cost }",
    today: "Asset rental is a catalog. The village twin was specified and never attached.",
    contract: "Every shared dryer, tractor, and cold room is a node on the twin with a rupee save.",
    thought: "Muscle that does not belong to a body is equipment photography.",
  },
  {
    id: "b-shared-ledger",
    from: "shared",
    to: "rcop",
    name: "Shared vs individual is a liver question",
    kind: "technical",
    status: "missing",
    signal: "rcop.decide { asset, shared: bool, rupeesPerYear }",
    today: "RCOP is missing. Rental does not answer the only question the liver asks.",
    contract: "Booking is allowed only after the twin says this save beats owning it alone.",
    thought: "A catalog of tractors is not an economy. A decision is.",
  },
  {
    id: "b-shared-power",
    from: "shared",
    to: "recie",
    name: "Shared dryers draw village breath",
    kind: "technical",
    status: "missing",
    signal: "asset.load { assetId, kwh, window }",
    today: "Dryers and pumps are booked as if power were free.",
    contract: "Shared loads register on the energy cloud. Outage reschedules the booking.",
    thought: "Village muscle that ignores breath will seize.",
  },
  {
    id: "b-water-pump",
    from: "water",
    to: "recie",
    name: "Pumping is an energy fact",
    kind: "technical",
    status: "missing",
    signal: "water.pumped { litres, kwh, aquifer, plotId }",
    today: "No water organ. Irrigation load is named in RECIE and then left as a bullet.",
    contract: "Every pumped litre posts kWh to RECIE and stress to the aquifer twin.",
    thought: "Water and energy are one breath. Split them and both KPIs lie.",
  },
  {
    id: "b-water-crop",
    from: "water",
    to: "crop",
    name: "Irrigation writes the season",
    kind: "technical",
    status: "missing",
    signal: "irrigation.window { plotId, mm, cost }",
    today: "Crop calendars do not hear pump hours or canal rotations.",
    contract: "A planted-crop fact includes water cost and stress, or it is not a season plan.",
    thought: "A genome that cannot drink on time is a spreadsheet.",
  },
  {
    id: "b-water-ledger",
    from: "water",
    to: "rcop",
    name: "₹ per litre on the village ledger",
    kind: "technical",
    status: "missing",
    signal: "water.cost { villageId, ₹/litre, source }",
    today: "RCOP lists water as a cost category. There is no engine.",
    contract: "Shared storage vs private borewell is a liver decision, shown in rupees per year.",
    thought: "The cheapest water is the litre the village did not have to lift twice.",
  },
  {
    id: "b-water-twin",
    from: "water",
    to: "village",
    name: "Aquifer on the habitat twin",
    kind: "technical",
    status: "missing",
    signal: "aquifer.state { villageId, depth, quality, stress }",
    today: "Village is a place field. GAP-0078 water monitoring is documented only.",
    contract: "The twin carries aquifer, tanks, and rights — not only houses.",
    thought: "A habitat that cannot say what it drinks is a pin.",
  },
  {
    id: "b-water-stock",
    from: "water",
    to: "livestock",
    name: "Herd water is not leftover irrigation",
    kind: "technical",
    status: "missing",
    signal: "stock.water { litres, quality, cost }",
    today: "Livestock and irrigation never share a water budget.",
    contract: "Dairy and draught have a reserved quality and cost on the same fluid organ.",
    thought: "Animals that drink last are how a second genome is quietly sacrificed.",
  },
  {
    id: "b-fpo-member",
    from: "fpo",
    to: "farmer",
    name: "Membership is collective tissue",
    kind: "technical",
    status: "living",
    signal: "fpo.member { fpoId, farmerId, share, offtake }",
    today: "Organism: Magh FPO membership is tissue; offtake splits qty-weighted. GitHub FPO is an ACL role.",
    contract: "The cell remains a nucleus. The FPO is tissue it can act through.",
    thought: "A login named FPO is not a cooperative. A pooled harvest is.",
  },
  {
    id: "b-fpo-offtake",
    from: "fpo",
    to: "contract",
    name: "Collective offtake before sowing",
    kind: "technical",
    status: "living",
    signal: "fpo.contract.offer { fpoId, crop, qty, season }",
    today: "Organism: pool offtake is FIFO remaining grams, then qty-weighted farmgate. GitHub contracts still open on a form.",
    contract: "When veins pull, the FPO is offered volume the cell could not underwrite alone.",
    thought: "Small farms grow a spine by promising together. Alone they sell distress.",
  },
  {
    id: "b-fpo-group-credit",
    from: "fpo",
    to: "finance",
    name: "Group credit on pooled health",
    kind: "technical",
    status: "missing",
    signal: "fpo.credit { fpoId, line, fdiDrivers }",
    today: "PACS and SHG management are GAP-0045/0046 — documented only. Credit is individual.",
    contract: "Group line reprices from pooled FDI, offtake, and storage — explained in rupees.",
    thought: "Extracting EMI from one flooded cell while the FPO sits idle is not rural finance.",
  },
  {
    id: "b-fpo-seller",
    from: "fpo",
    to: "marketplace",
    name: "FPO as the public hand",
    kind: "technical",
    status: "partial",
    signal: "listing.seller { fpoId, farmerCells[] }",
    today: "Organism: pooled listings carry member cells via FIFO split. Kitchen and GI story still thin.",
    contract: "The shelf shows the collective and the cells it nourishes, or it is a wholesaler skin.",
    thought: "A brand that hides the cell is a mandi with better CSS.",
  },
  {
    id: "b-fpo-assets",
    from: "fpo",
    to: "shared",
    name: "Collective muscle is booked as one",
    kind: "technical",
    status: "missing",
    signal: "fpo.asset { fpoId, assetId, roster }",
    today: "Rental catalog is individual. FPO-owned dryers do not reshape member calendars.",
    contract: "FPO assets write into every member plot they serve, and into RCOP’s shared-vs-individual.",
    thought: "A dryer the members cannot feel in their season plan is a monument.",
  },
  {
    id: "b-house-cell",
    from: "household",
    to: "farmer",
    name: "Household is the living unit of the cell",
    kind: "technical",
    status: "living",
    signal: "household.of { farmerId, members, goals, cash }",
    today: "Organism: each cell carries a household name. Not yet a kitchen graph or buffer-days ledger.",
    contract: "The cell has a household: mouths, goals, festival plates, and a cash buffer.",
    thought: "A farmer without a household is an account. A household is a life.",
  },
  {
    id: "b-house-goal",
    from: "household",
    to: "fvie",
    name: "Family goal compiles to food utility",
    kind: "technical",
    status: "missing",
    signal: "household.goal { diabetic, child, budget } → fus.query",
    today: "No household, no FVIE. Goals cannot compile.",
    contract: "A household goal is the query. FUS is the answer. The cart is a consequence.",
    thought: "Nutrition apps that start from a catalog have already lost the family.",
  },
  {
    id: "b-house-cash",
    from: "household",
    to: "finance",
    name: "Household cashflow, not only farm EMI",
    kind: "technical",
    status: "partial",
    signal: "household.cash { in, out, bufferDays }",
    today: "Organism: cell statement is farmgate minus inputs. School fees and medical shocks are invisible.",
    contract: "Credit that cannot see household buffer will call a health shock a default.",
    thought: "Rural finance that only sees the plot is extracting from a life it refuses to model.",
  },
  {
    id: "b-house-kitchen",
    from: "household",
    to: "gcip",
    name: "Kitchen remembers why the crop exists",
    kind: "technical",
    status: "partial",
    signal: "household.kitchen { dishes, festival, variety }",
    today: "Organism: Magh kitchen is a village graph, not yet a household plate ledger.",
    contract: "Each household contributes dishes to the graph. The graph returns sowing advice.",
    thought: "The most accurate demand sensor in a village is a grandmother’s winter list.",
  },
  {
    id: "b-house-vein",
    from: "household",
    to: "demand",
    name: "Plates return as veins",
    kind: "technical",
    status: "missing",
    signal: "demand.observed { householdId, dish, qty, window }",
    today: "Demand is an AI POST. Households never speak.",
    contract: "Repeat plates, skipped weeks, and festival spikes are first-class veins.",
    thought: "Forecasting without plates is astrology with a neural net.",
  },
  {
    id: "b-scheme-cell",
    from: "scheme",
    to: "farmer",
    name: "Eligibility computed on the cell",
    kind: "technical",
    status: "missing",
    signal: "scheme.eligible { farmerId, scheme, roi, rupees }",
    today: "Government knowledge is a missing REOS layer. Farmers hunt PDFs.",
    contract: "The cell carries land, FDI, crop, and livestock facts. Eligibility is a function, not a form.",
    thought: "A benefit the nucleus cannot feel is a press release.",
  },
  {
    id: "b-scheme-village",
    from: "scheme",
    to: "village",
    name: "Village-scale schemes on the twin",
    kind: "technical",
    status: "missing",
    signal: "scheme.village { villageId, feederSolar, storage, rupeesPerYear }",
    today: "No twin, so feeder solarisation and community storage cannot be composed.",
    contract: "Community schemes land on the twin with a liver answer: rupees per year saved.",
    thought: "Individual rooftop in a village that needed a feeder is how subsidies miss.",
  },
  {
    id: "b-scheme-solar",
    from: "scheme",
    to: "recie",
    name: "PM-KUSUM composed into energy cost",
    kind: "technical",
    status: "missing",
    signal: "scheme.energy { scheme, kwh, tcoDelta }",
    today: "Energy platforms are missing, so subsidies cannot change lifetime ₹/kWh.",
    contract: "A scheme is an input to TCO, not a parallel brochure.",
    thought: "Solar with a subsidy still has to beat diesel in rupees. Otherwise it is a photo.",
  },
  {
    id: "b-scheme-pump",
    from: "scheme",
    to: "water",
    name: "Irrigation subsidy is a water fact",
    kind: "technical",
    status: "missing",
    signal: "scheme.water { scheme, ₹/litreDelta }",
    today: "No water organ, so irrigation schemes cannot reprice the litre.",
    contract: "Eligibility plus pumping cost plus aquifer stress = one composed product.",
    thought: "A free pump that lowers an aquifer is not a gift. It is an unpriced fever.",
  },
  {
    id: "b-scheme-compose",
    from: "scheme",
    to: "finance",
    name: "Subsidy composes with credit, not beside it",
    kind: "technical",
    status: "missing",
    signal: "product.composed { credit, scheme, netEmi }",
    today: "b-gov-scheme already named the gap from AI to finance. The scheme organ itself does not exist.",
    contract: "The farmer sees one product: net EMI after subsidy, with renewal and compliance on the cell.",
    thought: "Two portals — loan and scheme — is how inclusion becomes homework.",
  },
  {
    id: "b-spine-harvest",
    from: "spine",
    to: "crop",
    name: "Harvest is blood, not a page",
    kind: "technical",
    status: "living",
    signal: "spine.publish harvest.completed",
    today:
      "Organism: spine_events persist harvest.completed. GitHub eventBus.js is still an in-memory stub.",
    contract: "crop.harvested is a spine event. Warehouse, trace, insurance, market, lot all subscribe.",
    thought: "A bus that no organ boards is a comment in a file.",
  },
  {
    id: "b-spine-intake",
    from: "spine",
    to: "warehouse",
    name: "Intake subscribes, does not retype",
    kind: "technical",
    status: "living",
    signal: "spine.subscribe harvest.completed → warehouse.intake",
    today: "Organism: warehouse.intake is a handler on the same lot id. GitHub warehouse still retypes.",
    contract: "Intake is a handler on the spine. The lot object is the payload.",
    thought: "Capillaries that do not reach the reserve organ leave grain in the field.",
  },
  {
    id: "b-spine-settle",
    from: "spine",
    to: "orders",
    name: "Settlement is a pulse",
    kind: "technical",
    status: "living",
    signal: "spine.publish order.settled",
    today: "Organism: order.settled posts journal and payouts. demand.observed still does not fire.",
    contract: "One event, three subscribers: payout, FDI, demand.observed.",
    thought: "Muscle that does not return blood is a cramp.",
  },
  {
    id: "b-spine-brain",
    from: "spine",
    to: "ai",
    name: "Nervous system rides the same blood",
    kind: "technical",
    status: "living",
    signal: "spine.subscribe * → reflex.evaluate",
    today: "Organism: coordinator consults the library; fabric caps spend at 0 paise; companion proposes. GitHub AIs are not subscribers.",
    contract: "The coordinator is the only brain. It sees the spine or it is hidden.",
    thought: "A brain that does not taste blood is a library of prompts.",
  },
  {
    id: "b-lot-birth",
    from: "lot",
    to: "crop",
    name: "Harvest mints a living lot",
    kind: "technical",
    status: "living",
    signal: "lot.mint { lotId, variety, kg, moisture, farmerId, villageId }",
    today: "Organism: harvest mints erp_lots with remaining_grams = grams. GitHub has no lot object.",
    contract: "One lot id from birth. Every later organ appends. None re-create.",
    thought: "Identity of produce is the identity of livelihood. Split it and GI becomes a rumour.",
  },
  {
    id: "b-lot-reserve",
    from: "lot",
    to: "warehouse",
    name: "The same body is stored",
    kind: "technical",
    status: "living",
    signal: "lot.stored { lotId, bin, temp, cover }",
    today: "Organism: inward is a state of the same lot. GitHub intake invents a warehouse id.",
    contract: "Storage is a state of the lot, not a new citizen.",
    thought: "A body that is renamed at every door is how traceability dies.",
  },
  {
    id: "b-lot-marker",
    from: "lot",
    to: "trace",
    name: "Marker is a property of the lot",
    kind: "technical",
    status: "partial",
    signal: "lot.marker { lotId, gi, geo, handlers[] }",
    today: "Organism: GI is a field on the lot. It is not yet an immune mint that blocks GI claims.",
    contract: "No GI listing without a marker on this lot. Marker is born with the lot.",
    thought: "A certificate that can exist without the sack is a PDF, not an immune marker.",
  },
  {
    id: "b-lot-shelf",
    from: "lot",
    to: "marketplace",
    name: "The shelf sells the lot",
    kind: "technical",
    status: "living",
    signal: "lot.listed { lotId, fus, price, cell }",
    today: "Organism: the shelf sells remaining grams of the lot at a declared price per kg. No FUS on the listing yet.",
    contract: "Draft listing is a projection of a living lot. Price can show energy and GI split.",
    thought: "Selling a product that is not a lot is selling a photograph of grain.",
  },
  {
    id: "b-lot-artery",
    from: "lot",
    to: "logistics",
    name: "Freight moves the same body",
    kind: "technical",
    status: "partial",
    signal: "lot.moved { lotId, energy, spoilageRisk }",
    today: "Organism: freight is declared on the offtake. Spoilage does not write back onto the lot.",
    contract: "A shipment is a motion of a lot. Fever (spoilage) posts to the lot, then to insurance and RCOP.",
    thought: "Arteries that invent a new patient mid-journey cannot treat a fever.",
  },
  {
    id: "b-lot-cover",
    from: "lot",
    to: "insurance",
    name: "Cover clings to the lot",
    kind: "technical",
    status: "living",
    signal: "lot.covered { lotId, policyId }",
    today: "Organism: cover_status lives on the lot. Gap is a spine alert. Premium is never invented.",
    contract: "Transit and warehouse cover are states of the lot. A gap is a spine alert.",
    thought: "Insurance of a person that ignores the sack is a form. Insurance of the sack is immunity.",
  },
  {
    id: "b-cloud-lungs",
    from: "cloud",
    to: "recie",
    name: "Cloud is how lungs become a schedule",
    kind: "technical",
    status: "missing",
    signal: "energy.cloud { villageId, forecast, surplus, ₹/kWh }",
    today: "RECIE 1.6 Village Energy Cloud is specified as missing. No forecast, no allocation.",
    contract: "RECIE computes cost. The cloud allocates time. Neither ships without the other.",
    thought: "A cost engine without a schedule is an essay. A schedule without cost is a roster.",
  },
  {
    id: "b-cloud-digest",
    from: "cloud",
    to: "processing",
    name: "Mills run on surplus",
    kind: "technical",
    status: "missing",
    signal: "cloud.window { surplus } → process.schedule",
    today: "Processing roster is static.",
    contract: "Batches wait for cheap, reliable windows. Yield after energy is the KPI.",
    thought: "Digestion at peak tariff is how villages pay extra to become poorer.",
  },
  {
    id: "b-cloud-cold",
    from: "cloud",
    to: "warehouse",
    name: "Cold rooms breathe with the village",
    kind: "technical",
    status: "missing",
    signal: "cloud.cold { load, outageRisk, holdCost }",
    today: "Holding energy is invisible. Outage spoilage is local.",
    contract: "Hold vs release is a cloud+RCOP decision: spoilage risk versus ₹ of power.",
    thought: "A dark cold room during an outage is a fever the reserve organ cannot feel.",
  },
  {
    id: "b-cloud-chill",
    from: "cloud",
    to: "livestock",
    name: "Chillers are on the same breath",
    kind: "technical",
    status: "missing",
    signal: "cloud.chill { litres, kwh, outage }",
    today: "Milk chillers are not a load on any cloud.",
    contract: "₹ per litre chilled is scheduled, metered, and claimed into insurance on outage.",
    thought: "Warm milk at dawn is the village spending energy it never measured.",
  },
  {
    id: "b-cloud-twin",
    from: "cloud",
    to: "village",
    name: "The twin has a weather of power",
    kind: "technical",
    status: "missing",
    signal: "twin.energy { villageId, stack, reliability }",
    today: "No twin, no cloud. Shared-vs-individual energy is an unasked question.",
    contract: "The habitat shows the stack: grid, diesel, solar, BESS — and the rupee path.",
    thought: "A village that cannot say how it breathes cannot choose a lung.",
  },
  {
    id: "b-graph-memory",
    from: "foodgraph",
    to: "gcip",
    name: "Culinary platform is a graph, not a blog",
    kind: "technical",
    status: "missing",
    signal: "graph.recipe { dish, village, festival, variety }",
    today: "GCIP is completely missing. There is no graph to hang recipes on.",
    contract: "Every recipe is a node with edges to variety, festival, household, and health goal.",
    thought: "A recipe page is literature. A graph is memory the economy can use.",
  },
  {
    id: "b-graph-taste",
    from: "foodgraph",
    to: "fvie",
    name: "Taste and satiety are edges",
    kind: "technical",
    status: "missing",
    signal: "graph.fus { dish, nutrition, satiety, childAccept }",
    today: "FVIE is missing, so FUS cannot live on the graph.",
    contract: "Food Utility is a property of graph nodes, queried by household goals.",
    thought: "Scoring food without a kitchen is lab nutrition. Villages do not eat in labs.",
  },
  {
    id: "b-graph-genome",
    from: "foodgraph",
    to: "crop",
    name: "Dishes imply varieties",
    kind: "technical",
    status: "living",
    signal: "graph.implies { dish → variety, season, district }",
    today: "Organism: kitchen graph implies Chakhao pithas to Chakhao Poireiton. FVIE still missing.",
    contract: "A spike in a dish revises the implied variety before seed is bought.",
    thought: "The genome should hear the kitchen. Otherwise it plants for a catalog.",
  },
  {
    id: "b-graph-vein",
    from: "foodgraph",
    to: "demand",
    name: "Festival graph lifts forecast",
    kind: "technical",
    status: "partial",
    signal: "graph.spike { festival, dish, window } → demand.revised",
    today: "Organism: Magh is encoded as a festival on the kitchen edge. Lead-time contract still uses settled qty, not a spike model.",
    contract: "The graph emits spikes with lead time enough to contract.",
    thought: "Magh is not a residual in a model. It is a memory. Encode it.",
  },
  {
    id: "b-rupee-cell",
    from: "rupee",
    to: "farmer",
    name: "Every path ends at the cell",
    kind: "technical",
    status: "living",
    signal: "prosperity.post { organ, farmerId, ₹, hours }",
    today: "Organism: farmgate credits the cell in the same ink as the journal. Village TCO still missing.",
    contract: "An organ may not ship a feature that cannot post a rupee to a named cell.",
    thought: "Dashboards that cannot nourish are mirrors in an empty room.",
  },
  {
    id: "b-rupee-liver",
    from: "rupee",
    to: "rcop",
    name: "Village TCO is the same ink",
    kind: "technical",
    status: "missing",
    signal: "ledger.post { villageId, organ, ₹/year }",
    today: "RCOP is missing. farmCosting is a module, not a village ledger.",
    contract: "Cell posts and village posts are two views of one ink.",
    thought: "A prosperous cell in a bankrupt village is a delay, not a design.",
  },
  {
    id: "b-rupee-pancreas",
    from: "rupee",
    to: "finance",
    name: "Hours-to-pay is a prosperity metric",
    kind: "technical",
    status: "missing",
    signal: "prosperity.hoursToPay { orderId, farmerId }",
    today: "Settlement skeletons do not write hours-to-pay onto any ledger.",
    contract: "Cost of capital and hours-to-pay post beside farmgate price.",
    thought: "A good price paid late is a hidden tax. The ledger must show it.",
  },
  {
    id: "b-rupee-brain",
    from: "rupee",
    to: "ai",
    name: "A reflex must explain the rupee",
    kind: "technical",
    status: "missing",
    signal: "reflex.explain { cause, organ, ₹, cell }",
    today: "AI services return text. They do not have to name a rupee path.",
    contract: "If the coordinator cannot post to the ledger, the reflex does not fire.",
    thought: "An explanation without a rupee is literature. Hide it.",
  },
  {
    id: "b-reflex-feet",
    from: "reflex",
    to: "soil",
    name: "Feet trigger the arc",
    kind: "technical",
    status: "missing",
    signal: "weather.alert | outage.alert | pest.alert → reflex.arc",
    today: "Advisories are pages. Two IoT systems disagree on ownership.",
    contract: "Sense events are the only legal start of a reflex. No human retype.",
    thought: "Feet that write a dashboard have not yet become a nervous system.",
  },
  {
    id: "b-reflex-immune",
    from: "reflex",
    to: "insurance",
    name: "Arc opens cover",
    kind: "technical",
    status: "missing",
    signal: "reflex.arc → claim.window",
    today: "Claims wait for a form. Weather does not open them.",
    contract: "Documented reflex: hazard → window → evidence from the lot and the twin.",
    thought: "Immunity that waits to be asked is a helpdesk.",
  },
  {
    id: "b-reflex-credit",
    from: "reflex",
    to: "finance",
    name: "Arc offers a pause",
    kind: "technical",
    status: "missing",
    signal: "reflex.arc → finance.moratorium.offer",
    today: "Credit does not hear the sky. Duplicate of the intent in b-weather-finance, now with an arc organ.",
    contract: "The offer is automatic, explained, and posted to the rupee ledger.",
    thought: "Mercy that requires a petition is not a reflex. It is PR.",
  },
  {
    id: "b-reflex-artery",
    from: "reflex",
    to: "logistics",
    name: "Arc retasks freight",
    kind: "technical",
    status: "missing",
    signal: "reflex.arc → logistics.reroute",
    today: "Freight tables do not move when a road or a chiller fails.",
    contract: "Hazard windows reshuffle pooling and cold chain, with spoilage risk priced in.",
    thought: "Arteries that cannot flinch will spill the blood they carry.",
  },
  {
    id: "b-reflex-brain",
    from: "reflex",
    to: "ai",
    name: "The brain owns the arc, not a chat",
    kind: "technical",
    status: "missing",
    signal: "reflex.declare { cause, organs[], rupee }",
    today: "Coordinator exists as a file. Reflexes are not declared, auditable, or rupee-attributed.",
    contract: "A reflex is a typed object. Domain AIs are tissues it may call. Chat is optional skin.",
    thought: "If it cannot fire without a prompt, it is not a spinal cord.",
  },
  {
    id: "b-wh-logistics",
    from: "warehouse",
    to: "logistics",
    name: "Release is an artery event",
    kind: "technical",
    status: "missing",
    signal: "storage.release → freight.dispatch",
    today: "Warehouse and logistics do not share a lot id. Dispatch is a separate form.",
    contract: "Release of a covered, marked lot is the only legal start of a GI shipment.",
    thought: "Fat that cannot enter the artery is a warehouse with a gift shop.",
  },
  {
    id: "b-wh-energy",
    from: "warehouse",
    to: "recie",
    name: "Holding power is a cost, not overhead",
    kind: "technical",
    status: "missing",
    signal: "storage.kwh { lotId, hours, ₹ }",
    today: "Energy of holding is invisible. Spoilage from outage is local.",
    contract: "₹ of spoilage avoided minus ₹ of holding energy, on the lot, on the cell.",
    thought: "Free storage is a lie villages pay for in warm grain.",
  },
  {
    id: "b-market-move",
    from: "marketplace",
    to: "logistics",
    name: "A sold lot must move",
    kind: "technical",
    status: "partial",
    signal: "order.confirmed → freight.plan",
    today: "Some order-to-ship wiring exists. It does not carry energy, spoilage, or lot identity.",
    contract: "The hand that sells already books the artery, priced with breath and fever.",
    thought: "A checkout without a journey is a promise the body cannot keep.",
  },
  {
    id: "b-contract-sow",
    from: "contract",
    to: "crop",
    name: "Offtake writes the genome",
    kind: "technical",
    status: "missing",
    signal: "contract.signed → crop.plan { variety, qty, season }",
    today: "Contracts do not write back into crop plans. The farmer sows on hope.",
    contract: "A signed offtake is a planted-crop fact waiting to happen.",
    thought: "A ligament that does not move the genome is a PDF in a drawer.",
  },
  {
    id: "b-contract-escrow",
    from: "contract",
    to: "finance",
    name: "Escrow is the money of trust",
    kind: "technical",
    status: "partial",
    signal: "contract.escrow { amount, milestone, farmerId }",
    today: "Contracts have statuses. Escrow, if any, is not a pulse the cell can see week by week.",
    contract: "Milestones release escrow onto the rupee ledger, visible to the cell.",
    thought: "Trust in time is money held in common — or it is stationery.",
  },
  {
    id: "b-recipe-genome",
    from: "gcip",
    to: "crop",
    name: "A dish names a variety",
    kind: "technical",
    status: "missing",
    signal: "recipe.variety { dish, crop, district }",
    today: "No culinary graph, so Chakhao is a catalog name, not a kitchen fact.",
    contract: "Every traditional dish points at varieties the genome can plan.",
    thought: "Heritage that cannot name a seed is a museum. Heritage that names a seed is a livelihood.",
  },
  {
    id: "b-village-vein",
    from: "village",
    to: "demand",
    name: "The habitat returns what it ate",
    kind: "technical",
    status: "missing",
    signal: "village.consumed { villageId, sku, season }",
    today: "Demand is national-looking and village-blind.",
    contract: "Each habitat is a demand node. Festival, tourism, and institutional pull sit on the twin.",
    thought: "A village that cannot say what it eats will always be surprised by what it should grow.",
  },
  {
    id: "b-erp-order",
    from: "erp",
    to: "orders",
    name: "ERP rides settlement, does not clone it",
    kind: "technical",
    status: "living",
    signal: "order.settled → erp.post",
    today: "Organism: orders, remaining hold, settlement journal are one books. GitHub ERP catalog is still a copy.",
    contract: "ERP is a subscriber. The spine remains the source of lots and settlements.",
    thought: "A bony spine that invents its own blood will split the body.",
  },
  {
    id: "b-erp-catalog",
    from: "erp",
    to: "marketplace",
    name: "Master data is not a living lot",
    kind: "technical",
    status: "partial",
    signal: "erp.product ↔ lot.projection",
    today: "Product sync exists. Live lots and master data diverge the same week.",
    contract: "SKU master is a skeleton. The lot is flesh. Sync is one way: flesh to bone, never bone inventing flesh.",
    thought: "Catalogues that outrun harvests are how GI becomes a fiction.",
  },
  {
    id: "b-trace-cover",
    from: "trace",
    to: "insurance",
    name: "A marker is evidence",
    kind: "technical",
    status: "missing",
    signal: "trace.evidence { lotId } → claim.file",
    today: "Claims and trace never share a payload.",
    contract: "A GI marker plus temperature chain is claim evidence, attached without a scan-and-upload.",
    thought: "Immunity that cannot read its own markers will demand paper from a flooded cell.",
  },
  {
    id: "b-channel-alloc",
    from: "demand",
    to: "processing",
    name: "Veins decide fresh vs processed",
    kind: "technical",
    status: "missing",
    signal: "channel.allocate { lotId, fresh|process|store|export }",
    today: "REOS AI Revenue Engine is missing. Lots do not choose a channel.",
    contract: "Demand plus energy plus FUS plus contract decide the channel. The farmer sees the rupee split.",
    thought: "Selling everything fresh is a habit. Allocation is an organism.",
  },
  {
    id: "b-fpo-village",
    from: "fpo",
    to: "village",
    name: "Collective tissue sits on the habitat",
    kind: "technical",
    status: "missing",
    signal: "fpo.habitat { fpoId, villageId, members }",
    today: "FPOs are not nodes on a twin. Villages are place strings.",
    contract: "An FPO without a habitat cannot share muscle, aquifer, or feeder.",
    thought: "A cooperative that is not of a place is a company. A place without a cooperative is only a pin.",
  },
  {
    id: "b-thought-livestock",
    from: "livestock",
    to: "farmer",
    name: "Livestock is a second genome",
    kind: "thoughtful",
    status: "missing",
    signal: "identity.genome.2",
    today: "Animals are a module beside crop. Veterinary is a spec. The cell is still a crop farmer in the UX.",
    contract: "The nucleus has two genomes. UX, FDI, and the rupee ledger treat both as life, not as tabs.",
    thought: "A rural cell that is only a crop row has already been simplified into poverty.",
  },
  {
    id: "b-thought-fpo",
    from: "fpo",
    to: "farmer",
    name: "FPO is tissue, not a role",
    kind: "thoughtful",
    status: "missing",
    signal: "identity.collective",
    today: "RBAC: admin, fpo, farmer, consumer. GAP-0043 says complete the FPO system — as software, not as a body.",
    contract: "The farmer remains the nucleus. The FPO is how many nuclei share a bone.",
    thought: "Roles are doors. Tissue is how a small life does not stand in the mandi alone.",
  },
  {
    id: "b-thought-household",
    from: "household",
    to: "farmer",
    name: "The household is the demand unit",
    kind: "thoughtful",
    status: "missing",
    signal: "identity.household",
    today: "Consumer is a checkout role. Household economy is a missing REOS layer.",
    contract: "Offtake, nutrition, and cash buffer are household facts that the cell lives inside.",
    thought: "A marketplace that sells to ‘users’ will never feed a family it cannot name.",
  },
  {
    id: "b-thought-water-breath",
    from: "water",
    to: "recie",
    name: "Water and energy are one breath",
    kind: "thoughtful",
    status: "missing",
    signal: "philosophy.nexus",
    today: "RECIE names irrigation load. RCOP names water cost. Neither organ exists, and they are listed separately.",
    contract: "No energy KPI without water; no water KPI without kWh. The breath is the nexus.",
    thought: "A solar pump that ignores the aquifer is a lung that does not ask if the blood is left.",
  },
  {
    id: "b-thought-scheme-blood",
    from: "scheme",
    to: "farmer",
    name: "A scheme is blood, not a PDF",
    kind: "thoughtful",
    status: "missing",
    signal: "philosophy.inclusion",
    today: "Schemes are content. Discovery is the farmer’s unpaid labour.",
    contract: "Inclusion means the cell is offered a composed product. Search is a failure mode.",
    thought: "A portal full of schemes the nucleus must hunt is a library next to a hungry body.",
  },
  {
    id: "b-thought-lot",
    from: "lot",
    to: "farmer",
    name: "The lot is one body of produce",
    kind: "thoughtful",
    status: "missing",
    signal: "philosophy.lot",
    today: "Six modules, six identifiers, one sack. The farmer retypes the harvest.",
    contract: "If two organs cannot point at the same lot id, they are not in the same organism.",
    thought: "Identity split is how GI, cover, and payout all become someone else’s problem.",
  },
  {
    id: "b-thought-spine-blood",
    from: "spine",
    to: "erp",
    name: "Blood is not bone",
    kind: "thoughtful",
    status: "missing",
    signal: "philosophy.bus",
    today: "eventBus.js is a stub. erpService is a batch hose. Both claim to be the spine.",
    contract: "ERP is bone. The event bus is blood. Bone may carry; it may not invent pulses.",
    thought: "Two skeletons cannot share one body. A skeleton cannot bleed.",
  },
  {
    id: "b-thought-shared-muscle",
    from: "shared",
    to: "village",
    name: "Shared infrastructure is village muscle",
    kind: "thoughtful",
    status: "missing",
    signal: "philosophy.muscle",
    today: "Rental is e-commerce for equipment. The habitat does not flex.",
    contract: "Muscle is booked, felt in the calendar, and justified in rupees per year on the twin.",
    thought: "A brochure of tractors is not a body. Hours a household could not afford alone are.",
  },
  {
    id: "b-thought-digest",
    from: "processing",
    to: "crop",
    name: "Processing is digestion of the same harvest",
    kind: "thoughtful",
    status: "missing",
    signal: "philosophy.digest",
    today: "Processing is a factory SKU path. Crop is a farmer page. They do not recognise each other.",
    contract: "Digestion has a parent lot. Margin after energy returns to the cell that grew it.",
    thought: "A mill that does not know the field is a stomach without a mouth.",
  },
  {
    id: "b-thought-season",
    from: "crop",
    to: "gcip",
    name: "Season is culture in the ground",
    kind: "thoughtful",
    status: "missing",
    signal: "philosophy.season",
    today: "Calendars are agronomic. Festivals are missing. The two clocks never meet.",
    contract: "A season plan names the festival it is for, or it is only weather.",
    thought: "Northeast GI produce is grown for a kitchen calendar. Strip the calendar and you strip the reason.",
  },
  {
    id: "b-thought-cloud",
    from: "cloud",
    to: "village",
    name: "Power is a weather of the habitat",
    kind: "thoughtful",
    status: "missing",
    signal: "philosophy.cloud",
    today: "If power appears, it is MW. The village does not have a weather of electricity.",
    contract: "The habitat feels surplus, outage, and tariff the way it feels monsoon.",
    thought: "Installing capacity into a place that cannot feel power is how projects look complete.",
  },
  {
    id: "b-thought-graph",
    from: "foodgraph",
    to: "fvie",
    name: "Food memory is not a nutrition label",
    kind: "thoughtful",
    status: "missing",
    signal: "philosophy.graph",
    today: "Nutrition, if any, is a column. Culture is a tag. Satiety does not exist as a word in the schema.",
    contract: "The graph holds why a food fills, who will eat it, and when it must be grown.",
    thought: "A label can be true and still be useless at a table where a child refuses the dish.",
  },
  {
    id: "b-thought-reflex",
    from: "reflex",
    to: "ai",
    name: "A chatbot is not a reflex",
    kind: "thoughtful",
    status: "missing",
    signal: "philosophy.reflex",
    today: "AI is a directory. DORA already named spinal reflex. Code named sixteen services.",
    contract: "Sense, decide, act, learn — on one event — or it is hidden from the organism.",
    thought: "Intelligence that waits to be prompted during a flood is a spectator.",
  },
  {
    id: "b-thought-coop-trust",
    from: "fpo",
    to: "contract",
    name: "Collective offtake is trust at village scale",
    kind: "thoughtful",
    status: "missing",
    signal: "philosophy.coop",
    today: "Contracts are one-to-one. The FPO is a badge.",
    contract: "The ligament can bind many cells at once without erasing any nucleus.",
    thought: "The mandi already knows how to crush one farmer. The organism’s answer is a we.",
  },
  {
    id: "b-thought-aquifer",
    from: "water",
    to: "village",
    name: "An aquifer is a commons, not a borewell",
    kind: "thoughtful",
    status: "missing",
    signal: "philosophy.commons",
    today: "Water, when mentioned, is a pump on a plot.",
    contract: "Rights, depth, and quality live on the habitat. The cell may draw; it may not pretend the well is private geology.",
    thought: "A prosperous farm over a dead aquifer is a countdown.",
  },
  {
    id: "b-thought-channel",
    from: "demand",
    to: "marketplace",
    name: "A storefront is not a revenue OS",
    kind: "thoughtful",
    status: "missing",
    signal: "philosophy.revenue",
    today: "Marketplace maturity is scored high. REOS says the revenue operating system is still a shop.",
    contract: "Fresh, process, store, export, institutional, subscription — allocated, not merely listed.",
    thought: "A beautiful shop that cannot choose a channel will always sell at the worst time.",
  },
  {
    id: "b-thought-time",
    from: "contract",
    to: "demand",
    name: "Time is the hidden dimension of every ligament",
    kind: "thoughtful",
    status: "missing",
    signal: "philosophy.time",
    today: "Modules are present-tense: list, order, store. Seasons, festivals, lead times, and next sowing are not first-class.",
    contract: "Every living ligament has a clock: lead time to sowing, hours-to-pay, cover window, festival spike.",
    thought: "An organism that cannot remember last Magh will plant next Magh as a surprise. That is how independent concepts stay independent.",
  },
  {
    id: "b-module-ai",
    from: "module",
    to: "ai",
    name: "AI systems are modules of one nerve",
    kind: "technical",
    status: "partial",
    signal: "module.attach { moduleId, organs[] }",
    today: "moduleSystemFactory.js prints SYS-M* from 544 folders. moduleContract.js classifies function-name prefixes. Neither names a DORA organ.",
    contract: "Each AI system registers: operations, organs it may move, pulses it emits, human-approval for commands.",
    thought: "A list of folders is an inventory. A synapse is a contract that fires.",
  },
  {
    id: "b-module-spine",
    from: "module",
    to: "spine",
    name: "Modules subscribe to blood",
    kind: "technical",
    status: "living",
    signal: "module.on harvest.completed",
    today: "Organism: Module OS workflows subscribe to harvest, intake, offtake. Unknown events fail. GitHub factory does not.",
    contract: "Factory.plug writes the event list. Unknown events fail closed. log-and-forget is forbidden.",
    thought: "A module that cannot hear blood is a prosthetic in a box.",
  },
  {
    id: "b-module-farmer",
    from: "module",
    to: "farmer",
    name: "Agentic sits with the cell",
    kind: "thoughtful",
    status: "living",
    signal: "agentic.propose { farmerId, harvest }",
    today: "Organism: agentic companion proposes; clerk approves with declared kg, loss, paymentRef. GitHub M675100 is still a 1KB re-export.",
    contract: "The companion proposes. The cell approves. Commands never execute alone.",
    thought: "Autonomy without a nucleus is a chatbot wearing the farmer’s name.",
  },
  {
    id: "b-module-lot",
    from: "module",
    to: "lot",
    name: "A proposal that cannot mint a lot is talk",
    kind: "technical",
    status: "living",
    signal: "agentic.propose lot.mint",
    today: "Organism: companion proposes lot.mint; clerk declares mass; remaining = grams. GitHub copilot is a page.",
    contract: "On harvest, agentic proposes one lot body. Human confirms. lot.mint fires. Media, trace, and cover attach to that id.",
    thought: "If the companion cannot point at the sack, it is not in the same organism as the harvest.",
  },
  {
    id: "b-module-reflex",
    from: "module",
    to: "reflex",
    name: "Sixteen mouths are not one arc",
    kind: "thoughtful",
    status: "missing",
    signal: "module.reflex weather.alert",
    today: "Advisory, self-heal, ops-intel, conversational, and voice are sibling modules. weatherAdvisory is still a page.",
    contract: "One reflex arc. Many tissues. Advisory explains; companion proposes; nerve fires muscle.",
    thought: "A mouth for every department is how a body forgets it has a spine.",
  },
  {
    id: "b-thought-wired",
    from: "module",
    to: "ai",
    name: "WIRED is not complete",
    kind: "thoughtful",
    status: "missing",
    signal: "philosophy.wired",
    today: "module.json status WIRED, wiredVerification: loads and delegates. analysis.isComplete false. Completeness: routes false, tests false.",
    contract: "A module is complete when it plugs, emits, and can name a rupee. Loading a re-export is not wiring.",
    thought: "The most expensive lie in this repo is the word WIRED on a skeleton.",
  },
  {
    id: "b-module-rupee",
    from: "module",
    to: "rupee",
    name: "Every module shows a rupee path",
    kind: "technical",
    status: "partial",
    signal: "module.rupeePath { organ, paise }",
    today: "Organism: AI cannot write rupees; fabric spend cap is 0 paise. No module yet posts a farmer rupee it moved.",
    contract: "fabric.allow spends paise against a cell, not a cloud bill. A proposal without ₹ is hidden.",
    thought: "Intelligence that cannot count the cell’s money is decoration with a GPU.",
  },
];
