import type { Bridge } from "./types";

/**
 * Ligaments that should bind organs. Living = some runtime path exists.
 * Partial = files exist on both sides but no event, schema, or UX joins them.
 * Missing = specified or implied, never built.
 *
 * Drawn from subhesco-bit/SUBH-DEEP @ consolidated/final.
 */
export const CORE_BRIDGES: Bridge[] = [
  {
    id: "b-farmer-market-fk",
    from: "farmer",
    to: "marketplace",
    name: "Product belongs to a cell",
    kind: "technical",
    status: "living",
    signal: "product.farmer_id",
    today: "productService rows point at a farmer. This is a foreign key, not a pulse — but it is a real ligament.",
    contract: "Keep the FK. Promote it to harvest.completed so the listing is born, not merely owned.",
    thought: "Ownership is the thinnest possible bond. Necessary, not sufficient.",
  },
  {
    id: "b-order-contains",
    from: "marketplace",
    to: "orders",
    name: "Cart to order",
    kind: "technical",
    status: "living",
    signal: "order.items[]",
    today: "Cart, checkout, and orderService are wired. Commerce muscle does contract — then stops.",
    contract: "Preserve checkout. Attach settlement as the next fibre of the same muscle.",
    thought: "The hand can grip. It cannot yet feed the cell.",
  },
  {
    id: "b-farmer-portal",
    from: "farmer",
    to: "crop",
    name: "Portal sees the field",
    kind: "technical",
    status: "living",
    signal: "farmer.dashboard.crops",
    today: "Farmer portal and agriculture services are among the most complete organs. They still speak in pages, not events.",
    contract: "The portal remains the skin. The harvest must leave the skin as blood.",
    thought: "A complete page is not a complete organ.",
  },
  {
    id: "b-harvest-fanout",
    from: "crop",
    to: "warehouse",
    name: "HarvestCompleted fan-out",
    kind: "technical",
    status: "missing",
    signal: "harvest.completed { lotId, giTag, moisture, villageId, farmerId }",
    today:
      "Harvest is a row in the farmer portal. Warehouse, insurance, trace, and marketplace never hear it. Four organs wait to be told by a human.",
    contract:
      "Spine publishes harvest.completed. Warehouse intake, insurance cover, GI trace mint, and marketplace draft-lot all subscribe. One lot object, four organs.",
    thought:
      "A sack of Chakhao is not four records in four modules. It is one body moving through the organism.",
  },
  {
    id: "b-harvest-market",
    from: "crop",
    to: "marketplace",
    name: "Lot is born as a listing",
    kind: "technical",
    status: "missing",
    signal: "lot.ready { lotId, foodUtility, gi, availableQty }",
    today: "Catalog products are created in the product service, independent of any harvest.",
    contract:
      "After warehouse grades a lot, marketplace receives a draft listing already carrying GI, moisture, and farmer cell.",
    thought: "The market should sell what the land just grew, not what a CMS last typed.",
  },
  {
    id: "b-harvest-trace",
    from: "crop",
    to: "trace",
    name: "GI marker at birth",
    kind: "technical",
    status: "missing",
    signal: "trace.mint { lotId, geo, handler, season }",
    today: "blockchainTrace and certifications exist as their own pages. Nothing is minted when the lot exists.",
    contract: "Trace mints at harvest. Listing without a marker cannot be sold as GI.",
    thought: "Trust is an immune marker, not a badge you add at checkout.",
  },
  {
    id: "b-harvest-insure",
    from: "warehouse",
    to: "insurance",
    name: "Warehouse cover on intake",
    kind: "technical",
    status: "missing",
    signal: "storage.covered { lotId, policyId, hazard }",
    today: "Policies live in insuranceService. Intake does not attach or confirm cover.",
    contract: "Intake either binds an existing master policy or opens a cover gap alert on the spine.",
    thought: "Grain in a dark room without cover is an uninsured organ.",
  },
  {
    id: "b-fdi-credit",
    from: "farmer",
    to: "finance",
    name: "FDI metabolises credit",
    kind: "technical",
    status: "partial",
    signal: "fdi.updated { farmerId, score, drivers }",
    today:
      "FDI is calculated in farmerService. Credit scoring is a separate AI endpoint. They do not share a pulse.",
    contract: "fdi.updated reprices credit line and insurance premium within the same day, with an explanation.",
    thought: "FDI is a development journey, not a cloned credit bureau score sitting next to a loan form.",
  },
  {
    id: "b-fdi-premium",
    from: "farmer",
    to: "insurance",
    name: "FDI reprices cover",
    kind: "technical",
    status: "missing",
    signal: "fdi.updated → premium.recompute",
    today: "Insurance does not read FDI. A farmer who just certified and stored well pays the same as one who did not.",
    contract: "Immune system listens to the cell’s health. Better practice, cheaper cover, shown in rupees.",
    thought: "Immunity that ignores the cell’s condition is not immunity.",
  },
  {
    id: "b-order-payout",
    from: "orders",
    to: "finance",
    name: "Settlement is one motion",
    kind: "technical",
    status: "partial",
    signal: "order.settled { orderId, farmerId, amount, hoursToPay }",
    today:
      "Orders, wallets, and payments were later bolted on as skeletons. Farmer payout, FDI bump, and demand signal are not one transaction.",
    contract:
      "order.settled credits the farmer cell, writes hours-to-pay, updates FDI, and emits demand.observed.",
    thought: "An order that does not nourish the cell is just a receipt.",
  },
  {
    id: "b-order-demand",
    from: "orders",
    to: "demand",
    name: "Veins return offtake",
    kind: "technical",
    status: "missing",
    signal: "demand.observed { sku, qty, village, season }",
    today: "Demand forecast is a POST to an AI route with a payload a human typed.",
    contract: "Every settled order is a vein. Forecast is a function of veins, not a prompt.",
    thought: "Without returning blood, the heart pumps into silence.",
  },
  {
    id: "b-iot-twin",
    from: "soil",
    to: "village",
    name: "Sensor ownership on the twin",
    kind: "technical",
    status: "missing",
    signal: "sensor.reading { entityId, farmerId, kind, value }",
    today:
      "Deferred in schema-decisions.json: IoT farmer_id vs entity_id, and two incompatible IoT systems both live.",
    contract:
      "One ownership model. Readings land on the village twin and the plot, never in a private silo.",
    thought: "Feet that do not tell the body where they stand are decoration.",
  },
  {
    id: "b-plantings-schema",
    from: "crop",
    to: "farmer",
    name: "Planted crop is a cell fact",
    kind: "technical",
    status: "missing",
    signal: "crop.planted { farmerId, plotId, variety, season }",
    today:
      "Deferred: crop_plantings schema, farms table vs farm_plots. Advanced analytics and digital twin disagree.",
    contract: "One planted-crop fact per farmer-plot-season, referenced by twin, insurance, and contract.",
    thought: "If the organism cannot say what is in the ground, it cannot promise what will be sold.",
  },
  {
    id: "b-weather-cascade",
    from: "soil",
    to: "insurance",
    name: "Weather as reflex",
    kind: "technical",
    status: "missing",
    signal: "weather.alert { villageId, hazard, window }",
    today: "weatherAdvisory is a page. It does not freeze EMI, open a claim window, or retask logistics.",
    contract:
      "weather.alert is an artery event. Insurance, finance, logistics, and crop subscribe with documented reflexes.",
    thought: "A warning that does not move a muscle is gossip.",
  },
  {
    id: "b-weather-finance",
    from: "soil",
    to: "finance",
    name: "Moratorium reflex",
    kind: "technical",
    status: "missing",
    signal: "weather.alert → finance.moratorium.offer",
    today: "Credit does not hear the sky.",
    contract: "Hazard windows offer a pause before a default, attributed to the village twin.",
    thought: "Extracting EMI through a flood is not rural finance. It is a disconnected organ.",
  },
  {
    id: "b-recipe-demand",
    from: "gcip",
    to: "demand",
    name: "Festival recipe lifts forecast",
    kind: "technical",
    status: "missing",
    signal: "culinary.spike { dish, region, window, impliedCrop }",
    today: "Culinary platform is entirely missing, so demand cannot know why millet moves in November.",
    contract: "Recipe calendar emits spikes. Demand revises. Contract farming is offered before sowing.",
    thought: "Culture is the most honest forecast. The organism forgot it had a memory.",
  },
  {
    id: "b-demand-contract",
    from: "demand",
    to: "contract",
    name: "Forecast becomes offtake",
    kind: "technical",
    status: "missing",
    signal: "demand.revised { crop, village, qty } → contract.offer",
    today: "Contracts are opened by a form, not by a vein.",
    contract: "When forecast confidence clears a threshold, the ligament offers a next-season contract to the cell.",
    thought: "A farmer should not have to guess the city. The organism already felt the pull.",
  },
  {
    id: "b-fus-rank",
    from: "fvie",
    to: "marketplace",
    name: "Food Utility ranks the shelf",
    kind: "technical",
    status: "missing",
    signal: "food.utility { sku, nutrition, satiety, taste, rupees, culture }",
    today: "Marketplace sorts like any store. FVIE does not exist.",
    contract: "Listings carry FUS. Goal-based baskets (diabetic, child, harvest-week) query the graph, not keywords.",
    thought: "People do not shop for SKUs. They shop for a full stomach that their family will eat.",
  },
  {
    id: "b-energy-logistics",
    from: "recie",
    to: "logistics",
    name: "₹ per cold kilometre",
    kind: "technical",
    status: "missing",
    signal: "energy.cost { kwh, outageHours, spoilageRisk } → freight.price",
    today: "Freight tables ignore diesel, inverter, and outage. RECIE is missing.",
    contract: "Every shipment quotes energy and spoilage risk as first-class cost, not overhead.",
    thought: "Cold chain that cannot say ₹ per kg moved is not logistics. It is hope.",
  },
  {
    id: "b-energy-process",
    from: "recie",
    to: "processing",
    name: "Village energy cloud schedules digestion",
    kind: "technical",
    status: "missing",
    signal: "energy.forecast { villageId, window, surplus }",
    today: "Processing roster is static. No village energy cloud.",
    contract: "Mills and chillers run when the cloud says power is cheapest and most reliable.",
    thought: "Digestion that ignores breath will choke.",
  },
  {
    id: "b-spoilage-cascade",
    from: "logistics",
    to: "rcop",
    name: "Spoilage hits the village ledger",
    kind: "technical",
    status: "missing",
    signal: "spoilage.event { lotId, kg, cause, kwh }",
    today: "Loss is local to a shipment. Insurance, RECIE, and RCOP never book it.",
    contract: "spoilage.event posts to claim, energy loss, and village TCO in one write.",
    thought: "Waste is the organism’s fever. A fever hidden in one module is how villages stay poor.",
  },
  {
    id: "b-shared-calendar",
    from: "shared",
    to: "crop",
    name: "Asset booking reshapes the season",
    kind: "technical",
    status: "missing",
    signal: "asset.booked { assetId, plotId, window }",
    today: "Rental is a catalog. The farm calendar does not move.",
    contract: "A booked dryer or tractor writes into the plot calendar and the yield model.",
    thought: "Shared muscle that does not move the body is a brochure.",
  },
  {
    id: "b-erp-pulse",
    from: "erp",
    to: "farmer",
    name: "Spine carries live lots, not copies",
    kind: "technical",
    status: "partial",
    signal: "erp.sync { entity, id, vector }",
    today: "erpService can POST a farmer. It does not ride the same events as the organism.",
    contract: "ERP is a subscriber and publisher on the spine, never a second master.",
    thought: "Two skeletons cannot share one body.",
  },
  {
    id: "b-ai-reflex",
    from: "ai",
    to: "farmer",
    name: "Nervous system fires muscles",
    kind: "technical",
    status: "partial",
    signal: "reflex.fire { cause, organs[], explanation }",
    today:
      "Sixteen AI services and a coordinator. No reflex engine subscribed to harvest, weather, spoilage, or settlement as one nervous system.",
    contract:
      "The coordinator is the only brain. Domain AIs are tissues. Reflexes are declared, auditable, and rupee-attributed.",
    thought: "A chatbot bolted onto a module is not a nervous system. It is a mouth without a spine.",
  },
  {
    id: "b-gov-scheme",
    from: "ai",
    to: "finance",
    name: "Scheme knowledge as subsidy blood",
    kind: "technical",
    status: "missing",
    signal: "scheme.eligible { farmerId, scheme, rupees }",
    today: "Government knowledge platform is a missing economic layer. Finance products do not auto-compose with schemes.",
    contract: "Eligibility is computed on the cell and offered as a composed product, not a PDF hunt.",
    thought: "A scheme the farmer must discover alone is not inclusion.",
  },
  {
    id: "b-thought-cell",
    from: "farmer",
    to: "village",
    name: "Farmer is a cell, not a role",
    kind: "thoughtful",
    status: "missing",
    signal: "identity.model",
    today: "RBAC lists farmer next to admin, fpo, consumer. The portal is a set of pages behind a role.",
    contract: "UX and data treat the farmer as the nucleus. Other organs report what they did for this cell, in rupees.",
    thought:
      "Roles are doors. Cells are lives. The consolidated branch still thinks in doors.",
  },
  {
    id: "b-thought-village",
    from: "village",
    to: "rcop",
    name: "Village is an economy",
    kind: "thoughtful",
    status: "missing",
    signal: "village.ledger",
    today: "Village is a place field. Cost is per module. No village ledger, no twin, no shared-vs-individual decision.",
    contract: "Every intervention answers: how many rupees per year does this save the village economy?",
    thought: "A pin on a map cannot be prosperous. An economy can.",
  },
  {
    id: "b-thought-food",
    from: "fvie",
    to: "gcip",
    name: "Food is culture, not a SKU",
    kind: "thoughtful",
    status: "missing",
    signal: "food.meaning",
    today: "Products have name, price, GI tag. No satiety, no grandmother, no festival, no household goal.",
    contract: "Every lot can answer who eats it, when, why it fills, and whether a child will accept it.",
    thought: "Northeast GI produce dies in a catalog the moment it is stripped of kitchen and calendar.",
  },
  {
    id: "b-thought-energy",
    from: "recie",
    to: "rcop",
    name: "Energy is lifetime ₹, not MW",
    kind: "thoughtful",
    status: "missing",
    signal: "energy.philosophy",
    today: "If energy appears at all, it is capacity. The missing-platforms analysis already named the inversion. Code did not.",
    contract: "KPIs are ₹/kg crop, ₹/litre chilled, ₹/hour irrigation — never MW installed.",
    thought: "Installing solar into a silo is how projects look complete and villages stay expensive.",
  },
  {
    id: "b-thought-gi",
    from: "trace",
    to: "marketplace",
    name: "GI is heritage plus livelihood",
    kind: "thoughtful",
    status: "partial",
    signal: "gi.meaning",
    today: "GI is a certification flag on a product. The cultural and livelihood claim is not carried into price or story.",
    contract: "A GI lot shows the cell, the geography, the kitchen, and the rupee split — or it is not GI.",
    thought: "A tag without a livelihood is branding. A livelihood without a tag is theft.",
  },
  {
    id: "b-thought-prosperity",
    from: "farmer",
    to: "ai",
    name: "Prosperity path on every organ",
    kind: "thoughtful",
    status: "missing",
    signal: "rule.prosperity",
    today:
      "The master spec says: every module must have a direct, measurable path to farmer prosperity. The concept audit counts files, not rupee paths.",
    contract: "No organ ships without a prosperity metric, a signal, and a named cell it nourishes.",
    thought:
      "One hundred and fifty-six independent concepts can all be ‘implemented’ and the organism still be dead.",
  },
  {
    id: "b-thought-contract",
    from: "contract",
    to: "farmer",
    name: "Contract is trust in time",
    kind: "thoughtful",
    status: "partial",
    signal: "trust.time",
    today: "Contracts have statuses. They do not feel like a season-long ligament of escrow and care.",
    contract: "The farmer can see, at any week, what is promised, what is in escrow, and what the offtake still owes.",
    thought: "Paper in a portal is not a bond. Time with money held in common is.",
  },
  {
    id: "b-thought-ai",
    from: "ai",
    to: "demand",
    name: "AI is a nervous system",
    kind: "thoughtful",
    status: "missing",
    signal: "ai.posture",
    today: "AI is a directory of services. The digital-organism spec already named brain, reflex, blood, and veins.",
    contract: "If it cannot sense, decide, act, and learn on the same event, it is not the nervous system. Hide it.",
    thought: "Intelligence that does not close a loop is literature.",
  },
  {
    id: "b-household-basket",
    from: "fvie",
    to: "orders",
    name: "Household goal becomes a basket",
    kind: "technical",
    status: "missing",
    signal: "goal.basket { householdId, goal, budget }",
    today: "Cart is SKU-in, SKU-out. No diabetic, child, or harvest-week goal.",
    contract: "A goal compiles to a basket that the market can fill from living lots.",
    thought: "Commerce should start from a life, not from a grid of cards.",
  },
  {
    id: "b-livestock-energy",
    from: "livestock",
    to: "recie",
    name: "₹ per litre chilled",
    kind: "technical",
    status: "missing",
    signal: "chill.cost { litres, kwh, outage }",
    today: "Livestock records headcount. Chilling energy is unmeasured.",
    contract: "Milk chilling posts to RECIE. Outage spoilage posts to insurance and RCOP.",
    thought: "A litre that warmed overnight is a silent withdrawal from the cell.",
  },
];
