import type { WalkHop } from "./types";

/** A Chakhao (black rice) harvest moving through the organism — and stalling. */
export const WALK_TITLE = "Chakhao lot, Karbi Anglong";
export const WALK_LEDE =
  "One harvest of GI black rice tries to travel the body: cell to market to kitchen to next season. Watch where the signal dies — including the missing bridge concepts that should have carried it.";

export const WALK: WalkHop[] = [
  {
    id: "w1",
    title: "The cell records a harvest",
    organId: "farmer",
    bridgeId: "b-thought-cell",
    signal: "farmer.harvest.noted { farmerId, variety: chakhao, kg: 840 }",
    today: "The farmer portal stores a row. No event leaves the page.",
    should: "The nucleus publishes a fact the whole body can feel.",
  },
  {
    id: "w2",
    title: "The living lot is never minted",
    organId: "lot",
    bridgeId: "b-lot-birth",
    signal: "lot.mint { lotId, variety: chakhao, kg: 840 }",
    today: "There is no lot object. Six modules will invent six ids for the same sack.",
    should: "One body of produce, one id, from field to plate.",
  },
  {
    id: "w3",
    title: "The event spine is a stub",
    organId: "spine",
    bridgeId: "b-spine-harvest",
    signal: "spine.publish harvest.completed",
    today: "eventBus.js is in-memory with TODO on the queue. Nothing publishes. Nothing subscribes for real.",
    should: "Blood carries the harvest. Warehouse, trace, cover, and market all drink.",
  },
  {
    id: "w4",
    title: "Genome should close the season",
    organId: "crop",
    bridgeId: "b-plantings-schema",
    signal: "crop.harvested { plotId, variety, season }",
    today: "crop_plantings, farms, and farm_plots still disagree. The season cannot close cleanly.",
    should: "One planted-crop fact, now harvested, referenced by twin, insurance, and contract.",
  },
  {
    id: "w5",
    title: "Warehouse never hears the lot",
    organId: "warehouse",
    bridgeId: "b-harvest-fanout",
    signal: "harvest.completed → warehouse.intake",
    today: "Intake waits for a clerk. Moisture, GI, and farmer cell are retyped.",
    should: "The same lot object arrives. Reserve organ takes it without a second birth.",
  },
  {
    id: "w6",
    title: "Cover is not attached",
    organId: "insurance",
    bridgeId: "b-harvest-insure",
    signal: "storage.covered",
    today: "A policy exists somewhere. The lot does not know. The immune system sleeps.",
    should: "Intake binds cover or raises a gap on the spine the same minute.",
  },
  {
    id: "w7",
    title: "GI marker is not minted",
    organId: "trace",
    bridgeId: "b-harvest-trace",
    signal: "trace.mint",
    today: "Traceability is a separate module. The lot can still be listed without a marker.",
    should: "Birth of the lot is birth of the marker. No GI claim without it.",
  },
  {
    id: "w8",
    title: "Market lists from a CMS, not the land",
    organId: "marketplace",
    bridgeId: "b-harvest-market",
    signal: "lot.ready",
    today: "Someone may create a product. It will not carry satiety, kitchen, or energy cost.",
    should: "A living lot appears on the shelf with GI, FUS, and farmer cell already on it.",
  },
  {
    id: "w9",
    title: "Food graph cannot remember why it exists",
    organId: "foodgraph",
    bridgeId: "b-graph-genome",
    signal: "graph.implies { chakhao pithas → chakhao, Magh }",
    today: "GCIP and FVIE are unattached organs. There is no graph from kitchen to variety.",
    should: "The memory organ already knew Magh would pull black rice. Demand is not a guess.",
  },
  {
    id: "w10",
    title: "An order pays a gateway, not a cell",
    organId: "orders",
    bridgeId: "b-order-payout",
    signal: "order.settled",
    today: "Wallet and payment-gateway skeletons were added in linkage repair. They do not nourish FDI or fire a vein.",
    should: "One motion: credit the cell, count hours-to-pay, emit demand.observed.",
  },
  {
    id: "w11",
    title: "Prosperity ledger never books the rupee",
    organId: "rupee",
    bridgeId: "b-rupee-cell",
    signal: "prosperity.post { organ: orders, ₹, hoursToPay }",
    today: "No attribution. AI cannot say which organ moved. The master spec’s rule is literature.",
    should: "Hours-to-pay and farmgate land on the cell in the same ink as village TCO.",
  },
  {
    id: "w12",
    title: "No offtake is offered for next sowing",
    organId: "contract",
    bridgeId: "b-demand-contract",
    signal: "contract.offer",
    today: "The farmer will sow again on hope. The ligament never fired. Time was never a dimension.",
    should: "A next-season contract appears on the cell — and on the FPO — before the seed is bought.",
  },
  {
    id: "w13",
    title: "Energy, water, and village cost never booked the journey",
    organId: "rcop",
    bridgeId: "b-spoilage-cascade",
    signal: "village.ledger.post",
    today: "If 40 kg spoiled in a power cut, insurance, RECIE, water, and RCOP each did not hear. The village ledger does not exist.",
    should: "The liver books the fever. The body learns what the journey cost.",
  },
  {
    id: "w14",
    title: "Agentic companion never wakes",
    organId: "module",
    bridgeId: "b-module-farmer",
    signal: "agentic.propose harvest.completed",
    today: "M675100 is WIRED, skeleton, a 1.1KB re-export with zero live callers. Sixteen AI systems sit beside the harvest and do not hear it.",
    should: "The companion proposes a lot mint and a rupee path. The cell approves. The harvest does not die at the portal.",
  },
];
