import type { WalkHop } from "./types";

/** A Chakhao (black rice) harvest moving through the organism — and stalling. */
export const WALK_TITLE = "Chakhao lot, Karbi Anglong";
export const WALK_LEDE =
  "One harvest of GI black rice tries to travel the body: cell to market to kitchen to next season. Watch where the signal dies — including the missing bridge concepts that should have carried it.";

export const WALK: WalkHop[] = [
  {
    id: "w1",
    title: "The cell records a harvest",
    organId: "farmer",
    bridgeId: "b-thought-cell",
    signal: "farmer.harvest.noted { farmerId, variety: chakhao, kg: 840 }",
    today: "This organism: the cell records Magh harvest on the books. GitHub portal still stores a row that never leaves the page.",
    should: "The nucleus publishes a fact the whole body can feel.",
  },
  {
    id: "w2",
    title: "The living lot is never minted",
    organId: "lot",
    bridgeId: "b-lot-birth",
    signal: "lot.mint { lotId, variety: chakhao, kg: 840 }",
    today: "This organism: harvest mints one lot; remaining = grams. GitHub still has no lot object.",
    should: "One body of produce, one id, from field to plate.",
  },
  {
    id: "w3",
    title: "The event spine is a stub",
    organId: "spine",
    bridgeId: "b-spine-harvest",
    signal: "spine.publish harvest.completed",
    today: "This organism: spine_events persist harvest.completed. GitHub eventBus.js is still an in-memory stub.",
    should: "Blood carries the harvest. Warehouse, trace, cover, and market all drink.",
  },
  {
    id: "w4",
    title: "Genome closes the season",
    organId: "crop",
    bridgeId: "b-plantings-schema",
    signal: "crop.harvested { plotId, variety, season }",
    today: "This organism: harvest closes the Magh planting on the named plot. Kramsapi still holds seed in the ground. GitHub crop_plantings still collide.",
    should: "One planted-crop fact, now harvested, referenced by twin, insurance, and contract.",
  },
  {
    id: "w5",
    title: "Warehouse never hears the lot",
    organId: "warehouse",
    bridgeId: "b-harvest-fanout",
    signal: "harvest.completed → warehouse.intake",
    today: "This organism: the same lot body can be inwarded. A clerk still presses intake. GitHub warehouse retypes moisture.",
    should: "The same lot object arrives. Reserve organ takes it without a second birth.",
  },
  {
    id: "w6",
    title: "Cover binds on intake",
    organId: "insurance",
    bridgeId: "b-harvest-insure",
    signal: "storage.covered",
    today: "This organism: Langthasa godown binds POL-LANGTHASA-GODOWN on intake. Premium is undeclared. Weather cover is still missing.",
    should: "Intake binds cover or raises a gap on the spine the same minute.",
  },
  {
    id: "w7",
    title: "GI marker is minted at birth",
    organId: "trace",
    bridgeId: "b-harvest-trace",
    signal: "trace.mint",
    today: "This organism: GI mint at birth (handler, Langthasa, Magh). A GI listing without the chain is blocked.",
    should: "Birth of the lot is birth of the marker. No GI claim without it.",
  },
  {
    id: "w8",
    title: "Market lists from the land, not the kitchen score",
    organId: "marketplace",
    bridgeId: "b-fus-rank",
    signal: "food.utility",
    today: "This organism: remaining mass lists at a declared rupee per kg. FUS scores still do not exist. Satiety and energy cost still missing from the shelf.",
    should: "A living lot appears on the shelf with GI, FUS, and farmer cell already on it.",
  },
  {
    id: "w9",
    title: "Kitchen remembers Magh",
    organId: "foodgraph",
    bridgeId: "b-graph-genome",
    signal: "graph.implies { chakhao pithas → chakhao, Magh }",
    today: "This organism: Chakhao pithas imply Chakhao Poireiton; Magh is memory. FVIE scores still do not exist.",
    should: "The memory organ already knew Magh would pull black rice. Demand is not a guess.",
  },
  {
    id: "w10",
    title: "An order pays a gateway, not a cell",
    organId: "orders",
    bridgeId: "b-order-payout",
    signal: "order.settled",
    today: "This organism: paymentRef settles farmgate onto the cell and emits demand.observed. FDI still does not reprice.",
    should: "One motion: credit the cell, count hours-to-pay, emit demand.observed.",
  },
  {
    id: "w11",
    title: "Prosperity ledger never books the rupee",
    organId: "rupee",
    bridgeId: "b-rupee-cell",
    signal: "prosperity.post { organ: orders, ₹, hoursToPay }",
    today: "This organism: farmgate and hours-to-pay land on the cell journal. Village TCO books declared energy, water, freight, and spoilage grams. 25-year optimizer still missing.",
    should: "Hours-to-pay and farmgate land on the cell in the same ink as village TCO.",
  },
  {
    id: "w12",
    title: "Next season is offered, price blank",
    organId: "contract",
    bridgeId: "b-demand-contract",
    signal: "contract.offer",
    today: "This organism: settlement offers Magh 2027 at the same kilograms. Price stays blank until a clerk declares it.",
    should: "A next-season contract appears on the cell — and on the FPO — before the seed is bought.",
  },
  {
    id: "w13",
    title: "Energy, water, and village cost book the journey",
    organId: "rcop",
    bridgeId: "b-spoilage-cascade",
    signal: "village.ledger.post",
    today: "This organism: 40 kg ginger spoiled in a power cut. Remaining grams fell. The village ledger posted. Insurance and energy heard. kWh and premium stay blank until a clerk declares them.",
    should: "The liver books the fever. The body learns what the journey cost.",
  },
  {
    id: "w14",
    title: "Agentic companion never wakes",
    organId: "module",
    bridgeId: "b-module-farmer",
    signal: "agentic.propose harvest.completed",
    today: "This organism: companion proposes harvest, intake, settle. GitHub M675100 is still a 1KB re-export. The clerk still must declare kg.",
    should: "The companion proposes a lot mint and a rupee path. The cell approves. The harvest does not die at the portal.",
  },
];
