// ALL 314 MODULE SPECIFICATIONS (M031-M344)
// Used by BATCH_IMPLEMENTATION_EXECUTOR.js

const MODULE_SPECS = {
  // TIER 2: Supply Chain (M031-M050) - 20 modules
  M031: { name: 'Supply Chain Coordination', table: 'supply_chains', tier: 2 },
  M032: { name: 'Supplier Management', table: 'suppliers', tier: 2 },
  M033: { name: 'Logistics Optimization', table: 'logistics', tier: 2 },
  M034: { name: 'Procurement', table: 'procurement', tier: 2 },
  M035: { name: 'Inventory Optimization', table: 'inventory', tier: 2 },
  M036: { name: 'Quality Control', table: 'quality_controls', tier: 2 },
  M037: { name: 'Warehouse Management', table: 'warehouses', tier: 2 },
  M038: { name: 'Cold Chain Management', table: 'cold_chains', tier: 2 },
  M039: { name: 'Returns & Reverse Logistics', table: 'returns', tier: 2 },
  M040: { name: 'Sustainability Tracking', table: 'sustainability', tier: 2 },
  M041: { name: 'Fleet Management', table: 'fleet', tier: 2 },
  M042: { name: 'Driver Management', table: 'drivers', tier: 2 },
  M043: { name: 'Route Optimization', table: 'routes_optimization', tier: 2 },
  M044: { name: 'Delivery Tracking', table: 'deliveries', tier: 2 },
  M045: { name: 'Last Mile Delivery', table: 'last_mile', tier: 2 },
  M046: { name: 'Real-time Visibility', table: 'visibility', tier: 2 },
  M047: { name: 'Proof of Delivery', table: 'proof_delivery', tier: 2 },
  M048: { name: 'Exception Management', table: 'exceptions', tier: 2 },
  M049: { name: 'Carrier Integration', table: 'carriers', tier: 2 },
  M050: { name: 'Analytics & Reporting', table: 'analytics', tier: 2 },

  // TIER 3: Agricultural (M051-M100) - 50 modules
  M051: { name: 'Soil Health Management', table: 'soil_health', tier: 3 },
  M052: { name: 'Crop Disease Detection', table: 'crop_diseases', tier: 3 },
  M053: { name: 'Pest Management', table: 'pest_management', tier: 3 },
  M054: { name: 'Irrigation Optimization', table: 'irrigation', tier: 3 },
  M055: { name: 'Fertilizer Recommendations', table: 'fertilizer', tier: 3 },
  M056: { name: 'Yield Prediction', table: 'yield_prediction', tier: 3 },
  M057: { name: 'Weather Advisory', table: 'weather', tier: 3 },
  M058: { name: 'Crop Insurance', table: 'crop_insurance', tier: 3 },
  M059: { name: 'Agricultural Finance', table: 'agri_finance', tier: 3 },
  M060: { name: 'Input Supply Chain', table: 'input_supply', tier: 3 },
  M061: { name: 'Livestock Health', table: 'livestock_health', tier: 3 },
  M062: { name: 'Dairy Management', table: 'dairy', tier: 3 },
  M063: { name: 'Poultry Management', table: 'poultry', tier: 3 },
  M064: { name: 'Fishery Management', table: 'fishery', tier: 3 },
  M065: { name: 'Apiary Management', table: 'apiary', tier: 3 },
  M066: { name: 'Organic Certification', table: 'organic_cert', tier: 3 },
  M067: { name: 'Land Records', table: 'land_records', tier: 3 },
  M068: { name: 'Water Rights', table: 'water_rights', tier: 3 },
  M069: { name: 'Carbon Credits', table: 'carbon_credits', tier: 3 },
  M070: { name: 'Farmer Training', table: 'training', tier: 3 },
  M071: { name: 'Market Intelligence', table: 'market_intel', tier: 3 },
  M072: { name: 'Price Forecasting', table: 'price_forecast', tier: 3 },
  M073: { name: 'Supply Chain Visibility', table: 'supply_visibility', tier: 3 },
  M074: { name: 'Blockchain Traceability', table: 'blockchain_trace', tier: 3 },
  M075: { name: 'Climate Risk Management', table: 'climate_risk', tier: 3 },
  M076: { name: 'Cooperative Management', table: 'cooperatives', tier: 3 },
  M077: { name: 'Credit Management', table: 'credit', tier: 3 },
  M078: { name: 'Government Schemes', table: 'govt_schemes', tier: 3 },
  M079: { name: 'Equipment Rental', table: 'equipment_rental', tier: 3 },
  M080: { name: 'Agri-Tourism', table: 'agri_tourism', tier: 3 },
  M081: { name: 'Rural Employment', table: 'rural_employment', tier: 3 },
  M082: { name: 'Education & Skilling', table: 'education', tier: 3 },
  M083: { name: 'Community Building', table: 'community', tier: 3 },
  M084: { name: 'Sustainability Goals', table: 'sustainability_goals', tier: 3 },
  M085: { name: 'Health & Safety', table: 'health_safety', tier: 3 },
  M086: { name: 'Water Management', table: 'water_mgmt', tier: 3 },
  M087: { name: 'Soil Conservation', table: 'soil_conservation', tier: 3 },
  M088: { name: 'Biodiversity Tracking', table: 'biodiversity', tier: 3 },
  M089: { name: 'Renewable Energy', table: 'renewable_energy', tier: 3 },
  M090: { name: 'Waste Management', table: 'waste_mgmt', tier: 3 },
  M091: { name: 'Social Impact Metrics', table: 'social_impact', tier: 3 },
  M092: { name: 'Gender Empowerment', table: 'gender_empowerment', tier: 3 },
  M093: { name: 'Youth Engagement', table: 'youth_engagement', tier: 3 },
  M094: { name: 'Youth Mentorship', table: 'mentorship', tier: 3 },
  M095: { name: 'Rural Finance', table: 'rural_finance', tier: 3 },
  M096: { name: 'Microfinance', table: 'microfinance', tier: 3 },
  M097: { name: 'Insurance Products', table: 'insurance', tier: 3 },
  M098: { name: 'Pension Schemes', table: 'pensions', tier: 3 },
  M099: { name: 'Savings Programs', table: 'savings', tier: 3 },
  M100: { name: 'Investment Opportunities', table: 'investments', tier: 3 },

  // TIER 4: Enterprise (M101-M150) - 50 modules
  M101: { name: 'ERP Integration', table: 'erp_integration', tier: 4 },
  M102: { name: 'Advanced Analytics', table: 'advanced_analytics', tier: 4 },
  M103: { name: 'Business Intelligence', table: 'bi', tier: 4 },
  M104: { name: 'Compliance & Audit', table: 'compliance', tier: 4 },
  M105: { name: 'Custom Reports', table: 'custom_reports', tier: 4 },
  M106: { name: 'Data Warehousing', table: 'data_warehouse', tier: 4 },
  M107: { name: 'API Management', table: 'api_management', tier: 4 },
  M108: { name: 'Workflow Automation', table: 'workflows', tier: 4 },
  M109: { name: 'Document Management', table: 'documents', tier: 4 },
  M110: { name: 'Contract Management', table: 'contracts', tier: 4 },
  M111: { name: 'Project Management', table: 'projects', tier: 4 },
  M112: { name: 'Resource Planning', table: 'resource_planning', tier: 4 },
  M113: { name: 'Budgeting & Forecasting', table: 'budgeting', tier: 4 },
  M114: { name: 'Performance Management', table: 'performance', tier: 4 },
  M115: { name: 'Quality Management', table: 'quality_mgmt', tier: 4 },
  M116: { name: 'Risk Management', table: 'risk_mgmt', tier: 4 },
  M117: { name: 'Vendor Management', table: 'vendors', tier: 4 },
  M118: { name: 'Procurement Management', table: 'procurement_mgmt', tier: 4 },
  M119: { name: 'Inventory Management', table: 'inventory_mgmt', tier: 4 },
  M120: { name: 'Asset Management', table: 'assets', tier: 4 },
  M121: { name: 'HR Management', table: 'hr', tier: 4 },
  M122: { name: 'Payroll Management', table: 'payroll', tier: 4 },
  M123: { name: 'Learning Management', table: 'learning', tier: 4 },
  M124: { name: 'Knowledge Management', table: 'knowledge', tier: 4 },
  M125: { name: 'Communication Platform', table: 'communication', tier: 4 },
  M126: { name: 'Customer Relationship Management', table: 'crm', tier: 4 },
  M127: { name: 'Sales Pipeline Management', table: 'sales_pipeline', tier: 4 },
  M128: { name: 'Marketing Automation', table: 'marketing_automation', tier: 4 },
  M129: { name: 'Campaign Management', table: 'campaigns', tier: 4 },
  M130: { name: 'Social Media Management', table: 'social_media', tier: 4 },
  M131: { name: 'Email Management', table: 'email', tier: 4 },
  M132: { name: 'Chat & Messaging', table: 'messaging', tier: 4 },
  M133: { name: 'Video Conferencing', table: 'video_conference', tier: 4 },
  M134: { name: 'Event Management', table: 'events', tier: 4 },
  M135: { name: 'Ticketing System', table: 'ticketing', tier: 4 },
  M136: { name: 'Survey & Feedback', table: 'surveys', tier: 4 },
  M137: { name: 'Complaint Management', table: 'complaints', tier: 4 },
  M138: { name: 'Issue Tracking', table: 'issues', tier: 4 },
  M139: { name: 'Bug Reporting', table: 'bugs', tier: 4 },
  M140: { name: 'Change Management', table: 'change_mgmt', tier: 4 },
  M141: { name: 'Release Management', table: 'releases', tier: 4 },
  M142: { name: 'Deployment Management', table: 'deployments', tier: 4 },
  M143: { name: 'Infrastructure Management', table: 'infrastructure', tier: 4 },
  M144: { name: 'Monitoring & Alerting', table: 'monitoring', tier: 4 },
  M145: { name: 'Logging & Analysis', table: 'logging', tier: 4 },
  M146: { name: 'Security Management', table: 'security', tier: 4 },
  M147: { name: 'Access Control', table: 'access_control', tier: 4 },
  M148: { name: 'Backup & Recovery', table: 'backup', tier: 4 },
  M149: { name: 'Disaster Recovery', table: 'disaster_recovery', tier: 4 },
  M150: { name: 'Business Continuity', table: 'business_continuity', tier: 4 },

  // TIER 5: Advanced Enterprise (M151-M200) - 50 modules
  M151: { name: 'Advanced Analytics Engine', table: 'analytics_engine', tier: 5 },
  M152: { name: 'Machine Learning Integration', table: 'ml_integration', tier: 5 },
  M153: { name: 'AI Predictions', table: 'ai_predictions', tier: 5 },
  M154: { name: 'Natural Language Processing', table: 'nlp', tier: 5 },
  M155: { name: 'Computer Vision', table: 'computer_vision', tier: 5 },
  M156: { name: 'IoT Data Processing', table: 'iot_data', tier: 5 },
  M157: { name: 'Real-time Data Streaming', table: 'data_streaming', tier: 5 },
  M158: { name: 'Edge Computing', table: 'edge_computing', tier: 5 },
  M159: { name: 'Blockchain Integration', table: 'blockchain', tier: 5 },
  M160: { name: 'Cryptocurrency Payments', table: 'crypto_payments', tier: 5 },
  M161: { name: 'Smart Contracts', table: 'smart_contracts', tier: 5 },
  M162: { name: 'Decentralized Storage', table: 'decentralized_storage', tier: 5 },
  M163: { name: 'Web3 Integration', table: 'web3', tier: 5 },
  M164: { name: 'Virtual Reality', table: 'vr', tier: 5 },
  M165: { name: 'Augmented Reality', table: 'ar', tier: 5 },
  M166: { name: 'Mixed Reality', table: 'mr', tier: 5 },
  M167: { name: 'Voice Interface', table: 'voice', tier: 5 },
  M168: { name: 'Gesture Recognition', table: 'gesture', tier: 5 },
  M169: { name: 'Biometric Authentication', table: 'biometric', tier: 5 },
  M170: { name: 'Multi-factor Authentication', table: 'mfa', tier: 5 },
  M171: { name: 'Zero Trust Security', table: 'zero_trust', tier: 5 },
  M172: { name: 'Quantum Encryption', table: 'quantum_encryption', tier: 5 },
  M173: { name: 'Privacy Protection', table: 'privacy', tier: 5 },
  M174: { name: 'Data Anonymization', table: 'anonymization', tier: 5 },
  M175: { name: 'Compliance Automation', table: 'compliance_automation', tier: 5 },
  M176: { name: 'Regulatory Reporting', table: 'regulatory_reporting', tier: 5 },
  M177: { name: 'Tax Optimization', table: 'tax_optimization', tier: 5 },
  M178: { name: 'Financial Modeling', table: 'financial_modeling', tier: 5 },
  M179: { name: 'Investment Analysis', table: 'investment_analysis', tier: 5 },
  M180: { name: 'Portfolio Management', table: 'portfolio', tier: 5 },
  M181: { name: 'Risk Analytics', table: 'risk_analytics', tier: 5 },
  M182: { name: 'Predictive Analytics', table: 'predictive_analytics', tier: 5 },
  M183: { name: 'Sentiment Analysis', table: 'sentiment', tier: 5 },
  M184: { name: 'Customer Analytics', table: 'customer_analytics', tier: 5 },
  M185: { name: 'Behavioral Analytics', table: 'behavioral_analytics', tier: 5 },
  M186: { name: 'Competitive Intelligence', table: 'competitive_intel', tier: 5 },
  M187: { name: 'Market Research', table: 'market_research', tier: 5 },
  M188: { name: 'Trend Analysis', table: 'trend_analysis', tier: 5 },
  M189: { name: 'Forecasting Engine', table: 'forecasting', tier: 5 },
  M190: { name: 'Data Integration', table: 'data_integration', tier: 5 },
  M191: { name: 'ETL Processing', table: 'etl', tier: 5 },
  M192: { name: 'Data Quality', table: 'data_quality', tier: 5 },
  M193: { name: 'Data Governance', table: 'data_governance', tier: 5 },
  M194: { name: 'Master Data Management', table: 'master_data', tier: 5 },
  M195: { name: 'Metadata Management', table: 'metadata', tier: 5 },
  M196: { name: 'Data Catalog', table: 'data_catalog', tier: 5 },
  M197: { name: 'Data Lineage', table: 'data_lineage', tier: 5 },
  M198: { name: 'Data Dictionary', table: 'data_dictionary', tier: 5 },
  M199: { name: 'Data Profiling', table: 'data_profiling', tier: 5 },
  M200: { name: 'Data Management Hub', table: 'data_hub', tier: 5 },

  // TIER 6: Specialized (M201-M344) - 144 modules
  // AI/ML (M201-M220) - 20 modules
  M201: { name: 'Deep Learning Framework', table: 'deep_learning', tier: 6 },
  M202: { name: 'Neural Networks', table: 'neural_networks', tier: 6 },
  M203: { name: 'Reinforcement Learning', table: 'reinforcement_learning', tier: 6 },
  M204: { name: 'Feature Engineering', table: 'feature_engineering', tier: 6 },
  M205: { name: 'Model Training Pipeline', table: 'model_training', tier: 6 },
  M206: { name: 'Model Evaluation', table: 'model_evaluation', tier: 6 },
  M207: { name: 'Model Optimization', table: 'model_optimization', tier: 6 },
  M208: { name: 'Transfer Learning', table: 'transfer_learning', tier: 6 },
  M209: { name: 'Ensemble Methods', table: 'ensemble', tier: 6 },
  M210: { name: 'Anomaly Detection', table: 'anomaly_detection', tier: 6 },
  M211: { name: 'Clustering Algorithms', table: 'clustering', tier: 6 },
  M212: { name: 'Classification Models', table: 'classification', tier: 6 },
  M213: { name: 'Regression Analysis', table: 'regression', tier: 6 },
  M214: { name: 'Time Series Forecasting', table: 'time_series', tier: 6 },
  M215: { name: 'Text Classification', table: 'text_classification', tier: 6 },
  M216: { name: 'Information Extraction', table: 'information_extraction', tier: 6 },
  M217: { name: 'Question Answering', table: 'question_answering', tier: 6 },
  M218: { name: 'Machine Translation', table: 'machine_translation', tier: 6 },
  M219: { name: 'Recommendation Systems', table: 'recommendations', tier: 6 },
  M220: { name: 'Personalization Engine', table: 'personalization', tier: 6 },

  // IoT & Sensors (M221-M240) - 20 modules
  M221: { name: 'Sensor Data Collection', table: 'sensor_data', tier: 6 },
  M222: { name: 'Device Management', table: 'device_mgmt', tier: 6 },
  M223: { name: 'IoT Gateway', table: 'iot_gateway', tier: 6 },
  M224: { name: 'MQTT Broker', table: 'mqtt', tier: 6 },
  M225: { name: 'CoAP Protocol', table: 'coap', tier: 6 },
  M226: { name: 'Data Aggregation', table: 'data_aggregation', tier: 6 },
  M227: { name: 'Time Series Database', table: 'timeseries_db', tier: 6 },
  M228: { name: 'Sensor Calibration', table: 'sensor_calibration', tier: 6 },
  M229: { name: 'Alert Management', table: 'alerts', tier: 6 },
  M230: { name: 'Predictive Maintenance', table: 'predictive_maintenance', tier: 6 },
  M231: { name: 'Resource Monitoring', table: 'resource_monitoring', tier: 6 },
  M232: { name: 'Environmental Monitoring', table: 'environmental_monitoring', tier: 6 },
  M233: { name: 'Health Monitoring', table: 'health_monitoring', tier: 6 },
  M234: { name: 'Safety Systems', table: 'safety_systems', tier: 6 },
  M235: { name: 'Telemetry Collection', table: 'telemetry', tier: 6 },
  M236: { name: 'Edge Analytics', table: 'edge_analytics', tier: 6 },
  M237: { name: 'Geolocation Tracking', table: 'geolocation', tier: 6 },
  M238: { name: 'Asset Tracking', table: 'asset_tracking', tier: 6 },
  M239: { name: 'WiFi Analytics', table: 'wifi_analytics', tier: 6 },
  M240: { name: 'Network Optimization', table: 'network_optimization', tier: 6 },

  // Blockchain (M241-M260) - 20 modules
  M241: { name: 'Blockchain Node', table: 'blockchain_node', tier: 6 },
  M242: { name: 'Smart Contract Platform', table: 'smart_contract_platform', tier: 6 },
  M243: { name: 'Consensus Mechanisms', table: 'consensus', tier: 6 },
  M244: { name: 'Wallet Management', table: 'wallets', tier: 6 },
  M245: { name: 'Transaction Processing', table: 'transactions', tier: 6 },
  M246: { name: 'Token Management', table: 'tokens', tier: 6 },
  M247: { name: 'NFT Platform', table: 'nft', tier: 6 },
  M248: { name: 'DeFi Protocol', table: 'defi', tier: 6 },
  M249: { name: 'Supply Chain Verification', table: 'supply_verification', tier: 6 },
  M250: { name: 'Certificate Authority', table: 'certificate_authority', tier: 6 },
  M251: { name: 'Digital Identity', table: 'digital_identity', tier: 6 },
  M252: { name: 'Access Rights', table: 'access_rights', tier: 6 },
  M253: { name: 'Multi-signature Accounts', table: 'multisig', tier: 6 },
  M254: { name: 'Escrow Services', table: 'escrow', tier: 6 },
  M255: { name: 'Atomic Swaps', table: 'atomic_swaps', tier: 6 },
  M256: { name: 'Merkle Trees', table: 'merkle_trees', tier: 6 },
  M257: { name: 'Zero-knowledge Proofs', table: 'zero_knowledge', tier: 6 },
  M258: { name: 'Sidechain Integration', table: 'sidechains', tier: 6 },
  M259: { name: 'Cross-chain Bridge', table: 'cross_chain', tier: 6 },
  M260: { name: 'Oracle Services', table: 'oracles', tier: 6 },

  // VR/AR/XR (M261-M280) - 20 modules
  M261: { name: '3D Rendering Engine', table: '3d_rendering', tier: 6 },
  M262: { name: 'Spatial Computing', table: 'spatial_computing', tier: 6 },
  M263: { name: 'Hand Tracking', table: 'hand_tracking', tier: 6 },
  M264: { name: 'Eye Tracking', table: 'eye_tracking', tier: 6 },
  M265: { name: 'Motion Capture', table: 'motion_capture', tier: 6 },
  M266: { name: 'Avatar System', table: 'avatars', tier: 6 },
  M267: { name: 'Virtual Environments', table: 'virtual_environments', tier: 6 },
  M268: { name: 'Metaverse Integration', table: 'metaverse', tier: 6 },
  M269: { name: 'Hologram Display', table: 'holograms', tier: 6 },
  M270: { name: 'Mixed Reality Rendering', table: 'mr_rendering', tier: 6 },
  M271: { name: 'Marker Detection', table: 'marker_detection', tier: 6 },
  M272: { name: 'Object Recognition', table: 'object_recognition', tier: 6 },
  M273: { name: 'Image Tracking', table: 'image_tracking', tier: 6 },
  M274: { name: 'SLAM Technology', table: 'slam', tier: 6 },
  M275: { name: 'Physics Engine', table: 'physics_engine', tier: 6 },
  M276: { name: 'Haptic Feedback', table: 'haptic_feedback', tier: 6 },
  M277: { name: 'Audio Spatialization', table: 'audio_spatial', tier: 6 },
  M278: { name: 'Real-time Collaboration', table: 'realtime_collab', tier: 6 },
  M279: { name: 'XR Platform Services', table: 'xr_services', tier: 6 },
  M280: { name: 'Content Distribution Network', table: 'content_cdn', tier: 6 },

  // Advanced Security (M281-M300) - 20 modules
  M281: { name: 'Encryption Services', table: 'encryption', tier: 6 },
  M282: { name: 'Key Management Service', table: 'key_management', tier: 6 },
  M283: { name: 'Digital Signatures', table: 'digital_signatures', tier: 6 },
  M284: { name: 'PKIX Infrastructure', table: 'pkix', tier: 6 },
  M285: { name: 'OAuth 2.0 Provider', table: 'oauth', tier: 6 },
  M286: { name: 'OpenID Connect', table: 'openid', tier: 6 },
  M287: { name: 'SAML Identity Provider', table: 'saml', tier: 6 },
  M288: { name: 'Single Sign-On', table: 'sso', tier: 6 },
  M289: { name: 'LDAP Directory', table: 'ldap', tier: 6 },
  M290: { name: 'Role Based Access Control', table: 'rbac', tier: 6 },
  M291: { name: 'Attribute Based Access Control', table: 'abac', tier: 6 },
  M292: { name: 'Threat Detection', table: 'threat_detection', tier: 6 },
  M293: { name: 'Intrusion Prevention', table: 'intrusion_prevention', tier: 6 },
  M294: { name: 'DDoS Protection', table: 'ddos_protection', tier: 6 },
  M295: { name: 'Web Application Firewall', table: 'waf', tier: 6 },
  M296: { name: 'Vulnerability Management', table: 'vulnerability_mgmt', tier: 6 },
  M297: { name: 'Penetration Testing', table: 'pentest', tier: 6 },
  M298: { name: 'Security Information Management', table: 'siem', tier: 6 },
  M299: { name: 'Forensics & Analysis', table: 'forensics', tier: 6 },
  M300: { name: 'Security Compliance', table: 'security_compliance', tier: 6 },

  // Data Science (M301-M320) - 20 modules
  M301: { name: 'Data Collection Pipeline', table: 'data_collection', tier: 6 },
  M302: { name: 'Data Validation', table: 'data_validation', tier: 6 },
  M303: { name: 'Data Transformation', table: 'data_transformation', tier: 6 },
  M304: { name: 'Data Cleaning', table: 'data_cleaning', tier: 6 },
  M305: { name: 'Data Deduplication', table: 'data_deduplication', tier: 6 },
  M306: { name: 'Feature Scaling', table: 'feature_scaling', tier: 6 },
  M307: { name: 'Dimensionality Reduction', table: 'dimensionality_reduction', tier: 6 },
  M308: { name: 'Statistical Analysis', table: 'statistical_analysis', tier: 6 },
  M309: { name: 'Hypothesis Testing', table: 'hypothesis_testing', tier: 6 },
  M310: { name: 'Correlation Analysis', table: 'correlation_analysis', tier: 6 },
  M311: { name: 'Regression Analysis Advanced', table: 'regression_advanced', tier: 6 },
  M312: { name: 'ANOVA Analysis', table: 'anova', tier: 6 },
  M313: { name: 'Bayesian Analysis', table: 'bayesian', tier: 6 },
  M314: { name: 'Monte Carlo Simulation', table: 'monte_carlo', tier: 6 },
  M315: { name: 'Survival Analysis', table: 'survival_analysis', tier: 6 },
  M316: { name: 'Causal Inference', table: 'causal_inference', tier: 6 },
  M317: { name: 'A/B Testing', table: 'ab_testing', tier: 6 },
  M318: { name: 'Multivariate Testing', table: 'multivariate_testing', tier: 6 },
  M319: { name: 'Experimental Design', table: 'experimental_design', tier: 6 },
  M320: { name: 'Results Visualization', table: 'visualization', tier: 6 },

  // Integration & APIs (M321-M344) - 24 modules
  M321: { name: 'REST API Framework', table: 'rest_api', tier: 6 },
  M322: { name: 'GraphQL Server', table: 'graphql', tier: 6 },
  M323: { name: 'WebSocket Server', table: 'websocket', tier: 6 },
  M324: { name: 'gRPC Framework', table: 'grpc', tier: 6 },
  M325: { name: 'API Gateway', table: 'api_gateway', tier: 6 },
  M326: { name: 'API Rate Limiting', table: 'rate_limiting', tier: 6 },
  M327: { name: 'API Versioning', table: 'api_versioning', tier: 6 },
  M328: { name: 'API Documentation', table: 'api_docs', tier: 6 },
  M329: { name: 'API Testing Framework', table: 'api_testing', tier: 6 },
  M330: { name: 'Webhook Management', table: 'webhooks', tier: 6 },
  M331: { name: 'Message Queue', table: 'message_queue', tier: 6 },
  M332: { name: 'Event Streaming', table: 'event_streaming', tier: 6 },
  M333: { name: 'Event Sourcing', table: 'event_sourcing', tier: 6 },
  M334: { name: 'CQRS Pattern', table: 'cqrs', tier: 6 },
  M335: { name: 'Service Discovery', table: 'service_discovery', tier: 6 },
  M336: { name: 'Load Balancing', table: 'load_balancing', tier: 6 },
  M337: { name: 'Circuit Breaker', table: 'circuit_breaker', tier: 6 },
  M338: { name: 'Retry Mechanism', table: 'retry_mechanism', tier: 6 },
  M339: { name: 'Bulkhead Pattern', table: 'bulkhead', tier: 6 },
  M340: { name: 'Distributed Tracing', table: 'distributed_tracing', tier: 6 },
  M341: { name: 'Health Checks', table: 'health_checks', tier: 6 },
  M342: { name: 'Configuration Management', table: 'config_management', tier: 6 },
  M343: { name: 'Secrets Management', table: 'secrets', tier: 6 },
  M344: { name: 'Feature Flags', table: 'feature_flags', tier: 6 },
};

module.exports = MODULE_SPECS;
