import React,{useEffect,useState} from 'react';
import {getEnterpriseModuleOverview,createEnterpriseTask,createEnterpriseWorkflow,queueEnterpriseDecision} from '../services/enterpriseModule550Api';

const label=x=>String(x||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function UniversalEnterpriseModulePage({moduleCode}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[tab,setTab]=useState('operations'),[busy,setBusy]=useState(false);
 const load=()=>getEnterpriseModuleOverview(moduleCode).then(setData).catch(e=>setError(e.message||'Unable to load module runtime'));
 useEffect(()=>{let active=true;getEnterpriseModuleOverview(moduleCode).then(x=>active&&setData(x)).catch(e=>active&&setError(e.message));return()=>{active=false};},[moduleCode]);
 const run=async(fn)=>{setBusy(true);setError('');try{await fn();await load();}catch(e){setError(e.message||'Operation failed');}finally{setBusy(false);}};
 if(error&&!data)return <section role="alert" className="p-6 rounded-xl border"><h1 className="text-xl font-semibold">{moduleCode}</h1><p>{error}</p></section>;
 if(!data)return <section className="p-6" aria-busy="true"><h1 className="text-xl font-semibold">{moduleCode}</h1><p>Loading enterprise workspace…</p></section>;
 const d=data.definition;
 return <section className="space-y-5" data-module-code={moduleCode}>
  <header className="rounded-2xl border p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-wide">{moduleCode} · Wave {d.portfolioWave}</p><h1 className="text-2xl font-semibold">{d.name}</h1><p className="mt-1 text-sm">{label(d.implementationMode)} · {d.physicalModule?'bespoke backend detected':'governed runtime'} · {d.physicalPage?'bespoke page detected':'universal operational page'}</p></div><div className="text-sm"><strong>Decision policy:</strong> human approval + maker/checker</div></div></header>
  {error&&<div role="alert" className="rounded-lg border p-3">{error}</div>}
  <section className="grid gap-3 md:grid-cols-3 xl:grid-cols-6" aria-label="Module KPIs">{data.kpis.map(k=><article className="rounded-xl border p-3" key={k.metric_key}><p className="text-xs">{label(k.metric_key)}</p><strong className="text-lg">{k.metric_value??'—'}</strong><p className="text-xs">{k.source_reference?'Source verified':'Awaiting authoritative data'}</p></article>)}</section>
  <nav className="flex flex-wrap gap-2" aria-label="Enterprise module workspace">{d.surfaces.map(x=><button type="button" disabled={busy} aria-pressed={tab===x} className="rounded-lg border px-3 py-2" onClick={()=>setTab(x)} key={x}>{label(x)}</button>)}</nav>
  {tab==='operations'&&<section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><article className="rounded-xl border p-4"><h2 className="font-semibold">Operational control</h2><p>Tasks, ownership, SLA, priority, status, evidence and exceptions are managed through the shared enterprise runtime.</p><button className="mt-3 rounded-lg border px-3 py-2" disabled={busy} onClick={()=>run(()=>createEnterpriseTask(moduleCode,{title:`${moduleCode} operational review`,priority:'normal'}))}>Create review task</button></article><article className="rounded-xl border p-4"><h2 className="font-semibold">Authoritative implementation</h2><ul>{Object.entries(d.artifacts).map(([k,v])=><li key={k}>{label(k)}: {v?'detected':'runtime fallback'}</li>)}</ul></article><article className="rounded-xl border p-4"><h2 className="font-semibold">Integration posture</h2><p>Bespoke services remain authoritative where detected. Missing modules use controlled runtime records until domain promotion.</p></article></section>}
  {tab==='workflow'&&<section className="rounded-xl border p-4"><h2 className="font-semibold">Workflow state machine</h2><ol className="mt-3 flex flex-wrap gap-2">{d.workflow.map((x,i)=><li className="rounded-lg border px-3 py-2" key={x}>{i+1}. {label(x)}</li>)}</ol><button className="mt-4 rounded-lg border px-3 py-2" disabled={busy} onClick={()=>run(()=>createEnterpriseWorkflow(moduleCode,{entity_type:'module_record',entity_id:`manual-${Date.now()}`}))}>Start governed workflow</button></section>}
  {tab==='visualization'&&<section className="grid gap-3 md:grid-cols-2"><article className="rounded-xl border p-4"><h2 className="font-semibold">KPI visualization contract</h2><p>Only source-backed KPI snapshots render numerical values. Unsourced values remain blank.</p></article><article className="rounded-xl border p-4"><h2 className="font-semibold">Context visualization</h2><p>Maps, charts, relationship graphs and timelines are selected by the promoted domain implementation; the universal runtime supplies provenance and state.</p></article></section>}
  {tab==='work_queue'&&<section className="rounded-xl border p-4"><h2 className="font-semibold">Work queue</h2><div className="mt-3 grid gap-2 md:grid-cols-3">{(data.tasks.length?data.tasks:[{status:'open',priority:'normal',count:0}]).map((x,i)=><div className="rounded-lg border p-3" key={`${x.status}-${x.priority}-${i}`}><strong>{x.count}</strong><p>{label(x.status)} · {label(x.priority)}</p></div>)}</div></section>}
  {tab==='decision_center'&&<section className="rounded-xl border p-4"><h2 className="font-semibold">Decision centre</h2><p>AI recommendations are advisory. Consequential actions require accountable human approval and maker/checker separation.</p><button className="mt-3 rounded-lg border px-3 py-2" disabled={busy} onClick={()=>run(()=>queueEnterpriseDecision(moduleCode,{decision_type:'operational_review',proposed_action:{action:'review'},risk_level:'normal'}))}>Queue decision review</button></section>}
  {tab==='erp_controls'&&<section className="grid gap-2 md:grid-cols-3">{d.erpControls.map(x=><article className="rounded-lg border p-3" key={x}><strong>{label(x)}</strong></article>)}</section>}
  {tab==='integrations'&&<section className="rounded-xl border p-4"><h2 className="font-semibold">Integration contract</h2><p>Authentication, tenant/geography/record scope, correlation, validation, idempotency, audit and standardized errors are mandatory middleware controls.</p><div className="mt-3 flex flex-wrap gap-2">{d.middleware.map(x=><span className="rounded-full border px-3 py-1 text-sm" key={x}>{label(x)}</span>)}</div></section>}
  {tab==='evidence_audit'&&<section className="rounded-xl border p-4"><h2 className="font-semibold">Evidence & audit</h2><p>Every consequential workflow transition, KPI, decision and exception must retain source reference, actor, correlation identifier, evidence and outcome history.</p><h3 className="mt-4 font-semibold">Certification gates</h3><ul className="mt-2 grid gap-2 md:grid-cols-2">{d.certification.map(x=><li className="rounded-lg border p-2" key={x}>{label(x)}</li>)}</ul></section>}
  {tab==='ai_assist'&&<section className="rounded-xl border p-4"><h2 className="font-semibold">Governed AI assist</h2><div className="mt-3 flex flex-wrap gap-2">{d.aiCapabilities.map(x=><span className="rounded-full border px-3 py-1 text-sm" key={x}>{label(x)}</span>)}</div><p className="mt-3">AI may analyse, predict, recommend, simulate and generate explanations; it cannot override authoritative data or approve consequential actions.</p></section>}
 </section>;
}
