# EBDESIGN: Database Setup Script
# Creates .env file with PostgreSQL configuration and runs migrations

$ErrorActionPreference = "Stop"

$backendDir = "C:/Users/DIYA GOEL/Downloads/EBDESIGN/backend"
$envFile = "$backendDir/.env"
$envExample = "$backendDir/.env.example"

Write-Output "EBDESIGN Database Setup"
Write-Output "======================"
Write-Output ""

# Check if .env already exists
if (Test-Path $envFile) {
    Write-Output ".env file already exists at $envFile"
    $overwrite = Read-Host "Do you want to overwrite it? (y/N)"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Output "Setup cancelled."
        exit 0
    }
}

# Get database configuration
Write-Output "Please provide PostgreSQL connection details:"
Write-Output ""

$pgHost = Read-Host "PostgreSQL host (default: localhost)"
if (-not $pgHost) { $pgHost = "localhost" }

$pgPort = Read-Host "PostgreSQL port (default: 5432)"
if (-not $pgPort) { $pgPort = "5432" }

$pgDatabase = Read-Host "Database name (default: afrera_db)"
if (-not $pgDatabase) { $pgDatabase = "afrera_db" }

$pgUser = Read-Host "Database user (default: postgres)"
if (-not $pgUser) { $pgUser = "postgres" }

$pgPassword = Read-Host "Database password (leave empty for no password)"

# Generate secure JWT secret
$jwtSecret = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 48 | % {[char]$_})

# Create .env file
Write-Output "Creating .env file..."
$envContent = @"
# AFRERA Backend — environment configuration
# Generated by setup_database.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

# ---------------------------------------------------------------------------
# Core
# ---------------------------------------------------------------------------
NODE_ENV=development
PORT=3001
BASE_URL=http://localhost:3001
FRONTEND_URL=http://localhost:3000
LOG_LEVEL=info
LOG_DIR=logs
ENABLE_GRAPHQL=false

# ---------------------------------------------------------------------------
# PostgreSQL (primary relational store)
# ---------------------------------------------------------------------------
PG_HOST=$pgHost
PG_PORT=$pgPort
PG_DATABASE=$pgDatabase
PG_USER=$pgUser
PG_PASSWORD=$pgPassword
DATABASE_URL=postgresql://$pgUser${if($pgPassword){":$pgPassword"}}@$pgHost`:$pgPort/$pgDatabase
TEST_DATABASE_URL=postgresql://$pgUser${if($pgPassword){":$pgPassword"}}@$pgHost`:$pgPort/${pgDatabase}_test

# ---------------------------------------------------------------------------
# MongoDB (document store)
# ---------------------------------------------------------------------------
MONGO_URI=mongodb://localhost:27017/afrera_mongo
MONGODB_URI=mongodb://localhost:27017/afrera_mongo
MONGO_DATABASE=afrera_mongo

# ---------------------------------------------------------------------------
# Redis (cache / queues)
# ---------------------------------------------------------------------------
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=
REDIS_DB=0

# ---------------------------------------------------------------------------
# Auth / crypto
# ---------------------------------------------------------------------------
JWT_SECRET=$jwtSecret
JWT_ACCESS_EXPIRY=15m
JWT_REFRESH_EXPIRY=7d
JWT_ISSUER=afrera-platform
JWT_AUDIENCE=afrera-users
ENCRYPTION_KEY=
OFFLINE_PAYMENT_SECRET=
SYNC_SECRET=
TRUSTED_IPS=

# ---------------------------------------------------------------------------
# OAuth providers (disabled by default)
# ---------------------------------------------------------------------------
GOOGLE_OAUTH_ENABLED=false
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REDIRECT_URI=http://localhost:3001/api/v1/auth/oauth/google/callback
GOOGLE_PROJECT_ID=

FACEBOOK_OAUTH_ENABLED=false
FACEBOOK_CLIENT_ID=
FACEBOOK_CLIENT_SECRET=
FACEBOOK_REDIRECT_URI=http://localhost:3001/api/v1/auth/oauth/facebook/callback

# ---------------------------------------------------------------------------
# Twilio (SMS / voice / WhatsApp) — mock mode when unset
# ---------------------------------------------------------------------------
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_PHONE_NUMBER=
TWILIO_VOICE_ENABLED=false
TWILIO_WHATSAPP_NUMBER=
PUBLIC_BASE_URL=

# ---------------------------------------------------------------------------
# ERP integrations (simulated by default)
# ---------------------------------------------------------------------------
SAP_ENABLED=false
SAP_HOST=
SAP_PORT=
SAP_CLIENT=
SAP_SYSTEM_ID=
SAP_USER=
SAP_PASSWORD=

ORACLE_ENABLED=false
ORACLE_HOST=
ORACLE_PORT=1521
ORACLE_SERVICE=
ORACLE_USER=
ORACLE_PASSWORD=

CUSTOM_ERP_ENABLED=false
CUSTOM_ERP_API_URL=
CUSTOM_ERP_API_KEY=
"@

$envContent | Out-File -FilePath $envFile -Encoding UTF8
Write-Output ".env file created successfully."

# Test database connection
Write-Output ""
Write-Output "Testing database connection..."
try {
    $testConnectionString = "postgresql://$pgUser${if($pgPassword){":$pgPassword"}}@$pgHost`:$pgPort/$pgDatabase"
    $env:PGPASSWORD = $pgPassword
    $result = & psql -h $pgHost -p $pgPort -U $pgUser -d $pgDatabase -c "SELECT 1" 2>&1
    if ($LASTEXITCODE -eq 0) {
        Write-Output "Database connection successful."
    } else {
        Write-Output "Warning: Could not connect to database. Please ensure PostgreSQL is running and the database exists."
        Write-Output "You can create the database with: createdb $pgDatabase"
    }
} catch {
    Write-Output "Warning: psql command not found. Please ensure PostgreSQL client tools are installed."
}

Write-Output ""
Write-Output "Database setup complete."
Write-Output ""
Write-Output "Next steps:"
Write-Output "1. Ensure PostgreSQL is running"
Write-Output "2. Create database if needed: createdb $pgDatabase"
Write-Output "3. Run migrations: npm run migrate"
Write-Output "4. Start the server: npm start"
