'use strict';
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const pool=require('../database/pool');

const MIN=1,MAX=550;
const ROOT=path.resolve(__dirname,'..','..','..');
const STANDARD={
 surfaces:['operations','workflow','visualization','work_queue','decision_center','erp_controls','integrations','evidence_audit','ai_assist'],
 middleware:['authentication','rbac_abac','tenant_scope','geography_scope','record_scope','validation','idempotency','correlation_id','rate_limit','audit','standard_errors'],
 erpControls:['master_data_integrity','state_machine','maker_checker','transaction_boundary','idempotency','exception_queue','sla_escalation','evidence_linkage','audit_trail','temporal_history'],
 ux:['responsive','accessible','multilingual','keyboard_navigable','loading_empty_error_success_states','search_filter_sort','saved_views','bulk_actions_with_guardrails','export_with_permissions','activity_timeline','offline_degraded_state_awareness'],
 ai:['generative_ai','analytical_ai','predictive_ai','prescriptive_ai','recommendation','anomaly_detection','scenario_simulation','knowledge_graph','digital_twin','governed_agents'],
 workflow:['capture','validate','enrich','review','approve','execute','verify','measure'],
 kpis:['coverage','quality','backlog','sla_compliance','exceptions','outcome'],
 certification:['identity_resolved','authoritative_service_or_governed_runtime','database_contract','api_contract','middleware_enforced','page_renders','workflow_real_path','authorization_negative_tests','maker_checker_tests','kpi_provenance','accessibility','observability','ai_evaluation_where_applicable','e2e']
};
function normalize(input){const m=String(input||'').toUpperCase().match(/^M(\d{1,3})$/);if(!m)throw Object.assign(new Error('Invalid module code'),{statusCode:400});const n=Number(m[1]);if(n<MIN||n>MAX)throw Object.assign(new Error(`Module outside M001-M${MAX}`),{statusCode:404});return `M${String(n).padStart(3,'0')}`;}
function existingPaths(code){const backend=path.join(ROOT,'backend','src','modules',code);const frontend=path.join(ROOT,'frontend','src','modules',code,`${code}Page.jsx`);return {backend,frontend,backendExists:fs.existsSync(backend),frontendExists:fs.existsSync(frontend)};}
function readTitle(code,p){if(!p.backendExists)return code;for(const f of ['README.md','module.json']){const file=path.join(p.backend,f);if(!fs.existsSync(file))continue;try{const raw=fs.readFileSync(file,'utf8');if(f==='module.json'){const j=JSON.parse(raw);return j.name||j.title||j.module_name||code;}const heading=raw.split(/\r?\n/).find(x=>/^#\s+/.test(x));if(heading)return heading.replace(/^#\s+/,'').replace(/^M\d+\s*[-–:]?\s*/i,'').trim()||code;}catch{} }return code;}
function artifactEvidence(code,p){const names=['service.js','controller.js','routes.js','model.sql','index.js'];const assets=Object.fromEntries(names.map(n=>[n,fs.existsSync(path.join(p.backend,n))]));return {...assets,page:p.frontendExists};}
function definition(input){const code=normalize(input),n=Number(code.slice(1)),p=existingPaths(code),artifacts=artifactEvidence(code,p),physical=Object.values(artifacts).some(Boolean);return {code,number:n,name:readTitle(code,p),portfolioWave:Math.ceil(n/50),implementationMode:physical?'bespoke_plus_enterprise_runtime':'governed_enterprise_runtime',physicalModule:p.backendExists,physicalPage:p.frontendExists,artifacts,surfaces:STANDARD.surfaces,middleware:STANDARD.middleware,erpControls:STANDARD.erpControls,uxStandards:STANDARD.ux,aiCapabilities:STANDARD.ai,workflow:STANDARD.workflow,kpis:STANDARD.kpis,decisionPolicy:{authoritativeData:physical?'existing module service/database':'enterprise runtime records until domain promotion',aiRole:'advisory_decision_support',humanApprovalRequired:true,makerChecker:true,evidenceRequiredForHighRisk:true},certification:STANDARD.certification,promotionRule:'Universal runtime may operate missing modules, but production certification requires domain identity, authoritative business rules, tests and evidence.'};}
function portfolio(start=MIN,end=MAX){const a=Math.max(MIN,Number(start)||MIN),b=Math.min(MAX,Number(end)||MAX);return Array.from({length:b-a+1},(_,i)=>definition(`M${String(a+i).padStart(3,'0')}`));}
async function overview(input){const d=definition(input),code=d.code;const [tasks,flows,decisions,kpis]=await Promise.all([
 pool.query(`SELECT status,priority,COUNT(*)::int count FROM enterprise_module_tasks WHERE module_id=$1 GROUP BY status,priority`,[code]),
 pool.query(`SELECT state,COUNT(*)::int count FROM enterprise_module_workflows WHERE module_id=$1 GROUP BY state`,[code]),
 pool.query(`SELECT status,risk_level,COUNT(*)::int count FROM enterprise_module_decisions WHERE module_id=$1 GROUP BY status,risk_level`,[code]),
 pool.query(`SELECT DISTINCT ON(metric_key) metric_key,metric_value,unit,source_reference,measured_at FROM enterprise_module_kpi_snapshots WHERE module_id=$1 ORDER BY metric_key,measured_at DESC`,[code])
]);const by=Object.fromEntries(kpis.rows.map(x=>[x.metric_key,x]));return {definition:d,tasks:tasks.rows,workflows:flows.rows,decisions:decisions.rows,kpis:d.kpis.map(k=>by[k]||{metric_key:k,metric_value:null,status:'awaiting_authoritative_data'})};}
async function createTask(input,data,actor={}){const code=normalize(input);if(!data.title)throw Object.assign(new Error('title is required'),{statusCode:400});const id=crypto.randomUUID();const q=await pool.query(`INSERT INTO enterprise_module_tasks(id,module_id,entity_type,entity_id,title,description,status,priority,assigned_role,assigned_user,due_at,payload,created_by) VALUES($1,$2,$3,$4,$5,$6,'open',$7,$8,$9,$10,$11,$12) RETURNING *`,[id,code,data.entity_type||null,data.entity_id||null,data.title,data.description||null,data.priority||'normal',data.assigned_role||null,data.assigned_user||null,data.due_at||null,data.payload||{},actor.id||null]);return q.rows[0];}
async function createWorkflow(input,data,actor={}){const d=definition(input);if(!data.entity_type||!data.entity_id)throw Object.assign(new Error('entity_type and entity_id are required'),{statusCode:400});const id=crypto.randomUUID();const q=await pool.query(`INSERT INTO enterprise_module_workflows(id,module_id,entity_type,entity_id,state,priority,assigned_role,assigned_user,sla_due_at,context,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[id,d.code,data.entity_type,data.entity_id,d.workflow[0],data.priority||'normal',data.assigned_role||null,data.assigned_user||null,data.sla_due_at||null,data.context||{},actor.id||null]);return q.rows[0];}
function assertTransition(input,from,to){const d=definition(input),a=d.workflow.indexOf(from),b=d.workflow.indexOf(to);if(a<0||b!==a+1)throw Object.assign(new Error(`Invalid workflow transition ${from} -> ${to}`),{statusCode:409});return true;}
async function transition(input,id,to,{actorId,actorRole,reason,evidence,correlationId}={}){const code=normalize(input),client=await pool.connect();try{await client.query('BEGIN');const cur=(await client.query('SELECT * FROM enterprise_module_workflows WHERE id=$1 AND module_id=$2 FOR UPDATE',[id,code])).rows[0];if(!cur)throw Object.assign(new Error('Workflow not found'),{statusCode:404});assertTransition(code,cur.state,to);await client.query('UPDATE enterprise_module_workflows SET state=$1,updated_at=NOW() WHERE id=$2',[to,id]);await client.query(`INSERT INTO enterprise_module_workflow_history(id,workflow_id,from_state,to_state,actor_id,actor_role,reason,evidence,correlation_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[crypto.randomUUID(),id,cur.state,to,actorId||null,actorRole||null,reason||null,evidence||{},correlationId||null]);await client.query('COMMIT');return {...cur,state:to};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
async function queueDecision(input,data,actor={}){const code=normalize(input);if(!data.decision_type)throw Object.assign(new Error('decision_type is required'),{statusCode:400});const id=crypto.randomUUID();const q=await pool.query(`INSERT INTO enterprise_module_decisions(id,module_id,workflow_id,decision_type,proposed_action,recommendation,evidence,risk_level,maker_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[id,code,data.workflow_id||null,data.decision_type,data.proposed_action||{},data.recommendation||null,data.evidence||{},data.risk_level||'normal',actor.id||null]);return q.rows[0];}
async function resolveDecision(input,id,data,actor={}){const code=normalize(input),allowed=['approved','rejected','modified','deferred'];if(!allowed.includes(data.decision))throw Object.assign(new Error('Invalid decision'),{statusCode:400});const cur=(await pool.query('SELECT * FROM enterprise_module_decisions WHERE id=$1 AND module_id=$2',[id,code])).rows[0];if(!cur)throw Object.assign(new Error('Decision not found'),{statusCode:404});if(cur.maker_id&&actor.id&&cur.maker_id===actor.id)throw Object.assign(new Error('Maker cannot check own consequential decision'),{statusCode:409});if(['high','critical'].includes(cur.risk_level)&&(!data.reason||Object.keys(cur.evidence||{}).length===0))throw Object.assign(new Error('High-risk decision requires evidence and reason'),{statusCode:422});const q=await pool.query(`UPDATE enterprise_module_decisions SET status=$1,checker_id=$2,decision_reason=$3,proposed_action=CASE WHEN $1='modified' THEN $4 ELSE proposed_action END,decided_at=NOW() WHERE id=$5 RETURNING *`,[data.decision,actor.id||null,data.reason||null,data.modified_action||{},id]);return q.rows[0];}
async function recordKpi(input,data,actor={}){const d=definition(input);if(!d.kpis.includes(data.metric_key))throw Object.assign(new Error('Unsupported KPI'),{statusCode:400});if(typeof data.metric_value!=='number'||!data.source_reference)throw Object.assign(new Error('metric_value and source_reference are required'),{statusCode:400});const id=crypto.randomUUID();const q=await pool.query(`INSERT INTO enterprise_module_kpi_snapshots(id,module_id,metric_key,metric_value,unit,dimensions,source_reference,measured_at,recorded_by) VALUES($1,$2,$3,$4,$5,$6,$7,COALESCE($8,NOW()),$9) RETURNING *`,[id,d.code,data.metric_key,data.metric_value,data.unit||null,data.dimensions||{},data.source_reference,data.measured_at||null,actor.id||null]);return q.rows[0];}
module.exports={MIN,MAX,STANDARD,normalize,definition,portfolio,overview,createTask,createWorkflow,assertTransition,transition,queueDecision,resolveDecision,recordKpi};
