'use strict';
const fs=require('fs');
const path=require('path');
const runtime=require('./enterpriseModule550RuntimeService');
const ROOT=path.resolve(__dirname,'..','..','..');
const MIN=1,MAX=541;
const FAMILY_RULES=[
 ['platform_identity',/(platform|config|tenant|organization|environment|feature|localization|timezone|user|auth|role|permission|identity|consent|session)/i],
 ['farmer_community',/(farmer|family|village|panchayat|district|state|shg|cooperative|producer|community|rural)/i],
 ['land_gis',/(land|parcel|gis|soil|water|boundary|survey|geo)/i],
 ['crop_production',/(crop|seed|fertili|horticulture|irrigation|farm|agron|mushroom|sericulture|vermicompost)/i],
 ['livestock_biology',/(dairy|poultry|goat|sheep|pig|livestock|animal|veterinary|fisheries|aquaculture|beekeep|apiculture)/i],
 ['supply_chain_assets',/(warehouse|storage|cold|logistic|transport|inventory|procurement|supply|trace|asset|maintenance)/i],
 ['commerce_market',/(market|buyer|seller|commerce|order|price|sales|trade|product|catalog)/i],
 ['finance_risk',/(finance|loan|credit|insurance|payment|ledger|account|bank|risk|wallet|escrow|settlement)/i],
 ['quality_compliance_lab',/(quality|certif|compliance|laboratory|food safety|audit|testing|inspection)/i],
 ['climate_sustainability',/(climate|carbon|biodiversity|energy|sustain|forest|environment)/i],
 ['enterprise_operations',/(erp|project|hr|workforce|operation|engineering|governance|legal|crm|workflow)/i]
];
const FAMILY={
 platform_identity:{pages:['command_center','master_data','requests','workflow','decisions','security','analytics','audit'],kpis:['availability','coverage','quality','backlog','exceptions','outcome'],visualizations:['dependency_graph','risk_heatmap','lifecycle_funnel','trend'],roles:['admin','security_admin','business_owner','checker','auditor'],integrations:['identity','configuration','audit','notifications','analytics']},
 farmer_community:{pages:['entity_360','relationships','services','workflow','decisions','outcomes','map','audit'],kpis:['coverage','completeness','service_readiness','backlog','outcomes','exceptions'],visualizations:['360_scorecard','journey','geography','cohort_trend'],roles:['farmer','village_operator','fpo_manager','field_officer','checker','auditor'],integrations:['village','fpo','land','schemes','marketplace','finance']},
 land_gis:{pages:['record_360','map','evidence','conflicts','workflow','decisions','analytics','audit'],kpis:['coverage','verified_records','data_quality','conflicts','resource_risk','outcome'],visualizations:['interactive_map','layer_stack','timeline','risk_heatmap'],roles:['farmer','gis_officer','land_officer','village_operator','checker','auditor'],integrations:['gis','farmer','village','soil','water','documents']},
 crop_production:{pages:['production_360','plan','inputs','field_operations','workflow','decisions','yield_quality','audit'],kpis:['coverage','plan_adherence','input_efficiency','yield','quality','outcome'],visualizations:['crop_calendar','field_map','yield_trend','input_efficiency'],roles:['farmer','agronomist','extension_worker','fpo_manager','checker','auditor'],integrations:['farmer','plot','soil','water','weather','inventory','marketplace']},
 livestock_biology:{pages:['population_360','health','production','inputs','workflow','decisions','economics','audit'],kpis:['coverage','health_status','production','mortality_exceptions','cost_efficiency','outcome'],visualizations:['population_trend','health_heatmap','production_trend','cost_waterfall'],roles:['farmer','veterinarian','field_officer','fpo_manager','checker','auditor'],integrations:['farmer','village','laboratory','inventory','marketplace','finance']},
 supply_chain_assets:{pages:['network_360','inventory_assets','movement','exceptions','workflow','decisions','performance','audit'],kpis:['throughput','inventory_accuracy','sla_compliance','loss_damage','cost_efficiency','outcome'],visualizations:['network_map','inventory_ageing','sla_trend','exception_heatmap'],roles:['operator','warehouse_manager','logistics_manager','fpo_manager','checker','auditor'],integrations:['production','warehouse','marketplace','buyer','transport','settlement']},
 commerce_market:{pages:['commercial_360','catalogue_parties','orders','pricing','workflow','decisions','performance','audit'],kpis:['gmv','order_fill_rate','price_realization','conversion','exceptions','outcome'],visualizations:['demand_supply','price_trend','order_funnel','buyer_seller_network'],roles:['seller','buyer','market_manager','fpo_manager','checker','auditor'],integrations:['inventory','warehouse','buyer','logistics','payment','settlement']},
 finance_risk:{pages:['financial_360','accounts_exposure','transactions','risk','workflow','decisions','performance','audit'],kpis:['exposure','settlement_or_collection','risk_exceptions','turnaround','margin_or_cost','outcome'],visualizations:['cashflow_trend','risk_heatmap','ageing','decision_funnel'],roles:['finance_user','risk_officer','approver','checker','auditor'],integrations:['orders','payments','ledger','insurance','banking','audit']},
 quality_compliance_lab:{pages:['quality_360','standards','samples_evidence','nonconformance','workflow','decisions','certificates','audit'],kpis:['coverage','pass_rate','nonconformance','turnaround','expiry_risk','outcome'],visualizations:['quality_trend','nonconformance_heatmap','certificate_expiry','sample_flow'],roles:['quality_officer','lab_user','compliance_officer','checker','auditor'],integrations:['production','batch','laboratory','warehouse','marketplace','traceability']},
 climate_sustainability:{pages:['sustainability_360','resources','monitoring','interventions','workflow','decisions','outcomes','audit'],kpis:['coverage','resource_efficiency','impact','intervention_progress','risk','outcome'],visualizations:['impact_trend','resource_map','risk_scenarios','intervention_portfolio'],roles:['sustainability_officer','field_officer','farmer','planner','checker','auditor'],integrations:['farm','village','gis','weather','production','reporting']},
 enterprise_operations:{pages:['operations_360','master_data','transactions','exceptions','workflow','decisions','performance','audit'],kpis:['coverage','quality','backlog','sla_compliance','exceptions','outcome'],visualizations:['process_funnel','sla_trend','exception_heatmap','performance_scorecard'],roles:['operator','manager','approver','checker','auditor'],integrations:['master_data','notifications','documents','finance','analytics','audit']}
};
function normalize(input){const code=runtime.normalize(input),n=Number(code.slice(1));if(n<MIN||n>MAX)throw Object.assign(new Error('Module outside M001-M541 enterprise promotion range'),{statusCode:404});return code;}
function readFile(code,name){const p=path.join(ROOT,'backend','src','modules',code,name);if(!fs.existsSync(p))return {exists:false,size:0,placeholder:false};const raw=fs.readFileSync(p,'utf8');return {exists:true,size:Buffer.byteLength(raw),placeholder:/TODO|FIXME|not implemented|placeholder|stub|skeleton/i.test(raw)};}
function maturity(code){const files=Object.fromEntries(['service.js','controller.js','routes.js','model.sql','index.js'].map(n=>[n,readFile(code,n)]));const page=path.join(ROOT,'frontend','src','modules',code,`${code}Page.jsx`);files.page={exists:fs.existsSync(page),size:fs.existsSync(page)?fs.statSync(page).size:0,placeholder:false};const missing=Object.entries(files).filter(([,v])=>!v.exists).map(([k])=>k);const placeholders=Object.entries(files).filter(([,v])=>v.placeholder).map(([k])=>k);const substantive=['service.js','controller.js','model.sql','page'].filter(k=>(files[k]?.size||0)>=500);const bytes=['service.js','controller.js','routes.js','model.sql','page'].reduce((n,k)=>n+(files[k]?.size||0),0);let score=Math.round(((6-missing.length)/6*30)+(substantive.length/4*60)-(placeholders.length*10));if(bytes<2000)score=Math.min(score,30);score=Math.max(0,Math.min(100,score));return {score,state:score>=80?'advanced':score>=60?'operational':score>=35?'partial':'promotion_required',coreBytes:bytes,files,missing,placeholders,substantive};}
function family(name){return FAMILY_RULES.find(([,re])=>re.test(name||''))?.[0]||'enterprise_operations';}
function interoperability(f){if(f==='livestock_biology')return {applicable:true,scope:['species_breed_taxonomy','animal_disease_terminology','sample_specimen','laboratory_result_semantics'],humanClinical:false};if(f==='quality_compliance_lab')return {applicable:true,scope:['sample_specimen','chain_of_custody','test_method','instrument','analyte','result_unit','threshold','certificate'],humanClinical:false};if(f==='crop_production'||f==='climate_sustainability')return {applicable:true,scope:['species_crop_variety_taxonomy','pest_pathogen_taxonomy','soil_biology','biodiversity_taxonomy'],humanClinical:false};return {applicable:false,scope:[],humanClinical:false};}
function profile(input){const code=normalize(input),base=runtime.definition(code),m=maturity(code),f=family(base.name),d=FAMILY[f];return {...base,enterprisePromotionRange:'M001-M541',domainFamily:f,maturity:m,pages:d.pages,kpis:d.kpis,visualizations:d.visualizations,roles:d.roles,integrations:d.integrations,workflow:['capture','validate','enrich','risk_assess','review','approve','execute','verify','measure'],middleware:[...new Set([...base.middleware,'field_level_authorization','purpose_and_consent_where_applicable','anti_replay_for_sensitive_mutations'])],erpControls:[...new Set([...base.erpControls,'master_data_linkage','document_evidence','exception_management','financial_traceability','cross_module_reconciliation','period_close_or_finalization_where_applicable'])],uxStandards:[...new Set([...base.uxStandards,'role_based_home','guided_tasks','data_density_modes','visual_explanations','drilldown','export_with_context','mobile_field_mode','printable_evidence_view'])],decisionControls:['maker_checker','reason_required','evidence_required_for_high_risk','human_approval_for_consequential_action','override_logged','sla_escalation','segregation_of_duties'],ai:{capabilities:base.aiCapabilities,authoritative:false,requirements:['grounded_data','evidence_and_confidence','insufficient_data_response','human_override','model_or_prompt_version','tool_call_audit','drift_or_quality_monitoring']},digitalTwin:{enabled:true,scope:`${f}_entity_process_and_outcome_twin`,status:m.state==='advanced'?'integrated':'available_via_enterprise_runtime'},knowledgeGraph:{enabled:true,relationships:['entity_to_actor','entity_to_geography','entity_to_transaction','entity_to_evidence','entity_to_policy','entity_to_outcome']},interoperability:interoperability(f),promotionGaps:[...m.missing.map(x=>`missing:${x}`),...m.placeholders.map(x=>`placeholder:${x}`),...(m.state==='promotion_required'?['domain_implementation_depth_below_standard']:[])],certification:['authoritative_domain_identity','service_and_database_depth','api_contract','middleware_enforced','operational_page','workflow_real_path','authorization_negative_tests','maker_checker','segregation_of_duties','kpi_provenance','accessibility','observability','integration_contracts','ai_governance','interoperability_where_applicable','e2e']};}
function portfolio(start=MIN,end=MAX){const a=Math.max(MIN,Number(start)||MIN),b=Math.min(MAX,Number(end)||MAX);return Array.from({length:b-a+1},(_,i)=>profile(`M${String(a+i).padStart(3,'0')}`));}
function summary(){const all=portfolio();return {range:'M001-M541',total:all.length,advanced:all.filter(x=>x.maturity.state==='advanced').length,operational:all.filter(x=>x.maturity.state==='operational').length,partial:all.filter(x=>x.maturity.state==='partial').length,promotionRequired:all.filter(x=>x.maturity.state==='promotion_required').length,modules:all};}
module.exports={MIN,MAX,FAMILY,normalize,maturity,family,interoperability,profile,portfolio,summary};
