'use strict';
const crypto=require('crypto');
const pool=require('../database/pool');
const assurance=require('./moduleProductionAssuranceService');
const operational=require('./m001m050OperationalExperienceService');
const ai=require('./m001m050HighestStandardEnhancementService');

const FOCUS={
M001:['platform deployment','runtime health','capacity','release governance'],M002:['configuration catalogue','change impact','drift','environment overrides'],M003:['tenant lifecycle','subscription','isolation','tenant economics'],M004:['organization hierarchy','business units','delegation','inter-company relationships'],M005:['environment promotion','release readiness','configuration parity','rollback'],M006:['administrative operations','privileged actions','job control','system exceptions'],M007:['feature lifecycle','rollout cohorts','experimentation','kill switches'],M008:['language resources','translation quality','regional content','terminology'],M009:['timezone policy','local calendars','cutoffs','scheduled operations'],M010:['enterprise master settings','policy parameters','configuration ownership','dependency impact'],
M011:['user lifecycle','profile status','access recertification','account risk'],M012:['authentication','credential risk','login assurance','adaptive controls'],M013:['authorization','resource policy','least privilege','segregation of duties'],M014:['role catalogue','permission bundles','toxic combinations','role review'],M015:['permission catalogue','entitlements','resource actions','recertification'],M016:['SSO providers','federation','claims mapping','identity trust'],M017:['MFA enrollment','factor assurance','recovery','step-up authentication'],M018:['digital identity','identity proofing','assurance','identity graph'],M019:['consent lifecycle','purpose limitation','revocation','data-use evidence'],M020:['session lifecycle','device context','risk','revocation'],
M021:['farmer registration','duplicate resolution','village/FPO linkage','onboarding'],M022:['farmer 360','household economics','land/service links','profile completeness'],M023:['family/household','dependants','labour capacity','livelihoods'],M024:['KYC documents','verification','expiry','evidence'],M025:['farmer verification','field checks','exceptions','approval'],M026:['skills graph','competency gaps','training pathways','service matching'],M027:['certifications','validity','scope','market eligibility'],M028:['advisory cases','recommendations','follow-up','outcome'],M029:['welfare assessment','consent','support/referral','non-diagnostic safeguards'],M030:['farmer performance','benchmarking','productivity','improvement plan'],
M031:['land registry','parcel identity','farmer linkage','provenance'],M032:['ownership history','title evidence','conflicts','temporal validity'],M033:['lease lifecycle','lessor/lessee','terms','expiry'],M034:['parcel geometry','boundary quality','overlap','map validation'],M035:['GIS layers','spatial joins','thematic maps','geospatial analytics'],M036:['soil samples','soil biology','nutrient layers','recommendations'],M037:['water resources','availability','quality','allocation'],M038:['administrative boundaries','topology','hierarchy','coverage'],M039:['survey planning','field capture','quality','evidence'],M040:['digital land records','source reconciliation','versioning','document provenance'],
M041:['village master','district/block hierarchy','FPO/farmer linkage','village 360'],M042:['panchayat governance','village coverage','plans','decisions'],M043:['block hierarchy','village roll-up','programmes','performance'],M044:['district hierarchy','block roll-up','portfolio','resource allocation'],M045:['state hierarchy','district roll-up','policy','strategic outcomes'],M046:['SHG membership','meetings','savings/enterprise linkage','performance'],M047:['cooperative membership','governance','shares/services','compliance'],M048:['producer groups','membership','aggregation','market readiness'],M049:['community assets','condition','utilization','maintenance'],M050:['rural initiatives','planning','funding','execution/outcomes']};

const FAMILY={platform:{range:[1,10],pages:['command_center','master_data','changes','operations','exceptions','audit'],workflow:['draft','impact_assessment','review','approve','execute','verify','close'],kpis:['availability','backlog','change_success','exceptions','sla_compliance'],visuals:['status_timeline','dependency_graph','risk_matrix','capacity_trend'],roles:['platform_admin','sre','security_admin','business_owner','auditor'],integrations:['telemetry','configuration_registry','audit','notifications']},identity:{range:[11,20],pages:['identity_360','requests','verification','risk','decisions','audit'],workflow:['request','validate','risk_assess','review','approve','activate','monitor','close'],kpis:['active_records','verification_backlog','high_risk','approval_tat','exceptions'],visuals:['lifecycle_funnel','risk_heatmap','relationship_graph','tat_trend'],roles:['identity_admin','security_admin','maker','checker','privacy_officer','auditor'],integrations:['authentication','authorization','consent','audit','notifications']},farmer:{range:[21,30],pages:['farmer_360','relationships','operations','services','decisions','outcomes','audit'],workflow:['capture','validate','enrich','review','approve','serve','monitor','measure'],kpis:['coverage','completeness','pending_reviews','service_readiness','outcomes'],visuals:['farmer_360','journey','geography','performance_trend','cohort_comparison'],roles:['farmer','village_operator','fpo_manager','extension_worker','maker','checker','auditor'],integrations:['village','fpo','land','schemes','marketplace','finance','notifications']},land:{range:[31,40],pages:['record_360','map','evidence','conflicts','workflow','decisions','analytics'],workflow:['capture','georeference','validate','reconcile','review','approve','publish','monitor'],kpis:['coverage','verified_records','conflicts','data_quality','resource_risk'],visuals:['interactive_map','timeline','layer_stack','conflict_heatmap','quality_trend'],roles:['farmer','gis_officer','land_officer','village_operator','maker','checker','auditor'],integrations:['gis','farmer','village','soil','water','documents','audit']},community:{range:[41,50],pages:['territory_360','institutions','assets','programmes','workflow','decisions','outcomes','audit'],workflow:['identify','prioritize','plan','resource','review','approve','execute','verify','measure'],kpis:['coverage','open_gaps','programme_progress','asset_utilization','outcomes'],visuals:['territory_scorecard','hierarchy_map','network_graph','asset_map','programme_portfolio','outcome_trend'],roles:['village_operator','panchayat_user','fpo_manager','block_officer','district_officer','state_officer','maker','checker','auditor'],integrations:['farmer','fpo','land','assets','finance','marketplace','logistics','government_schemes']}};
function code(n){return `M${String(n).padStart(3,'0')}`;}
function familyFor(moduleCode){const n=Number(moduleCode.slice(1));return Object.entries(FAMILY).find(([,v])=>n>=v.range[0]&&n<=v.range[1])?.[0];}
function spec(moduleCode){const c=moduleCode.toUpperCase();const contract=assurance.CONTRACTS[c];if(!contract||!FOCUS[c]){const e=new Error(`Unknown M001-M050 module ${c}`);e.statusCode=404;throw e;}const fam=familyFor(c),f=FAMILY[fam],op=operational.profile(c),a=ai.profile(c);return {code:c,name:contract.name,domain:contract.domain,family:fam,focus:FOCUS[c],pages:f.pages,workflow:f.workflow,kpis:f.kpis,visualizations:f.visuals,roles:f.roles,integrations:f.integrations,requiredFields:contract.required||[],erpControls:op.erpControls,uxStandards:[...new Set([...op.uxStandards,'search_filter_sort','saved_views','bulk_actions_with_guardrails','export_with_permissions','activity_timeline','responsive_data_tables','map_or_chart_where_domain_relevant'])],middleware:['authn','rbac_abac','tenant_scope','geography_scope','record_scope','validation','idempotency_for_mutations','correlation','rate_limit','audit','error_standardization'],decisionControls:['maker_checker','reason_required','evidence_required_for_high_risk','sla_escalation','human_approval_for_consequential_action'],ai:{capabilities:a.aiCapabilities,role:'decision_support_and_productivity',authoritative:false,evidenceFirst:true},digitalTwin:a.digitalTwin,knowledgeGraph:a.knowledgeGraph,interoperability:a.interoperability||[],certification:['domain_service_loads','database_contract','api_contract','middleware_enforced','page_renders','workflow_real_path','authorization_negative_tests','decision_control_tests','kpi_source_provenance','accessibility','observability','ai_evaluation','e2e']};}
function portfolio(){return Array.from({length:50},(_,i)=>spec(code(i+1)));}
async function taskSummary(moduleCode){spec(moduleCode);const q=await pool.query(`SELECT status,priority,COUNT(*)::int count FROM m001_m050_operational_tasks WHERE module_id=$1 GROUP BY status,priority ORDER BY status,priority`,[moduleCode.toUpperCase()]);return q.rows;}
async function createTask(moduleCode,data,actor={}){spec(moduleCode);if(!data.title){const e=new Error('title is required');e.statusCode=400;throw e;}const id=crypto.randomUUID();const q=await pool.query(`INSERT INTO m001_m050_operational_tasks(id,module_id,entity_type,entity_id,title,description,status,priority,assigned_role,assigned_user,due_at,payload,created_by) VALUES($1,$2,$3,$4,$5,$6,'open',$7,$8,$9,$10,$11,$12) RETURNING *`,[id,moduleCode.toUpperCase(),data.entity_type||null,data.entity_id||null,data.title,data.description||null,data.priority||'normal',data.assigned_role||null,data.assigned_user||null,data.due_at||null,data.payload||{},actor.id||null]);return q.rows[0];}
async function updateTask(moduleCode,id,data,actor={}){spec(moduleCode);const allowed=['open','in_progress','blocked','completed','cancelled'];if(data.status&&!allowed.includes(data.status)){const e=new Error('Invalid task status');e.statusCode=400;throw e;}const q=await pool.query(`UPDATE m001_m050_operational_tasks SET status=COALESCE($1,status),priority=COALESCE($2,priority),assigned_role=COALESCE($3,assigned_role),assigned_user=COALESCE($4,assigned_user),due_at=COALESCE($5,due_at),payload=payload||$6::jsonb,completed_at=CASE WHEN $1='completed' THEN NOW() ELSE completed_at END,updated_at=NOW(),updated_by=$7 WHERE id=$8 AND module_id=$9 RETURNING *`,[data.status||null,data.priority||null,data.assigned_role||null,data.assigned_user||null,data.due_at||null,JSON.stringify(data.payload||{}),actor.id||null,id,moduleCode.toUpperCase()]);if(!q.rows[0]){const e=new Error('Task not found');e.statusCode=404;throw e;}return q.rows[0];}
async function recordKpi(moduleCode,data,actor={}){const s=spec(moduleCode);if(!s.kpis.includes(data.metric_key)){const e=new Error(`Unsupported KPI ${data.metric_key}`);e.statusCode=400;throw e;}if(typeof data.metric_value!=='number'){const e=new Error('metric_value must be numeric');e.statusCode=400;throw e;}const id=crypto.randomUUID();const q=await pool.query(`INSERT INTO m001_m050_kpi_snapshots(id,module_id,metric_key,metric_value,unit,dimensions,source_reference,measured_at,recorded_by) VALUES($1,$2,$3,$4,$5,$6,$7,COALESCE($8,NOW()),$9) RETURNING *`,[id,moduleCode.toUpperCase(),data.metric_key,data.metric_value,data.unit||null,data.dimensions||{},data.source_reference,data.measured_at||null,actor.id||null]);return q.rows[0];}
async function latestKpis(moduleCode){const s=spec(moduleCode);const q=await pool.query(`SELECT DISTINCT ON(metric_key) metric_key,metric_value,unit,dimensions,source_reference,measured_at FROM m001_m050_kpi_snapshots WHERE module_id=$1 ORDER BY metric_key,measured_at DESC`,[moduleCode.toUpperCase()]);const by=Object.fromEntries(q.rows.map(x=>[x.metric_key,x]));return s.kpis.map(k=>by[k]||{metric_key:k,metric_value:null,source_reference:null,status:'awaiting_authoritative_data'});}
module.exports={FOCUS,FAMILY,spec,portfolio,taskSummary,createTask,updateTask,recordKpi,latestKpis};