'use strict';
const crypto=require('crypto');
const pool=require('../database/pool');
const experience=require('./m001m050OperationalExperienceService');
function definition(moduleCode){return experience.profile(moduleCode.toUpperCase());}
function assertTransition(moduleCode,from,to){const flow=definition(moduleCode).workflow;const a=flow.indexOf(from),b=flow.indexOf(to);if(b<0||a<0||b!==a+1){const e=new Error(`Invalid ${moduleCode} workflow transition ${from} -> ${to}`);e.statusCode=409;throw e;}return true;}
async function create(moduleCode,data,actor={}){const d=definition(moduleCode);const state=d.workflow[0];const id=crypto.randomUUID();const q=await pool.query(`INSERT INTO m001_m050_workflow_instances(id,module_id,entity_type,entity_id,state,priority,assigned_role,assigned_user,sla_due_at,context,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[id,moduleCode.toUpperCase(),data.entity_type,data.entity_id,state,data.priority||'normal',data.assigned_role||null,data.assigned_user||null,data.sla_due_at||null,data.context||{},actor.id||null]);return q.rows[0];}
async function summary(moduleCode){const code=moduleCode.toUpperCase();definition(code);const [states,decisions]=await Promise.all([pool.query(`SELECT state,COUNT(*)::int count FROM m001_m050_workflow_instances WHERE module_id=$1 GROUP BY state`,[code]),pool.query(`SELECT status,COUNT(*)::int count FROM m001_m050_decision_queue WHERE module_id=$1 GROUP BY status`,[code])]);return {moduleCode:code,states:states.rows,decisions:decisions.rows};}
async function transition(moduleCode,workflowId,toState,{actorId,actorRole,reason,evidence,correlationId}={}){const client=await pool.connect();try{await client.query('BEGIN');const current=(await client.query('SELECT * FROM m001_m050_workflow_instances WHERE id=$1 AND module_id=$2 FOR UPDATE',[workflowId,moduleCode.toUpperCase()])).rows[0];if(!current){const e=new Error('Workflow not found');e.statusCode=404;throw e;}assertTransition(moduleCode,current.state,toState);await client.query('UPDATE m001_m050_workflow_instances SET state=$1,updated_at=NOW() WHERE id=$2',[toState,workflowId]);await client.query(`INSERT INTO m001_m050_workflow_transitions(id,workflow_id,from_state,to_state,actor_id,actor_role,reason,evidence,correlation_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[crypto.randomUUID(),workflowId,current.state,toState,actorId||null,actorRole||null,reason||null,evidence||{},correlationId||null]);await client.query('COMMIT');return {...current,state:toState};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
async function queueDecision(moduleCode,data,actor={}){definition(moduleCode);const id=crypto.randomUUID();const q=await pool.query(`INSERT INTO m001_m050_decision_queue(id,module_id,workflow_id,decision_type,proposed_action,recommendation,risk_level,maker_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[id,moduleCode.toUpperCase(),data.workflow_id||null,data.decision_type,data.proposed_action||{},data.recommendation||null,data.risk_level||'normal',actor.id||null]);return q.rows[0];}
async function decide(moduleCode,id,{decision,checkerId,reason,modifiedAction}={}){if(!['approved','rejected','modified','deferred'].includes(decision)){const e=new Error('Invalid decision');e.statusCode=400;throw e;}const current=(await pool.query('SELECT * FROM m001_m050_decision_queue WHERE id=$1 AND module_id=$2',[id,moduleCode.toUpperCase()])).rows[0];if(!current){const e=new Error('Decision not found');e.statusCode=404;throw e;}if(current.maker_id&&checkerId&&current.maker_id===checkerId){const e=new Error('Maker cannot approve/check own consequential decision');e.statusCode=409;throw e;}const proposed=decision==='modified'&&modifiedAction?modifiedAction:current.proposed_action;const q=await pool.query(`UPDATE m001_m050_decision_queue SET status=$1,checker_id=$2,decision_reason=$3,proposed_action=$4,decided_at=NOW() WHERE id=$5 RETURNING *`,[decision,checkerId||null,reason||null,proposed,id]);return q.rows[0];}
module.exports={definition,assertTransition,create,summary,transition,queueDecision,decide};
