'use strict';
const fs=require('fs');
const path=require('path');
const runtime=require('./enterpriseModule550RuntimeService');
const ROOT=path.resolve(__dirname,'..','..','..');
const MIN=51,MAX=150;
const DOMAIN_PATTERNS=[
 ['livestock',/(dairy|poultry|goat|sheep|pig|livestock|animal|veterinary)/i],
 ['crop_production',/(crop|seed|fertili|horticulture|irrigation|soil|water|farm|agron)/i],
 ['fpo_cooperative',/(fpo|producer|cooperative|collective|shg|aggregation)/i],
 ['supply_chain',/(warehouse|storage|cold|logistic|transport|inventory|procurement|supply|trace)/i],
 ['commerce_market',/(market|buyer|seller|commerce|order|price|sales|trade)/i],
 ['finance_risk',/(finance|loan|credit|insurance|payment|ledger|account|risk)/i],
 ['quality_compliance',/(quality|certif|compliance|laboratory|food safety|audit)/i],
 ['climate_sustainability',/(climate|carbon|biodiversity|energy|sustain|forestry)/i],
 ['enterprise_operations',/(erp|project|asset|hr|workforce|maintenance|operation)/i]
];
const FAMILY={
 livestock:{pages:['herd_flock_360','health','production','feed_inputs','workflow','decisions','economics','audit'],kpis:['coverage','health_status','production','mortality_exceptions','cost_efficiency','outcome'],visualizations:['population_trend','health_heatmap','production_trend','cost_waterfall'],roles:['farmer','veterinarian','field_officer','fpo_manager','checker','auditor'],integrations:['farmer','village','laboratory','inventory','marketplace','finance']},
 crop_production:{pages:['production_360','plan','inputs','field_operations','workflow','decisions','yield_quality','audit'],kpis:['coverage','plan_adherence','input_efficiency','yield','quality','outcome'],visualizations:['crop_calendar','field_map','yield_trend','input_efficiency'],roles:['farmer','agronomist','extension_worker','village_operator','fpo_manager','checker','auditor'],integrations:['farmer','plot','soil','water','weather','inventory','marketplace']},
 fpo_cooperative:{pages:['organization_360','members','governance','services','workflow','decisions','performance','audit'],kpis:['member_coverage','active_members','service_utilization','governance_compliance','business_volume','outcome'],visualizations:['member_network','service_funnel','business_trend','governance_scorecard'],roles:['fpo_manager','board_member','member','village_operator','checker','auditor'],integrations:['farmer','village','marketplace','finance','procurement','warehouse']},
 supply_chain:{pages:['network_360','inventory_assets','movement','exceptions','workflow','decisions','performance','audit'],kpis:['throughput','inventory_accuracy','sla_compliance','loss_damage','cost_efficiency','outcome'],visualizations:['network_map','inventory_ageing','sla_trend','exception_heatmap'],roles:['operator','warehouse_manager','logistics_manager','fpo_manager','checker','auditor'],integrations:['production','warehouse','marketplace','buyer','transport','settlement']},
 commerce_market:{pages:['commercial_360','catalogue_parties','orders','pricing','workflow','decisions','performance','audit'],kpis:['gmv','order_fill_rate','price_realization','conversion','exceptions','outcome'],visualizations:['demand_supply','price_trend','order_funnel','buyer_seller_network'],roles:['seller','buyer','market_manager','fpo_manager','checker','auditor'],integrations:['inventory','warehouse','buyer','logistics','payment','settlement']},
 finance_risk:{pages:['financial_360','accounts_exposure','transactions','risk','workflow','decisions','performance','audit'],kpis:['exposure','collection_or_settlement','risk_exceptions','turnaround','cost_or_margin','outcome'],visualizations:['cashflow_trend','risk_heatmap','ageing','decision_funnel'],roles:['finance_user','risk_officer','approver','fpo_manager','checker','auditor'],integrations:['farmer','orders','payments','ledger','insurance','banking']},
 quality_compliance:{pages:['quality_360','standards','samples_evidence','nonconformance','workflow','decisions','certificates','audit'],kpis:['coverage','pass_rate','nonconformance','turnaround','expiry_risk','outcome'],visualizations:['quality_trend','nonconformance_heatmap','certificate_expiry','sample_flow'],roles:['quality_officer','lab_user','compliance_officer','checker','auditor'],integrations:['production','batch','laboratory','warehouse','marketplace','traceability']},
 climate_sustainability:{pages:['sustainability_360','resources','monitoring','interventions','workflow','decisions','outcomes','audit'],kpis:['coverage','resource_efficiency','emissions_or_impact','intervention_progress','risk','outcome'],visualizations:['impact_trend','resource_map','risk_scenarios','intervention_portfolio'],roles:['sustainability_officer','field_officer','farmer','planner','checker','auditor'],integrations:['farm','village','gis','weather','production','reporting']},
 enterprise_operations:{pages:['operations_360','master_data','transactions','exceptions','workflow','decisions','performance','audit'],kpis:['coverage','quality','backlog','sla_compliance','exceptions','outcome'],visualizations:['process_funnel','sla_trend','exception_heatmap','performance_scorecard'],roles:['operator','manager','approver','checker','auditor'],integrations:['master_data','notifications','documents','finance','analytics','audit']}
};
function normalize(input){const code=runtime.normalize(input),n=Number(code.slice(1));if(n<MIN||n>MAX)throw Object.assign(new Error('Module outside M051-M150 promotion range'),{statusCode:404});return code;}
function fileInfo(code,name){const p=path.join(ROOT,'backend','src','modules',code,name);if(!fs.existsSync(p))return {exists:false,size:0,placeholder:false};const raw=fs.readFileSync(p,'utf8');return {exists:true,size:Buffer.byteLength(raw),placeholder:/TODO|FIXME|not implemented|placeholder|stub|skeleton/i.test(raw)};}
function familyFor(name){return DOMAIN_PATTERNS.find(([,re])=>re.test(name||''))?.[0]||'enterprise_operations';}
function maturity(code){const names=['service.js','controller.js','routes.js','model.sql','index.js'];const files=Object.fromEntries(names.map(n=>[n,fileInfo(code,n)]));const pagePath=path.join(ROOT,'frontend','src','modules',code,`${code}Page.jsx`);files.page={exists:fs.existsSync(pagePath),size:fs.existsSync(pagePath)?fs.statSync(pagePath).size:0,placeholder:false};const missing=Object.entries(files).filter(([,v])=>!v.exists).map(([k])=>k);const placeholders=Object.entries(files).filter(([,v])=>v.placeholder).map(([k])=>k);const substantive=['service.js','controller.js','model.sql','page'].filter(k=>(files[k]?.size||0)>=500);const coreBytes=['service.js','controller.js','routes.js','model.sql','page'].reduce((n,k)=>n+(files[k]?.size||0),0);let score=Math.round(((6-missing.length)/6*35)+(substantive.length/4*55)-(placeholders.length*10));if(coreBytes<2000)score=Math.min(score,30);const clamped=Math.max(0,Math.min(100,score));return {score:clamped,state:clamped>=80?'advanced':clamped>=60?'operational':clamped>=35?'partial':'promotion_required',coreBytes,files,missing,placeholders,substantive};}
function interoperability(family){if(family==='livestock')return {applicable:true,scope:['species_breed_taxonomy','animal_disease_terminology','specimen_sample_chain','laboratory_result_semantics'],medicalScope:'veterinary_and_biological_only_unless_separately_governed'};if(family==='quality_compliance')return {applicable:true,scope:['sample_specimen','test_method','instrument','analyte','result_unit','threshold','chain_of_custody','certificate'],medicalScope:'no_human_clinical_claims_without_separate_clinical_governance'};if(family==='crop_production'||family==='climate_sustainability')return {applicable:true,scope:['species_crop_variety_taxonomy','pest_pathogen_taxonomy','soil_biology','biodiversity_taxonomy'],medicalScope:'not_applicable'};return {applicable:false,scope:[],medicalScope:'not_applicable'};}
function profile(input){const code=normalize(input),base=runtime.definition(code),mat=maturity(code),family=familyFor(base.name),f=FAMILY[family];return {...base,promotionRange:'M051-M150',domainFamily:family,maturity:mat,pages:f.pages,kpis:f.kpis,visualizations:f.visualizations,roles:f.roles,integrations:f.integrations,workflow:['capture','validate','enrich','risk_assess','review','approve','execute','verify','measure'],decisionControls:['maker_checker','reason_required','evidence_required_for_high_risk','human_approval_for_consequential_action','override_logged','sla_escalation'],erpControls:[...new Set([...base.erpControls,'master_data_linkage','document_evidence','exception_management','financial_traceability','cross_module_reconciliation'])],uxStandards:[...new Set([...base.uxStandards,'role_based_home','guided_tasks','data_density_modes','visual_explanations','drilldown','export_with_context','mobile_field_mode'])],ai:{capabilities:base.aiCapabilities,authoritative:false,requirements:['grounded_data','evidence_and_confidence','insufficient_data_response','human_override','model_or_prompt_version','audit_trace']},digitalTwin:{enabled:true,scope:`${family}_entity_and_process_twin`,status:mat.state==='advanced'?'integrated':'available_via_enterprise_runtime'},knowledgeGraph:{enabled:true,relationships:['entity_to_actor','entity_to_geography','entity_to_transaction','entity_to_evidence','entity_to_outcome']},interoperability:interoperability(family),promotionGaps:[...mat.missing.map(x=>`missing:${x}`),...mat.placeholders.map(x=>`placeholder:${x}`),...(mat.state==='promotion_required'?['domain_implementation_depth_below_standard']:[])],certification:['authoritative_domain_identity','service_and_database_depth','api_and_middleware','operational_page','real_workflow','negative_authorization','maker_checker','kpi_provenance','accessibility','observability','integration_contracts','ai_governance','biological_interoperability_where_applicable','e2e']};}
function portfolio(){return Array.from({length:100},(_,i)=>profile(`M${String(MIN+i).padStart(3,'0')}`));}
function summary(){const all=portfolio();return {range:'M051-M150',total:all.length,advanced:all.filter(x=>x.maturity.state==='advanced').length,operational:all.filter(x=>x.maturity.state==='operational').length,partial:all.filter(x=>x.maturity.state==='partial').length,promotionRequired:all.filter(x=>x.maturity.state==='promotion_required').length,modules:all};}
module.exports={MIN,MAX,FAMILY,normalize,maturity,interoperability,profile,portfolio,summary};
