param(
    [string]$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path,
    [string]$OutputDirectory = '.ai\staging\claude-visual',
    [switch]$IncludeDocumentation
)

$ErrorActionPreference = 'Stop'
$root = (Resolve-Path $ProjectRoot).Path
$output = [System.IO.Path]::GetFullPath((Join-Path $root $OutputDirectory))
$excludedDirectories = @('node_modules', '.git', 'backups', 'dist', 'build', '.ai\staging')
$extensions = @('.html', '.jsx', '.tsx', '.js', '.ts', '.css', '.scss', '.svg')
if ($IncludeDocumentation) { $extensions += '.md' }
$scanRoots = @('frontend\src', '_EBDESIGN_LIBRARY\05_UI', '_EBDESIGN_LIBRARY\11_COMPONENTS')
$scanFiles = @('afrera_platform_v43.html', 'PROJECT_STATUS.html')

New-Item -ItemType Directory -Path $output -Force | Out-Null

function Get-RelativePath([string]$path) {
    return $path.Substring($root.Length + 1).Replace('\', '/')
}

function Get-ArtifactKind([string]$relativePath) {
    if ($relativePath -match '(?i)(visual|ui|component|page|layout|theme|style)') { return 'ui' }
    if ($relativePath -match '(?i)\.html$') { return 'prototype' }
    return 'code'
}

$files = @(
    foreach ($scanRoot in $scanRoots) {
        $scanPath = Join-Path $root $scanRoot
        if (Test-Path $scanPath) { Get-ChildItem -Path $scanPath -Recurse -File }
    }
    foreach ($scanFile in $scanFiles) {
        $scanPath = Join-Path $root $scanFile
        if (Test-Path $scanPath) { Get-Item -LiteralPath $scanPath }
    }
) | Where-Object {
    $relative = Get-RelativePath $_.FullName
    $segments = $relative -split '/'
    $_.Extension.ToLowerInvariant() -in $extensions -and
    -not ($segments | Where-Object { $_ -in ($excludedDirectories | ForEach-Object { $_ -split '\\' | Select-Object -Last 1 }) })
}

$artifacts = foreach ($file in $files) {
    $relative = Get-RelativePath $file.FullName
    $hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $file.FullName).Hash.ToLowerInvariant()
    [ordered]@{
        path = $relative
        kind = Get-ArtifactKind $relative
        extension = $file.Extension.ToLowerInvariant()
        bytes = $file.Length
        sha256 = $hash
        source_of_truth = $relative -like 'frontend/src/*'
        review_status = 'pending'
    }
}

$manifest = [ordered]@{
    schema = 'claude.visual-context.v1'
    generated_at_utc = (Get-Date).ToUniversalTime().ToString('o')
    project_root = $root
    compatibility = @('Claude Code', 'Claude API', 'local review')
    non_destructive = $true
    artifact_count = @($artifacts).Count
    artifacts = @($artifacts)
}

$manifest | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath (Join-Path $output 'manifest.json') -Encoding utf8

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# Claude Visual Context')
$lines.Add('')
$lines.Add('Generated by `Export-ClaudeVisualContext.ps1`. This packet references source files; it does not rewrite or move them.')
$lines.Add('')
$lines.Add("Artifact count: $(@($artifacts).Count)")
$lines.Add('')
$lines.Add('| Path | Kind | SHA-256 | Review |')
$lines.Add('| --- | --- | --- | --- |')
foreach ($artifact in $artifacts) {
    $lines.Add("| $($artifact.path) | $($artifact.kind) | $($artifact.sha256) | $($artifact.review_status) |")
}
$lines | Set-Content -LiteralPath (Join-Path $output 'CONTEXT.md') -Encoding utf8

Write-Output "Exported $(@($artifacts).Count) visual context artifacts to $output"