/** Auto-mounted by DynamicRouteLoader as /api/v1/nutritionCommerceIntelligence. */
const express = require('express');
const { authMiddleware } = require('../middleware/auth');
const { apiLimiter } = require('../middleware/rateLimiter');
const engine = require('../services/commerce/nutritionCommerceIntelligenceService');

const router = express.Router();
router.use(authMiddleware);
router.use(apiLimiter);

router.get('/health', (_req, res) => res.json({ success: true, data: {
  service: 'nutritionCommerceIntelligence',
  version: '1.1.0',
  capabilities: [
    'price-normalization',
    'nutrient-cost',
    'household-basket',
    'nutrition-density',
    'market-offer-normalization',
    'market-observation-quality',
    'internal-rural-metro-benchmark',
  ],
  clinical_boundary: 'No diagnosis or treatment decisions are generated by this service.',
} }));

router.post('/product-value', (req, res) => safe(res, () => engine.calculateProductValue(req.body)));
router.post('/basket', (req, res) => safe(res, () => engine.calculateBasket(req.body.items)));
router.post('/nutrition-density', (req, res) => safe(res, () => engine.calculateNutritionDensity(req.body)));
router.post('/market-offer/normalize', (req, res) => safe(res, () => engine.normalizeMarketOffer(req.body)));
router.post('/market-offer/quality', (req, res) => safe(res, () => engine.priceObservationQuality(req.body.observations, req.body.options)));
// This endpoint is for trusted internal pricing workers only; keep it out of customer/farmer APIs.
router.post('/internal/rural-metro-benchmark', (req, res) => safe(res, () => engine.benchmarkInternalValue(req.body)));

async function safe(res, fn) {
  try { return res.json({ success: true, data: await fn() }); }
  catch (error) { return res.status(400).json({ success: false, error: error.message }); }
}

module.exports = router;
