/**
 * Nutrition Commerce Intelligence API.
 * Auto-mounted by DynamicRouteLoader as /api/v1/nutritionCommerceIntelligence.
 */
const express = require('express');
const { authMiddleware } = require('../middleware/auth');
const { apiLimiter } = require('../middleware/rateLimiter');
const engine = require('../services/commerce/nutritionCommerceIntelligenceService');

const router = express.Router();
router.use(authMiddleware);
router.use(apiLimiter);

router.get('/health', async (_req, res) => res.json({ success: true, data: engineHealth() }));
router.post('/product-value', (req, res) => safe(res, () => engine.calculateProductValue(req.body)));
router.post('/basket', (req, res) => safe(res, () => engine.calculateBasket(req.body.items)));
router.post('/market-offer/normalize', (req, res) => safe(res, () => engine.normalizeMarketOffer(req.body)));

// Internal pricing endpoint. Never return this payload to customer/farmer APIs.
router.post('/internal/rural-metro-benchmark', (req, res) => safe(res, () => engine.benchmarkInternalValue(req.body)));

function engineHealth() {
  return {
    service: 'nutritionCommerceIntelligence',
    version: '1.0.0',
    capabilities: ['price-normalization', 'nutrient-cost', 'household-basket', 'market-offer-normalization', 'internal-rural-metro-benchmark'],
    clinical_boundary: 'No diagnosis or treatment decisions are generated by this service.',
  };
}

async function safe(res, fn) {
  try {
    const data = await fn();
    return res.json({ success: true, data });
  } catch (error) {
    return res.status(400).json({ success: false, error: error.message });
  }
}

module.exports = router;
