CREATE TABLE IF NOT EXISTS village_capability_profiles(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id UUID NOT NULL,village_id UUID NOT NULL,entity_type VARCHAR(20) NOT NULL CHECK(entity_type IN('freelancer','artisan','shg','fpo','panchayat')),entity_id VARCHAR(100) NOT NULL,display_name TEXT NOT NULL,skills TEXT[] NOT NULL DEFAULT '{}',certifications JSONB NOT NULL DEFAULT '[]',available_capacity NUMERIC(18,4) NOT NULL CHECK(available_capacity>=0),capacity_unit VARCHAR(30) NOT NULL,lead_days INTEGER NOT NULL CHECK(lead_days>=0),unit_cost NUMERIC(18,4) CHECK(unit_cost>0),quality_score NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK(quality_score BETWEEN 0 AND 100),underserved_share NUMERIC(5,4) NOT NULL DEFAULT 0 CHECK(underserved_share BETWEEN 0 AND 1),status VARCHAR(20) NOT NULL DEFAULT 'active',created_by UUID NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(tenant_id,entity_type,entity_id));
CREATE TABLE IF NOT EXISTS institutional_demand_briefs(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id UUID NOT NULL,buyer_id UUID NOT NULL,title TEXT NOT NULL,specification JSONB NOT NULL,quantity NUMERIC(18,4) NOT NULL CHECK(quantity>0),unit VARCHAR(30) NOT NULL,max_unit_cost NUMERIC(18,4) NOT NULL CHECK(max_unit_cost>0),max_lead_days INTEGER NOT NULL CHECK(max_lead_days>0),required_skills TEXT[] NOT NULL DEFAULT '{}',delivery_location JSONB NOT NULL,state VARCHAR(20) NOT NULL CHECK(state IN('draft','published','awarded','in_production','completed','cancelled')),created_by UUID NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS village_commerce_quotations(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),demand_id UUID NOT NULL REFERENCES institutional_demand_briefs(id),capability_id UUID NOT NULL REFERENCES village_capability_profiles(id),quantity NUMERIC(18,4) NOT NULL CHECK(quantity>0),unit_cost NUMERIC(18,4) NOT NULL CHECK(unit_cost>0),delivery_date DATE NOT NULL,state VARCHAR(20) NOT NULL DEFAULT 'submitted',score_snapshot JSONB NOT NULL,created_by UUID NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(demand_id,capability_id));
CREATE TABLE IF NOT EXISTS village_cluster_allocations(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),demand_id UUID NOT NULL REFERENCES institutional_demand_briefs(id),quotation_id UUID NOT NULL REFERENCES village_commerce_quotations(id),allocated_quantity NUMERIC(18,4) NOT NULL CHECK(allocated_quantity>0),escrow_contract_id VARCHAR(100),journal_entry_id INTEGER, state VARCHAR(20) NOT NULL DEFAULT 'allocated',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS village_production_milestones(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),allocation_id UUID NOT NULL REFERENCES village_cluster_allocations(id),sequence_no INTEGER NOT NULL,title TEXT NOT NULL,due_at TIMESTAMPTZ NOT NULL,state VARCHAR(20) NOT NULL DEFAULT 'pending',evidence JSONB NOT NULL DEFAULT '[]',UNIQUE(allocation_id,sequence_no));
CREATE TABLE IF NOT EXISTS village_quality_acceptances(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),allocation_id UUID NOT NULL REFERENCES village_cluster_allocations(id),accepted_quantity NUMERIC(18,4) NOT NULL CHECK(accepted_quantity>=0),rejected_quantity NUMERIC(18,4) NOT NULL CHECK(rejected_quantity>=0),inspection JSONB NOT NULL,decision VARCHAR(20) NOT NULL CHECK(decision IN('accepted','partially_accepted','rejected')),inspected_by UUID NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS village_commerce_audit(id BIGSERIAL PRIMARY KEY,tenant_id UUID NOT NULL,entity_type VARCHAR(30) NOT NULL,entity_id UUID NOT NULL,action VARCHAR(50) NOT NULL,actor_id UUID NOT NULL,detail JSONB NOT NULL DEFAULT '{}',occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_village_capability_tenant_skills ON village_capability_profiles USING GIN(skills);
CREATE INDEX IF NOT EXISTS idx_institutional_demand_tenant_state ON institutional_demand_briefs(tenant_id,state);
