'use strict';
const crypto=require('crypto'); const db=require('../../database/pool'); const ai=require('../aiGatewayService');
const {ValidationError,ConflictError,NotFoundError,AppError}=require('../../utils/errors');
const money=v=>{const n=Number(v);if(!Number.isFinite(n)||n<0)throw new ValidationError('Invalid monetary amount');return Math.round(n*100)/100};
const transitions={draft:['under_review'],under_review:['approved','declined'],approved:['active'],active:['expired','cancelled'],fnol:['evidence_pending','survey_pending'],evidence_pending:['survey_pending'],survey_pending:['fraud_review','assessed'],fraud_review:['assessed','rejected'],assessed:['approved','rejected'],approved_claim:['settled']};
class RuralInsuranceService{
 constructor({database=db,gateway=ai}={}){this.db=database;this.gateway=gateway}
 quote(i){const sum=money(i.sumInsured),rate=Number(i.ratePercent);if(!Number.isFinite(rate)||rate<=0)throw new ValidationError('ratePercent is required');const base=money(sum*rate/100),subsidy=money(Math.min(base,base*Number(i.subsidyPercent||0)/100));return{sumInsured:sum,basePremium:base,subsidy,farmerPayable:money(base-subsidy),calculation:{formula:'sumInsured * ratePercent / 100',ratePercent:rate}}}
 fraudScore(i={}){const factors=[];let score=0;if(i.claimAmount>i.sumInsured){score+=45;factors.push('amount_exceeds_cover')}if((i.duplicateEvidence||0)>0){score+=30;factors.push('duplicate_evidence')}if((i.daysSinceInception||99)<15){score+=15;factors.push('early_claim')}return{score:Math.min(score,100),band:score>=60?'high':score>=30?'medium':'low',factors,decision:'advisory_review_only'}}
 async tx(fn){const c=await this.db.connect();try{await c.query('BEGIN');const r=await fn(c);await c.query('COMMIT');return r}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
 async audit(c,type,id,event,actor,payload={}){await c.query('INSERT INTO rural_insurance_audit(aggregate_type,aggregate_id,event_type,actor_id,payload) VALUES($1,$2,$3,$4,$5::jsonb)',[type,id,event,actor,JSON.stringify(payload)])}
 async createQuote(i,actor){const q=this.quote(i);return this.tx(async c=>{const r=await c.query(`INSERT INTO rural_insurance_quotes(organization_id,product_version_id,farmer_id,order_id,asset_id,subsidy_application_id,sum_insured,base_premium,subsidy_amount,farmer_payable,input_evidence,status,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,'draft',$12) RETURNING *`,[i.organizationId,i.productVersionId,i.farmerId,i.orderId||null,i.assetId||null,i.subsidyApplicationId||null,q.sumInsured,q.basePremium,q.subsidy,q.farmerPayable,JSON.stringify(i.evidence||{}),actor]);await this.audit(c,'quote',r.rows[0].id,'quote.created',actor,q);return r.rows[0]})}
 async transition(table,id,next,actor,notes){return this.tx(async c=>{const f=await c.query(`SELECT * FROM ${table} WHERE id=$1 FOR UPDATE`,[id]);if(!f.rows[0])throw new NotFoundError('Insurance record');const cur=f.rows[0].status;if(!transitions[cur]?.includes(next))throw new ConflictError(`Invalid transition ${cur} -> ${next}`);const r=await c.query(`UPDATE ${table} SET status=$2,decision_notes=$3,updated_at=NOW() WHERE id=$1 RETURNING *`,[id,next,notes||null]);await this.audit(c,table,id,`${table}.${next}`,actor,{notes});return r.rows[0]})}
 async fnol(i,actor){return this.tx(async c=>{const p=await c.query("SELECT * FROM rural_insurance_policies WHERE id=$1 AND organization_id=$2 AND status='active'",[i.policyId,i.organizationId]);if(!p.rows[0])throw new AppError('Active policy not found',404);const r=await c.query(`INSERT INTO rural_insurance_claims(policy_id,organization_id,loss_date,loss_type,claim_amount,description,status,reported_by) VALUES($1,$2,$3,$4,$5,$6,'fnol',$7) RETURNING *`,[i.policyId,i.organizationId,i.lossDate,i.lossType,money(i.claimAmount),i.description,actor]);await this.audit(c,'claim',r.rows[0].id,'claim.fnol',actor);return r.rows[0]})}
 async advise(i,actor){const r=await this.gateway.run({moduleId:'rural-insurance',capability:'advisory-underwriting-claims',prompt:i.objective,context:{actor,evidence:i.evidence||{}}});return{...r,decisionAuthority:false,humanReviewRequired:true}}
}
module.exports=new RuralInsuranceService();module.exports.RuralInsuranceService=RuralInsuranceService;
