/** Canonical concept-to-runtime catalog. Nothing removed. Every item classified. */

import type { OsItem, OsStageMeta } from "./types.ts";

export const OS_STAGES: OsStageMeta[] = [
  { stage: 0, name: "Concept reconciliation", target: "Preserve and classify everything.", exit: "Every concept has source, meaning, class, kernel vs GitHub." },
  { stage: 1, name: "Industry baseline", target: "Identity, data, APIs, workflows, security, tests, observability.", exit: "Clerk, remaining grams, journal, workflows, dual-truth registry pass on this kernel." },
  { stage: 2, name: "Sector excellence", target: "Industry-native journeys.", exit: "Agriculture walk living. Insurance, banking, travel, engineering still named." },
  { stage: 3, name: "Intelligent assistance", target: "Grounded AI on each component.", exit: "Library, companion, firewall, evidence. No invented ₹." },
  { stage: 4, name: "System intelligence", target: "Events, agents, knowledge, twins coordinate.", exit: "Module OS bus. Digital twins and federated learning remain proposed." },
  { stage: 5, name: "Autonomous ecosystem", target: "Bounded execution.", exit: "Companion proposes. Clerk approves. Consequential writes stay human." },
  { stage: 6, name: "Futuristic platform", target: "Adaptive economic OS.", exit: "Named. Not claimed. Village twin and energy cloud still missing." },
];

function i(
  id: string,
  name: string,
  table: OsItem["table"],
  stage: OsItem["stage"],
  level: OsItem["level"],
  area: string,
  kernel: OsItem["kernel"],
  github: OsItem["github"],
  present: string,
  missing: string,
  next: string,
  organs: string[],
  href: string,
  todo: OsItem["todo"],
): OsItem {
  return { id, name, table, stage, level, area, kernel, github, present, missing, next, organs, href, todo };
}

export const OS_ITEMS: OsItem[] = [
  // Levels
  i("lv-1", "Transactional platform", "level", 1, 1, "platform", "partial", "scaffolded", "Lots, receipts, orders, journal, FPO split.", "GST, e-invoice, bank rails, 3-way match.", "Keep kernel. Do not invent a second ledger.", ["erp", "lot", "rupee"], "/platform", "done"),
  i("lv-2", "Sector digital businesses", "level", 2, 2, "sectors", "partial", "scaffolded", "Agriculture walk. Cover, kitchen, next Magh.", "Travel, banking, health, engineering journeys.", "One sector native: spice/horticulture. Others stay named.", ["crop", "farmer", "marketplace"], "/pulse", "open"),
  i("lv-3", "Shared ERP / identity / workflow", "level", 1, 3, "erp", "partial", "duplicated", "Clerk, remaining grams, Module OS, L1–L12.", "One GitHub identity. Chart of accounts. Period close.", "This kernel is the shared bone. GitHub folders stay cadavers until they plug.", ["erp", "spine", "module"], "/charter", "done"),
  i("lv-4", "India / rural-first access", "level", 2, 4, "rural", "partial", "documented", "Vernacular copy, mobile books, assisted companion.", "Offline queue, IVR/SMS, shared-device consent.", "Assisted operator lives. Offline sync is still missing.", ["farmer", "household"], "/companion", "open"),
  i("lv-5", "AI nervous system on evidence", "level", 3, 5, "ai", "partial", "scaffolded", "25 plugs, library reflexes, firewall, companion.", "Model registry, drift, citations, outcome feedback.", "Library-first. LLM only on miss. Never a rupee write.", ["ai", "spine", "module"], "/nerve", "done"),
  i("lv-6", "Adaptive UX from consented context", "level", 3, 6, "ux", "proposed", "documented", "Need-based intents. Role is a door, not a profile.", "Consent ledger, intent engine, non-personalized mode.", "Do not infer caste, religion, health. Voluntary constraints only.", ["farmer", "household"], "/os", "open"),

  // Critical gaps
  i("g-sot", "Single source of truth", "gap", 0, 3, "architecture", "verified", "disconnected", "This catalog. 16-link chain. Four-level enhance. Concept → module → feature → user → workflow → rules → database → service → API → authorization → AI → ERP → page → component → test → telemetry.", "GitHub still has competing registries.", "Never remove. Classify. Dual-truth.", ["os", "erp", "module"], "/os", "done"),
  i("g-auth", "Coherent authentication", "gap", 1, 3, "security", "verified", "disconnected", "This organism: clerk. No mock JWT, no plaintext users.", "GitHub authRoutes in-memory + JWT middleware split.", "Do not mount the mock. Canonicalize on that branch separately.", ["farmer"], "/os", "done"),
  i("g-journey", "Industry journeys", "gap", 2, 2, "sectors", "partial", "scaffolded", "Agriculture harvest→godown→offtake→settle.", "Travel, insurance claims, banking, logistics tower, DPR.", "Finish agriculture. Name the others. Do not clone dashboards.", ["crop", "orders"], "/pulse", "open"),
  i("g-adaptive", "Governed adaptive webpage", "gap", 3, 6, "ux", "proposed", "documented", "Need-based nav. No dark patterns.", "Consent profile, experimentation, outcome measurement.", "Intents only. No inferred sensitive traits.", ["farmer"], "/os", "open"),
  i("g-ai", "Governed AI architecture", "gap", 3, 5, "ai", "partial", "scaffolded", "Gateway, coordinator, library, firewall, human command.", "Training, drift, bias, cost, citations, eval harness.", "Evidence or hide. Random wrappers are not AI.", ["ai", "module"], "/modules", "open"),
  i("g-workflow", "State-driven workflows", "gap", 1, 3, "workflow", "partial", "scaffolded", "harvest-mint, warehouse-intake, offtake-settle, nerve-consult.", "Booking, RFQ, claim, loan, subsidy, grievance, recall.", "Durable steps persist. Unknown events fail.", ["spine", "lot"], "/modules", "open"),
  i("g-erp", "Unified ERP control", "gap", 1, 3, "erp", "partial", "duplicated", "Paise journal, remaining, FIFO, WAC, FPO split, trial balance.", "CoA, tax, 3-way, bank rec, assets, SoD, period close.", "Journal is the GL of this village. Do not invent ₹.", ["erp", "rupee"], "/platform", "open"),
  i("g-india", "India-first intelligence", "gap", 2, 4, "india", "partial", "documented", "GI mint, Magh kitchen, Langthasa cover, FPO cells.", "Mandi feed, GST, land registry, scheme rules engine.", "Schemes stay missing until effective-dated.", ["scheme", "fpo", "gcip"], "/trade", "open"),
  i("g-organism", "Executable super-organism", "gap", 0, 1, "organism", "partial", "documented", "Organs, ligaments, pulse, library, nerve, charter, OS board.", "Sensory IoT, immune fraud, circulatory payments.", "Map, do not metaphor.", ["os", "spine", "ai"], "/organism", "done"),
  i("g-data", "Real analytics lineage", "gap", 1, 5, "analytics", "partial", "scaffolded", "Books KPIs from rows. No random dashboards here.", "GitHub dashboards still simulate.", "No metric without source.", ["erp", "rcop"], "/ledger", "done"),
  i("g-trust", "Trust and reputation", "gap", 2, 2, "trust", "partial", "documented", "GI mint, paymentRef, remaining, evidence passport.", "Dispute-adjusted scores, appeal, chain of custody network.", "Passport first. Stars later.", ["trace", "lot"], "/lots", "open"),
  i("g-rural", "Rural-first access complete", "gap", 2, 4, "rural", "partial", "documented", "Mobile books, companion assist, vernacular thesis.", "Offline queue, SMS/IVR, shared-device consent, sync audit.", "Assisted mode lives. Offline does not.", ["farmer", "household"], "/companion", "open"),
  i("g-eng", "Engineering calculation chain", "gap", 2, 2, "engineering", "documented", "scaffolded", "Names and MEP hooks on GitHub.", "Units, standards, BIM, BOQ, professional approval.", "Do not fake CFD.", ["shared"], "/os", "blocked"),
  i("g-prod", "Production verification", "gap", 1, 1, "ops", "partial", "scaffolded", "Unit tests, typecheck, browser smoke on this kernel.", "Load, backup restore, pen-test, rollback on GitHub.", "File existence is not readiness.", ["erp"], "/os", "open"),

  // Table 1 concepts
  i("c-organism", "Digital Super-Organism", "concept", 0, 1, "organism", "partial", "documented", "Brain/nerve/memory as library+module OS+charter.", "Executable immune, sensory IoT, payment circulation.", "OS board maps every metaphor to a service.", ["os", "ai", "spine"], "/os", "done"),
  i("c-modules", "Modular M001–M150 platform", "concept", 0, 3, "modules", "partial", "scaffolded", "25 living plugs. Charter 18 criteria.", "~760 GitHub services; WIRED skeletons; duplicates.", "Registry with runtime status. Do not delete folders.", ["module"], "/modules", "done"),
  i("c-agri", "Agriculture operating system", "concept", 2, 2, "agriculture", "partial", "scaffolded", "Plot/planting, harvest mint, grade, store, sell, settle.", "Finance-procure-operate loop, fisheries, livestock cashflow.", "Walk is living. Livestock is partial.", ["crop", "lot", "farmer"], "/lots", "open"),
  i("c-erp", "Enterprise ERP", "concept", 1, 3, "erp", "partial", "duplicated", "Village books, platform trial balance, process mass.", "Unified CoA, tax, intercompany, period close.", "Connect operational txn to this journal only.", ["erp", "rupee"], "/platform", "open"),
  i("c-market", "Marketplace", "concept", 2, 2, "commerce", "partial", "scaffolded", "Offtake, declared price, GI frame, FPO pool.", "Discovery, returns, trust graph, settlement rails.", "Listing is born from harvest, not a SKU form.", ["marketplace", "orders"], "/trade", "open"),
  i("c-insure", "Insurance", "concept", 2, 2, "insurance", "partial", "scaffolded", "Langthasa godown cover. Premium never invented.", "Need analysis, exclusions, claims, survey, appeal.", "Cover binds. Claims OS is missing.", ["insurance"], "/warehouse", "open"),
  i("c-bank", "Banking and rural finance", "concept", 2, 2, "finance", "documented", "scaffolded", "Hours-to-pay on the cell. Pledge gate.", "Underwriting, disbursement, recovery, explainability.", "No invented credit score.", ["finance", "farmer"], "/ledger", "open"),
  i("c-logistics", "Logistics", "concept", 2, 2, "logistics", "partial", "scaffolded", "Declared freight (zero allowed). Spoilage remainder.", "Control tower, ETA, PoD, load pooling.", "Freight is a deduction, not a marketplace yet.", ["logistics"], "/trade", "open"),
  i("c-eng", "Engineering platform", "concept", 2, 2, "engineering", "documented", "scaffolded", "GitHub names, MEP plan-to-BOQ mention.", "Standards, units, BIM, simulation, commissioning.", "Blocked on professional approval boundaries.", ["shared"], "/os", "blocked"),
  i("c-scheme", "Government schemes", "concept", 2, 4, "india", "missing", "documented", "Named as blood, not PDF.", "Effective-dated rules, eligibility, grievance.", "Do not scrape PDFs into a chatbot.", ["scheme"], "/os", "open"),
  i("c-auth", "Authentication", "concept", 1, 3, "security", "verified", "disconnected", "Clerk on this kernel. Auth off for visitors.", "GitHub mock users + JWT split.", "One identity authority on that branch later.", ["farmer"], "/os", "done"),
  i("c-personal", "Personalization", "concept", 3, 6, "ux", "proposed", "documented", "Need-based intents. No hidden profile.", "Consent ledger, ranking, reset, non-personalized mode.", "Voluntary constraints only.", ["farmer", "household"], "/os", "open"),
  i("c-ai", "AI services", "concept", 3, 5, "ai", "partial", "duplicated", "One bus, 25 plugs, library-first, firewall.", "GitHub 16 sibling chats. No eval harness.", "A wrapper is not production AI.", ["ai", "module"], "/modules", "open"),
  i("c-access", "Rural accessibility", "concept", 2, 4, "rural", "partial", "documented", "Mobile layout, companion assist.", "Offline, IVR, translation review, sync trail.", "Assisted operator is living.", ["household", "farmer"], "/companion", "open"),
  i("c-analytics", "Analytics", "concept", 1, 5, "analytics", "partial", "scaffolded", "KPIs from remaining and journal.", "Lineage, freshness, experiments on GitHub.", "Ban simulated business numbers.", ["erp"], "/", "done"),
  i("c-knowledge", "Knowledge platform", "concept", 3, 5, "knowledge", "verified", "scaffolded", "Library hippocampus, 19+ reflexes, bindings.", "OCR graph, permissions, cited rules engine.", "Memory lives without an API key.", ["ai"], "/library", "done"),
  i("c-esg", "Sustainability", "concept", 2, 2, "esg", "missing", "documented", "Village spoilage grams. Declared kWh only.", "Methodology, factors, audit, attribution.", "Do not invent emissions.", ["rcop", "recie"], "/ledger", "open"),

  // Table 2 baseline
  i("b-arch", "Product architecture", "baseline", 1, 3, "architecture", "verified", "overlapping", "Bounded organs + ligaments + module contracts.", "GitHub overlapping services.", "Capability registry is this catalog.", ["os", "module"], "/os", "done"),
  i("b-journey", "User journeys", "baseline", 1, 2, "ux", "partial", "scaffolded", "Pulse walk + books flow + need intents.", "Sector-native maps for travel/banking/health.", "Agriculture journey is the proof.", ["crop", "farmer"], "/pulse", "done"),
  i("b-api", "API architecture", "baseline", 1, 3, "api", "partial", "disconnected", "Server functions, one kernel.", "GitHub many naming conventions.", "Idempotent clerk writes only.", ["erp"], "/platform", "done"),
  i("b-ident", "Authentication baseline", "baseline", 1, 3, "security", "verified", "disconnected", "No mock login on this kernel.", "Canonicalize GitHub identity later.", "Clerk is the human command.", ["farmer"], "/os", "done"),
  i("b-authz", "Authorization", "baseline", 1, 3, "security", "partial", "scaffolded", "AI rupeeWrite false. Clerk writes.", "ABAC, SoD, authorization tests on GitHub.", "L8–L9 are the policy.", ["ai", "rupee"], "/charter", "done"),
  i("b-data", "Data architecture", "baseline", 1, 3, "data", "verified", "overlapping", "PGLite migrations. remaining_grams source of truth.", "Schema collisions on GitHub (plantings/farms/plots).", "Lot body is one id.", ["lot", "erp"], "/lots", "done"),
  i("b-wf", "Workflow orchestration", "baseline", 1, 3, "workflow", "verified", "scaffolded", "Durable module_steps. pass/block/defer/propose.", "Timers, compensation, saga on GitHub.", "Unknown events fail (L12).", ["spine", "module"], "/modules", "done"),
  i("b-erpctl", "ERP control", "baseline", 1, 3, "erp", "partial", "duplicated", "Journal, FIFO, WAC, trial balance, process mass.", "Tax, 3-way, bank rec, assets.", "Village GL is enough to be honest.", ["erp", "rupee"], "/platform", "open"),
  i("b-ui", "UI architecture", "baseline", 1, 6, "ux", "verified", "scaffolded", "Editorial tokens. Sector boards. No purple.", "GitHub many page inventories.", "Need-based composer starts here.", ["os"], "/os", "done"),
  i("b-resp", "Mobile / responsive", "baseline", 1, 4, "rural", "partial", "documented", "390 layout, overflow-x nav.", "Device matrix, PWA offline.", "Touch targets hold.", ["farmer"], "/", "done"),
  i("b-off", "Offline", "baseline", 1, 4, "rural", "missing", "documented", "PWA chrome exists.", "Encrypted queue, conflict, sync receipt.", "Do not fake store-and-forward.", ["spine"], "/os", "open"),
  i("b-a11y", "Accessibility", "baseline", 1, 4, "rural", "partial", "documented", "Labels, contrast, keyboard on controls.", "Full WCAG journeys, voice confirm.", "Keep forms labelled.", ["farmer"], "/os", "open"),
  i("b-i18n", "Multilingual", "baseline", 1, 4, "india", "partial", "documented", "Domain vocabulary in copy (cell, lot, farmgate).", "Terminology registry, transliteration, review.", "Do not auto-translate rupee laws.", ["household"], "/os", "open"),
  i("b-sec", "Security", "baseline", 1, 3, "security", "partial", "scaffolded", "No secrets in repo. Firewall on AI writes.", "Threat model, pen-test, incident playbook.", "Clerk boundary is the control.", ["ai"], "/charter", "open"),
  i("b-consent", "Privacy and consent", "baseline", 1, 6, "privacy", "partial", "documented", "Constitution E1–E8 enforced. No inferred caste/religion/health. Auth-off default.", "Consent receipts, deletion, purpose binding.", "Voluntary constraints only.", ["farmer"], "/os", "done"),
  i("b-test", "Testing evidence", "baseline", 1, 1, "ops", "verified", "scaffolded", "Kernel, lattice, charter, library, erp tests.", "E2E auth, migration, resilience on GitHub.", "Mocked green is not complete.", ["erp", "module"], "/os", "done"),
  i("b-obs", "Observability", "baseline", 1, 5, "ops", "partial", "scaffolded", "module_runs, pulses, auto-op.", "SLOs, traces, redaction on GitHub.", "Correlation is lotId.", ["spine"], "/modules", "open"),
  i("b-rel", "Reliability", "baseline", 1, 1, "ops", "partial", "scaffolded", "Startup revive, migrations idempotent.", "DR, failover, backup restore.", "PGLite is the village memory here.", ["erp"], "/os", "open"),
  i("b-content", "Content governance", "baseline", 0, 5, "knowledge", "verified", "documented", "Library cards sourced. Effective doctrine.", "GitHub completion certificates vs runtime.", "Cited or it is gossip.", ["ai"], "/library", "done"),
  i("b-gov", "Completion governance", "baseline", 0, 1, "architecture", "verified", "disconnected", "Nothing complete without runtime+data+tests.", "Hundreds of COMPLETE reports on GitHub.", "Kernel under 40%. 7% platform. Dual-truth.", ["os"], "/os", "done"),

  // Table 3 innovations
  i("n-composer", "Sector Experience Composer", "innovation", 2, 6, "ux", "partial", "proposed", "Need intents + sector boards (books, warehouse, trade).", "Travel/insurance/ERP templates.", "Shared primitives. Different journeys.", ["os"], "/os", "done"),
  i("n-event", "Life-and-Business Event Engine", "innovation", 4, 1, "spine", "partial", "scaffolded", "harvest.completed, intake, settle, spoilage, cover.bound. Unknown events fail.", "Marriage, illness, price-crash fan-out.", "Spine publishes. Unknown events fail.", ["spine"], "/pulse", "done"),
  i("n-passport", "Evidence Passport", "innovation", 1, 2, "trust", "verified", "documented", "Lot passport: GI, cover, remaining, paymentRef, journal.", "Portable credential across organs on GitHub.", "Absent stays absent.", ["lot", "trace"], "/lots", "done"),
  i("n-profile", "User-Controlled Digital Profile", "innovation", 3, 6, "privacy", "proposed", "documented", "Cell is the nucleus. No hidden dossier.", "Inspect/correct/revoke ledger.", "Auth-off here. Do not fake a profile.", ["farmer"], "/os", "blocked"),
  i("n-need", "Need-Based Navigation", "innovation", 1, 6, "ux", "verified", "documented", "Sell crop / mint / store / claim / Magh.", "Full problem taxonomy.", "Module names are not the door.", ["farmer", "os"], "/os", "done"),
  i("n-compare", "Cross-Sector Comparison Engine", "innovation", 2, 2, "commerce", "proposed", "documented", "None on this kernel.", "User-weighted comparison with exclusions.", "Do not rank without declared criteria.", ["marketplace"], "/os", "open"),
  i("n-trust", "Trust Graph", "innovation", 2, 2, "trust", "partial", "documented", "GI mint + paymentRef + remaining + passport.", "Dispute, retaliation-safe reviews.", "Evidence over stars.", ["trace", "fpo"], "/lots", "open"),
  i("n-benefit", "Benefit Realization Ledger", "innovation", 3, 5, "analytics", "partial", "documented", "Village TCO vs declared spoilage. Farmgate vs inputs.", "Predicted vs actual yield/income with causality label.", "No success without a row.", ["rcop", "rupee"], "/ledger", "done"),
  i("n-exception", "Exception Command Centre", "innovation", 1, 3, "ops", "verified", "scaffolded", "Platform exceptions G1–G9 with impact, owner, action. Blocking/deferred counts.", "Escalate and verify closure across GitHub alerts.", "One place. Impact first.", ["erp", "spine"], "/platform", "done"),
  i("n-assist", "Assisted Digital Operator", "innovation", 2, 4, "rural", "verified", "documented", "Companion proposes. Clerk confirms kg/₹/ref.", "Delegated consent, recorded assistance on GitHub.", "User confirmation required.", ["farmer", "module"], "/companion", "done"),
  i("n-rules", "Rules-as-Evidence", "innovation", 1, 3, "knowledge", "verified", "documented", "L1–L12 executable. Gates named.", "Scheme/GST rules with citation+effective date.", "Authority, date, logic, reviewer.", ["module", "scheme"], "/charter", "done"),
  i("n-suit", "Suitability Layer", "innovation", 3, 2, "trust", "verified", "documented", "Refuse loan, travel, invented premium, undated scheme. Cover may bind without a quote.", "Affordability engine, exclusions comparison on GitHub.", "Do not recommend a loan here.", ["finance", "insurance"], "/os", "done"),
  i("n-cap", "Capability Marketplace", "innovation", 4, 3, "modules", "partial", "proposed", "Module OS contracts, health, firewall.", "Signed adapters, migrations, permissions on GitHub.", "Plug without a second organism.", ["module"], "/modules", "open"),
  i("n-grief", "Digital Grievance Spine", "innovation", 2, 4, "trust", "partial", "documented", "Village cases from G1–G5. Complaint → ack → evidence. No invented ₹.", "Insurance/government appeal machine.", "Do not hide disputes in chat.", ["farmer", "spine"], "/os", "done"),
  i("n-ethic", "Ethical Engagement Engine", "innovation", 3, 6, "ux", "verified", "documented", "No dark patterns. Firewall. Library-first. 99.5% token save.", "Experiment framework, fatigue controls.", "Benefit over addiction.", ["ai", "farmer"], "/economy", "done"),

  // Table 4 AI enhancements
  i("a-comp", "Intelligent component", "ai", 3, 5, "ai", "partial", "scaffolded", "Four-level enhance. Boards explain remaining, gates, next action. Envelope on proposals.", "Language adapt + outcome feedback on GitHub.", "Explain or hide.", ["ai"], "/os", "done"),
  i("a-form", "Evidence-aware form", "ai", 3, 5, "ai", "partial", "scaffolded", "Harvest/process/settle forms. Declared only.", "OCR, voice, inconsistency detection.", "Save/resume is the clerk.", ["lot"], "/lots", "open"),
  i("a-search", "Multimodal intent search", "ai", 3, 5, "ai", "partial", "scaffolded", "Library query. Nerve consult.", "Image, geo, vernacular, permissioned retrieval.", "Library-first.", ["ai"], "/nerve", "open"),
  i("a-rec", "Constraint-aware recommendation", "ai", 3, 5, "ai", "partial", "scaffolded", "Companion ranks settle/intake/harvest. No invented ₹.", "Causal benefit, season, consent.", "Propose only.", ["module"], "/companion", "done"),
  i("a-dash", "Adaptive decision workspace", "ai", 3, 6, "ux", "partial", "scaffolded", "OS board + books + exceptions.", "Role/risk/geography composer.", "Priorities from remaining and gates.", ["os", "erp"], "/os", "done"),
  i("a-note", "Intelligent intervention", "ai", 3, 5, "ai", "proposed", "scaffolded", "Copilot strip. No push spam.", "Channel/timing/fatigue engine.", "Do not nag.", ["ai"], "/companion", "open"),
  i("a-wf", "AI-assisted dynamic workflow", "ai", 4, 5, "workflow", "partial", "scaffolded", "Engine selects next step. Missing evidence defers.", "Predict evidence, escalate.", "pass/block/defer/propose.", ["spine"], "/modules", "done"),
  i("a-doc", "Document intelligence", "ai", 3, 5, "knowledge", "partial", "scaffolded", "Issue harvest/warehouse/settle documents.", "OCR, layout, compliance coords.", "Human verifies.", ["erp"], "/platform", "open"),
  i("a-pdp", "Trust-and-suitability page", "ai", 3, 2, "commerce", "partial", "scaffolded", "GI frame, remaining, declared price.", "Dietary/cultural filters with consent.", "No silent profiling.", ["marketplace"], "/trade", "open"),
  i("a-ins", "Protection-gap adviser", "ai", 3, 2, "insurance", "partial", "scaffolded", "Cover bound without premium.", "Exclusions, scenarios, affordability.", "Do not invent a quote.", ["insurance"], "/warehouse", "open"),
  i("a-travel", "Contextual journey planner", "ai", 2, 2, "travel", "proposed", "scaffolded", "Not this village kernel.", "Budget/weather/food/access.", "Do not clone agriculture UX.", ["demand"], "/os", "blocked"),
  i("a-twin", "Farm digital-twin decisions", "ai", 4, 5, "agriculture", "partial", "documented", "Planting close, remaining, Magh memory.", "Soil/weather/water simulation.", "No invented yield.", ["crop", "village"], "/cells", "open"),
  i("a-fin", "Explainable cash-flow", "ai", 3, 2, "finance", "partial", "scaffolded", "Hours-to-pay, farmgate, inputs.", "Stress, early warning, underwriting.", "No silent score.", ["finance", "rupee"], "/ledger", "open"),
  i("a-log", "Predictive logistics market", "ai", 4, 2, "logistics", "proposed", "scaffolded", "Declared freight. Spoilage event.", "Pooling, ETA confidence, cold-chain.", "Cost is declared.", ["logistics"], "/os", "open"),
  i("a-net", "Demand-supply network", "ai", 4, 2, "commerce", "partial", "scaffolded", "Kitchen → next Magh offer at last kg.", "Fair allocation, waste reduction.", "Price stays blank until declared.", ["demand", "contract"], "/trade", "open"),
  i("a-ctl", "Continuous intelligent control", "ai", 4, 3, "erp", "partial", "scaffolded", "Journal balance gate. Exceptions.", "Fraud, margin leakage models.", "Anomaly is a defer, not a write.", ["erp"], "/platform", "open"),
  i("a-nerve", "Governed AI nervous system", "ai", 4, 5, "ai", "partial", "duplicated", "Router, library, agents, policy, human control.", "Eval, memory governance, cost/latency SLOs.", "One nerve. Many tissues.", ["ai", "module"], "/modules", "done"),
  i("a-nat", "Rural-economic intelligence network", "ai", 6, 1, "india", "proposed", "documented", "Langthasa books as the cell of a nation.", "Permissioned exchanges, public programs.", "Village first.", ["village", "os"], "/os", "open"),

  // Table 5 futuristic
  i("f-petwin", "Personal Economic Digital Twin", "future", 6, 5, "twin", "proposed", "documented", "None. Would simulate loan/crop/store before write.", "Household/farm/enterprise simulator.", "Show what-if. Never auto-execute.", ["farmer", "household"], "/os", "open"),
  i("f-vtwin", "Village / Cluster Digital Twin", "future", 6, 5, "twin", "partial", "documented", "Village ledger + plantings + remaining.", "Water/energy/storage/demand model.", "Identify shared gaps. No invented kWh.", ["village", "rcop"], "/ledger", "open"),
  i("f-aron", "Autonomous Rural Operations", "future", 5, 5, "agents", "partial", "documented", "Bounded companion. Approval thresholds.", "Procurement/logistics agents.", "Low-risk only. Writes stay human.", ["module"], "/companion", "open"),
  i("f-fed", "Federated Rural Intelligence", "future", 6, 5, "privacy", "proposed", "documented", "None.", "Learn without centralizing cell data.", "Local weights. National questions.", ["ai"], "/os", "blocked"),
  i("f-graph", "India Agricultural Knowledge Graph", "future", 4, 5, "knowledge", "partial", "documented", "Kitchen graph Magh → Chakhao. Library cards.", "Soil/climate/research/scheme graph.", "Evidence-aware. Cited.", ["foodgraph", "gcip"], "/library", "open"),
  i("f-diet", "Cultural / Dietary Constraint Engine", "future", 3, 6, "privacy", "proposed", "documented", "Voluntary. Not inferred.", "Filter, never profile.", "Cannot set price/credit/eligibility.", ["household", "fvie"], "/os", "open"),
  i("f-climate", "Climate Adaptation Autopilot", "future", 5, 5, "reflex", "missing", "documented", "Weather still a page on GitHub.", "Simulate adaptation daily.", "Reflex or hide.", ["soil", "reflex"], "/os", "open"),
  i("f-circ", "Circular Resource Exchange", "future", 6, 2, "esg", "proposed", "documented", "Spoilage as village fever. No waste market.", "By-product, return load, unused capacity.", "Waste is a rupee if declared.", ["rcop"], "/os", "open"),
  i("f-cbo", "Community Benefit Optimizer", "future", 6, 2, "fairness", "proposed", "documented", "Qty-weighted FPO split. Last cell remainder.", "Income+affordability+resilience objective.", "Not platform GMV.", ["fpo", "rupee"], "/trade", "open"),
  i("f-policy", "Policy Simulation Laboratory", "future", 6, 4, "india", "proposed", "documented", "None.", "Scheme twins before gazette.", "Evidence for government.", ["scheme", "village"], "/os", "blocked"),
  i("f-obi", "Outcome-Based Insurance", "future", 5, 2, "insurance", "proposed", "documented", "Cover bound. No premium.", "Prevention linked to protection.", "Do not invent a rate.", ["insurance"], "/os", "open"),
  i("f-infra", "Infrastructure Intelligence Network", "future", 6, 2, "engineering", "proposed", "scaffolded", "Godown cover. No thermal twin.", "Cold store/solar/pond twins.", "Engineering approval required.", ["warehouse", "recie"], "/os", "blocked"),
  i("f-aidp", "Verifiable AI Decision Passport", "future", 4, 5, "ai", "partial", "documented", "Step payload: decision, organ, lotId, algorithm.", "Portable audit across institutions.", "Challenge and correct.", ["ai", "lot"], "/modules", "open"),
  i("f-coop", "Personal Data Cooperative", "future", 6, 6, "privacy", "proposed", "documented", "None.", "Collective license of permitted data.", "Value to contributors.", ["farmer"], "/os", "blocked"),
  i("f-reflex", "Disaster / Disruption Reflex", "future", 5, 5, "reflex", "partial", "documented", "Spoilage cuts remaining. Cover binds. EMI pause named.", "Flood/heat/price-crash pre-approved bundle.", "Warning must move a muscle.", ["reflex", "insurance"], "/warehouse", "open"),
  i("f-syn", "Synthetic Scenario Exchange", "future", 6, 5, "ops", "proposed", "documented", "Tests on Magh numbers. No rare-event farm.", "Generate failures before they happen.", "Never as live rupees.", ["erp"], "/os", "open"),
  i("f-nlb", "Natural-Language Enterprise Builder", "future", 6, 3, "modules", "proposed", "documented", "Companion proposes workflows.", "Goal → screens/controls with human approve.", "Registry stays canonical.", ["module"], "/companion", "open"),
  i("f-heal", "Self-Healing Integration Fabric", "future", 5, 3, "modules", "partial", "scaffolded", "Charter names orphans. Selfheal step on bus.", "Contract+telemetry repairs. No speculative code.", "No-orphan continuously.", ["module", "spine"], "/charter", "open"),
  i("f-map", "National Capability Map", "future", 6, 4, "india", "proposed", "documented", "Langthasa is one village.", "Geo capacity/demand/gaps.", "Guide investment to shortage.", ["village"], "/os", "open"),
  i("f-const", "Ethical Personalization Constitution", "future", 3, 6, "ux", "verified", "documented", "No dark patterns. No inferred sensitive traits. Firewall.", "Machine-enforced constitution registry.", "Assistance ≠ manipulation.", ["ai", "farmer"], "/os", "done"),
];

export const OS_ITEM_BY_ID: Record<string, OsItem> = Object.fromEntries(OS_ITEMS.map((x) => [x.id, x]));
