/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BodyRouteImport } from './routes/body'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as CellsRouteImport } from './routes/cells'
import { Route as CharterRouteImport } from './routes/charter'
import { Route as CompanionRouteImport } from './routes/companion'
import { Route as EconomyRouteImport } from './routes/economy'
import { Route as FlowsRouteImport } from './routes/flows'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LigamentsRouteImport } from './routes/ligaments'
import { Route as LotsRouteImport } from './routes/lots'
import { Route as MeshRouteImport } from './routes/mesh'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as NerveRouteImport } from './routes/nerve'
import { Route as OrganismRouteImport } from './routes/organism'
import { Route as OsRouteImport } from './routes/os'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PulseRouteImport } from './routes/pulse'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as VetRouteImport } from './routes/vet'
import { Route as WarehouseRouteImport } from './routes/warehouse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyRoute = BodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const CellsRoute = CellsRouteImport.update({
  id: '/cells',
  path: '/cells',
  getParentRoute: () => rootRouteImport,
} as any)
const CharterRoute = CharterRouteImport.update({
  id: '/charter',
  path: '/charter',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionRoute = CompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomyRoute = EconomyRouteImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsRoute = FlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LigamentsRoute = LigamentsRouteImport.update({
  id: '/ligaments',
  path: '/ligaments',
  getParentRoute: () => rootRouteImport,
} as any)
const LotsRoute = LotsRouteImport.update({
  id: '/lots',
  path: '/lots',
  getParentRoute: () => rootRouteImport,
} as any)
const MeshRoute = MeshRouteImport.update({
  id: '/mesh',
  path: '/mesh',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const NerveRoute = NerveRouteImport.update({
  id: '/nerve',
  path: '/nerve',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganismRoute = OrganismRouteImport.update({
  id: '/organism',
  path: '/organism',
  getParentRoute: () => rootRouteImport,
} as any)
const OsRoute = OsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PulseRoute = PulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const VetRoute = VetRouteImport.update({
  id: '/vet',
  path: '/vet',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/body': typeof BodyRoute
  '/brain': typeof BrainRoute
  '/cells': typeof CellsRoute
  '/charter': typeof CharterRoute
  '/companion': typeof CompanionRoute
  '/economy': typeof EconomyRoute
  '/flows': typeof FlowsRoute
  '/ledger': typeof LedgerRoute
  '/library': typeof LibraryRoute
  '/ligaments': typeof LigamentsRoute
  '/lots': typeof LotsRoute
  '/mesh': typeof MeshRoute
  '/modules': typeof ModulesRoute
  '/nerve': typeof NerveRoute
  '/organism': typeof OrganismRoute
  '/os': typeof OsRoute
  '/platform': typeof PlatformRoute
  '/pulse': typeof PulseRoute
  '/share': typeof ShareRoute
  '/systems': typeof SystemsRoute
  '/trade': typeof TradeRoute
  '/vet': typeof VetRoute
  '/warehouse': typeof WarehouseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/body': typeof BodyRoute
  '/brain': typeof BrainRoute
  '/cells': typeof CellsRoute
  '/charter': typeof CharterRoute
  '/companion': typeof CompanionRoute
  '/economy': typeof EconomyRoute
  '/flows': typeof FlowsRoute
  '/ledger': typeof LedgerRoute
  '/library': typeof LibraryRoute
  '/ligaments': typeof LigamentsRoute
  '/lots': typeof LotsRoute
  '/mesh': typeof MeshRoute
  '/modules': typeof ModulesRoute
  '/nerve': typeof NerveRoute
  '/organism': typeof OrganismRoute
  '/os': typeof OsRoute
  '/platform': typeof PlatformRoute
  '/pulse': typeof PulseRoute
  '/share': typeof ShareRoute
  '/systems': typeof SystemsRoute
  '/trade': typeof TradeRoute
  '/vet': typeof VetRoute
  '/warehouse': typeof WarehouseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/body': typeof BodyRoute
  '/brain': typeof BrainRoute
  '/cells': typeof CellsRoute
  '/charter': typeof CharterRoute
  '/companion': typeof CompanionRoute
  '/economy': typeof EconomyRoute
  '/flows': typeof FlowsRoute
  '/ledger': typeof LedgerRoute
  '/library': typeof LibraryRoute
  '/ligaments': typeof LigamentsRoute
  '/lots': typeof LotsRoute
  '/mesh': typeof MeshRoute
  '/modules': typeof ModulesRoute
  '/nerve': typeof NerveRoute
  '/organism': typeof OrganismRoute
  '/os': typeof OsRoute
  '/platform': typeof PlatformRoute
  '/pulse': typeof PulseRoute
  '/share': typeof ShareRoute
  '/systems': typeof SystemsRoute
  '/trade': typeof TradeRoute
  '/vet': typeof VetRoute
  '/warehouse': typeof WarehouseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/body'
    | '/brain'
    | '/cells'
    | '/charter'
    | '/companion'
    | '/economy'
    | '/flows'
    | '/ledger'
    | '/library'
    | '/ligaments'
    | '/lots'
    | '/mesh'
    | '/modules'
    | '/nerve'
    | '/organism'
    | '/os'
    | '/platform'
    | '/pulse'
    | '/share'
    | '/systems'
    | '/trade'
    | '/vet'
    | '/warehouse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/body'
    | '/brain'
    | '/cells'
    | '/charter'
    | '/companion'
    | '/economy'
    | '/flows'
    | '/ledger'
    | '/library'
    | '/ligaments'
    | '/lots'
    | '/mesh'
    | '/modules'
    | '/nerve'
    | '/organism'
    | '/os'
    | '/platform'
    | '/pulse'
    | '/share'
    | '/systems'
    | '/trade'
    | '/vet'
    | '/warehouse'
  id:
    | '__root__'
    | '/'
    | '/body'
    | '/brain'
    | '/cells'
    | '/charter'
    | '/companion'
    | '/economy'
    | '/flows'
    | '/ledger'
    | '/library'
    | '/ligaments'
    | '/lots'
    | '/mesh'
    | '/modules'
    | '/nerve'
    | '/organism'
    | '/os'
    | '/platform'
    | '/pulse'
    | '/share'
    | '/systems'
    | '/trade'
    | '/vet'
    | '/warehouse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BodyRoute: typeof BodyRoute
  BrainRoute: typeof BrainRoute
  CellsRoute: typeof CellsRoute
  CharterRoute: typeof CharterRoute
  CompanionRoute: typeof CompanionRoute
  EconomyRoute: typeof EconomyRoute
  FlowsRoute: typeof FlowsRoute
  LedgerRoute: typeof LedgerRoute
  LibraryRoute: typeof LibraryRoute
  LigamentsRoute: typeof LigamentsRoute
  LotsRoute: typeof LotsRoute
  MeshRoute: typeof MeshRoute
  ModulesRoute: typeof ModulesRoute
  NerveRoute: typeof NerveRoute
  OrganismRoute: typeof OrganismRoute
  OsRoute: typeof OsRoute
  PlatformRoute: typeof PlatformRoute
  PulseRoute: typeof PulseRoute
  ShareRoute: typeof ShareRoute
  SystemsRoute: typeof SystemsRoute
  TradeRoute: typeof TradeRoute
  VetRoute: typeof VetRoute
  WarehouseRoute: typeof WarehouseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body': {
      id: '/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof BodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cells': {
      id: '/cells'
      path: '/cells'
      fullPath: '/cells'
      preLoaderRoute: typeof CellsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charter': {
      id: '/charter'
      path: '/charter'
      fullPath: '/charter'
      preLoaderRoute: typeof CharterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion': {
      id: '/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economy': {
      id: '/economy'
      path: '/economy'
      fullPath: '/economy'
      preLoaderRoute: typeof EconomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows': {
      id: '/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof FlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligaments': {
      id: '/ligaments'
      path: '/ligaments'
      fullPath: '/ligaments'
      preLoaderRoute: typeof LigamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lots': {
      id: '/lots'
      path: '/lots'
      fullPath: '/lots'
      preLoaderRoute: typeof LotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesh': {
      id: '/mesh'
      path: '/mesh'
      fullPath: '/mesh'
      preLoaderRoute: typeof MeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nerve': {
      id: '/nerve'
      path: '/nerve'
      fullPath: '/nerve'
      preLoaderRoute: typeof NerveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organism': {
      id: '/organism'
      path: '/organism'
      fullPath: '/organism'
      preLoaderRoute: typeof OrganismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os': {
      id: '/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof OsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pulse': {
      id: '/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof PulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vet': {
      id: '/vet'
      path: '/vet'
      fullPath: '/vet'
      preLoaderRoute: typeof VetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BodyRoute: BodyRoute,
  BrainRoute: BrainRoute,
  CellsRoute: CellsRoute,
  CharterRoute: CharterRoute,
  CompanionRoute: CompanionRoute,
  EconomyRoute: EconomyRoute,
  FlowsRoute: FlowsRoute,
  LedgerRoute: LedgerRoute,
  LibraryRoute: LibraryRoute,
  LigamentsRoute: LigamentsRoute,
  LotsRoute: LotsRoute,
  MeshRoute: MeshRoute,
  ModulesRoute: ModulesRoute,
  NerveRoute: NerveRoute,
  OrganismRoute: OrganismRoute,
  OsRoute: OsRoute,
  PlatformRoute: PlatformRoute,
  PulseRoute: PulseRoute,
  ShareRoute: ShareRoute,
  SystemsRoute: SystemsRoute,
  TradeRoute: TradeRoute,
  VetRoute: VetRoute,
  WarehouseRoute: WarehouseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
