import type { AiSystem } from "./types";

/**
 * AI systems on subhesco-bit/SUBH-DEEP @ consolidated/final.
 *
 * They were meant to be modules of one nervous system. On disk they are
 * sibling services, duplicate IDs, and thin re-exports. module.json says
 * WIRED. analysis.isComplete is false. Canonical paths are ~1KB wrappers
 * of legacy/. None subscribe to harvest.completed, lot.mint, or weather.alert.
 */
export const AI_SYSTEMS: AiSystem[] = [
  {
    id: "orchestrator",
    name: "AI Orchestrator",
    short: "Orchestrator",
    moduleId: "M402_AI_ORCHESTRATION",
    family: "core",
    declared: "WIRED",
    actual: "partial",
    bytesCanonical: 43882,
    bytesLegacy: null,
    liveCallers: 1,
    isComplete: false,
    frontend: false,
    routes: false,
    tests: false,
    organs: ["ai", "spine", "reflex"],
    path: "backend/src/core/aiOrchestrator.js",
    contract:
      "Route a task to one engine, score confidence, cap cost, write an audit. One spinal cord, not sixteen mouths.",
    silo: "A 43KB switch. Default case is log-and-forget. No harvest, lot, or weather subscribe. visionRoutes require it; the require is marked BROKEN.",
    plug: "orchestrator.route { organ, signal, lotId } — then fire one reflex, never a sibling chat.",
  },
  {
    id: "coordinator",
    name: "Claude Coordinator",
    short: "Coordinator",
    moduleId: "claudeAICoordinator",
    family: "core",
    declared: "none",
    actual: "partial",
    bytesCanonical: 13269,
    bytesLegacy: null,
    liveCallers: 1,
    isComplete: false,
    frontend: false,
    routes: false,
    tests: false,
    organs: ["ai", "spine"],
    path: "backend/src/core/claudeAICoordinator.js",
    contract:
      "The coordinator consults the library, names an organ, and only then may a model speak. It is not the on-switch.",
    silo: "Still calls queryLibraryKnowledge after that function was gutted to CRUD. Auto-operation never ran because syncDatabase was opt-in.",
    plug: "coordinator.consult { query, organId } after organism.booted — never before.",
  },
  {
    id: "fabric",
    name: "Intelligence Fabric",
    short: "Fabric",
    moduleId: "M410_AI_INTELLIGENCE_FABRIC",
    family: "core",
    declared: "WIRED",
    actual: "skeleton",
    bytesCanonical: 988,
    bytesLegacy: null,
    liveCallers: 0,
    isComplete: false,
    frontend: false,
    routes: false,
    tests: false,
    organs: ["ai", "spine", "rupee"],
    path: "backend/src/core/ai/AI_MODULE_REGISTRY.json",
    contract:
      "Provider routing, engine registry, confidence, cost control, guardrails, audit — one fabric under every organ.",
    silo: "A JSON list of seven file names. EBD-MOD-00000001. No organ binding. Cost controller does not know a farmer rupee.",
    plug: "fabric.allow { organ, spendPaise, signal } before any model call.",
  },
  {
    id: "backbone",
    name: "AI Backbone",
    short: "Backbone",
    moduleId: "M400_AI_BACKBONE / M752100_AIBACKBONE",
    family: "core",
    declared: "WIRED",
    actual: "duplicate",
    bytesCanonical: 1635,
    bytesLegacy: 36120,
    liveCallers: 0,
    isComplete: false,
    frontend: true,
    routes: true,
    tests: false,
    organs: ["ai", "erp", "spine"],
    path: "backend/src/services/aiBackboneService.js",
    contract:
      "The bony AI spine: one runtime that domain AIs attach to. Duplicate IDs are a fracture, not a feature.",
    silo: "Three names for one organ: M400_AI_CORE, M400_AI_BACKBONE, M752100_AIBACKBONE. Canonical service is a 1.6KB stub. Legacy holds 36KB. Pages exist; harvest does not.",
    plug: "backbone.attach { moduleId, organs[] } once. Kill the duplicate IDs.",
  },
  {
    id: "core",
    name: "AI Core",
    short: "Core",
    moduleId: "M400_AI_CORE",
    family: "core",
    declared: "WIRED",
    actual: "skeleton",
    bytesCanonical: 22871,
    bytesLegacy: 188,
    liveCallers: 1,
    isComplete: false,
    frontend: true,
    routes: false,
    tests: false,
    organs: ["ai"],
    path: "backend/src/services/aiService.js",
    contract:
      "A generic AI service is not a module. Core should be the fabric the others import — not another sibling named 'Ai'.",
    silo: "module.json name is 'Ai'. analysis.category SKELETON, isComplete false, routes false. Shares the M400 number with the backbone.",
    plug: "core is fabric. If two modules share M400, neither is a module.",
  },
  {
    id: "gateway",
    name: "AI Gateway",
    short: "Gateway",
    moduleId: "M401_AI_GATEWAY",
    family: "core",
    declared: "WIRED",
    actual: "skeleton",
    bytesCanonical: 15077,
    bytesLegacy: 16095,
    liveCallers: 0,
    isComplete: false,
    frontend: true,
    routes: true,
    tests: false,
    organs: ["ai", "spine"],
    path: "backend/src/services/ai/aiGatewayService.js",
    contract:
      "One door for every model call. Organs do not speak to providers. They speak to the gateway.",
    silo: "Dashboard page copied into the module folder. No harvest ingress. unifiedAIGateway.js is another door beside it.",
    plug: "gateway.ingress { signal, organ } — one door, one audit, one cost cap.",
  },
  {
    id: "nervous",
    name: "Nervous System",
    short: "Nervous",
    moduleId: "nervousSystem",
    family: "core",
    declared: "none",
    actual: "skeleton",
    bytesCanonical: 32072,
    bytesLegacy: null,
    liveCallers: 0,
    isComplete: false,
    frontend: false,
    routes: true,
    tests: false,
    organs: ["ai", "spine", "reflex", "erp"],
    path: "backend/src/core/nervousSystem.js",
    contract:
      "Brain, heart, pathways, reflexes, sensors, motor — as code that modules register with, not a metaphor file.",
    silo: "Classes named CentralBrain and HeartBeat. Default decision is log-and-forget. Heart pump is empty. Reflex effectiveness is hardcoded 1.0. 22 routes, no AI inside them.",
    plug: "nervous.register { moduleId, events[], reflex } on boot. Unknown events must fail, not forget.",
  },
  {
    id: "decision",
    name: "Decision Engine",
    short: "Decision",
    moduleId: "decisionEngine",
    family: "core",
    declared: "none",
    actual: "partial",
    bytesCanonical: 14504,
    bytesLegacy: null,
    liveCallers: 0,
    isComplete: false,
    frontend: false,
    routes: false,
    tests: false,
    organs: ["ai", "reflex", "rupee"],
    path: "backend/src/core/decisionEngine.js",
    contract:
      "Sense, decide, act, learn as one motion. A decision that cannot name a rupee path is decoration.",
    silo: "File exists in core/. MCDA sits beside it. Neither is bound to harvest, weather, or offtake. BIEA specified the loop; the loop is literature.",
    plug: "decision.act { signal, organ, ₹ } or hide the recommendation.",
  },
  {
    id: "erp-agents",
    name: "ERP Agents",
    short: "ERP agents",
    moduleId: "erpAgents",
    family: "core",
    declared: "none",
    actual: "partial",
    bytesCanonical: 46380,
    bytesLegacy: null,
    liveCallers: 0,
    isComplete: false,
    frontend: false,
    routes: false,
    tests: false,
    organs: ["erp", "ai", "spine", "orders"],
    path: "backend/src/core/erpAgents.js",
    contract:
      "ERP agents subscribe to the same pulses the organism already knows. They do not invent a second spine.",
    silo: "Largest AI file. Still a batch of agent classes. harvest.completed is not an input. Village books are not an output.",
    plug: "erpAgent.on harvest.completed → propose a lot mint. Human approves. ERP records.",
  },
  {
    id: "factory",
    name: "Module System Factory",
    short: "Factory",
    moduleId: "moduleSystemFactory",
    family: "core",
    declared: "none",
    actual: "partial",
    bytesCanonical: 4880,
    bytesLegacy: null,
    liveCallers: 0,
    isComplete: false,
    frontend: false,
    routes: false,
    tests: false,
    organs: ["ai", "spine", "erp"],
    path: "backend/src/core/moduleSystemFactory.js",
    contract:
      "Every module becomes a runtime system with a contract: operations, emits, organs it may move. Phase 1 is listing. Phase 2 is plugging.",
    silo: "Phase 1 walks folders and prints SYS-M*. Phase 2 (orphan discovery, organ binding) is 'intentionally separate' and unfinished. 544 directories. Most declaredStatus is generated.",
    plug: "factory.plug { moduleId, organs[], events[] } — a list of folders is not a nervous system.",
  },
  {
    id: "contract",
    name: "Module Contract",
    short: "Contract",
    moduleId: "moduleContract",
    family: "core",
    declared: "none",
    actual: "skeleton",
    bytesCanonical: 1491,
    bytesLegacy: null,
    liveCallers: 0,
    isComplete: false,
    frontend: false,
    routes: false,
    tests: false,
    organs: ["ai", "farmer", "lot", "spine", "reflex"],
    path: "backend/src/core/moduleContract.js",
    contract:
      "A module contract names operations, the organs it may move, the pulses it emits, and that commands require a human. Prefixes are not organs.",
    silo: "classifies get/list as query and create/update as command. emits `${moduleId}.*`. ai_capabilities are three generic strings. No DORA organ. No lotId.",
    plug: "contract.bind { moduleId, organs, emits, rupeePath }. Prefixes are doors. Organs are lives.",
  },
  {
    id: "agentic",
    name: "Agentic Companion",
    short: "Agentic",
    moduleId: "M675100_AIAGENTICCOMPANION",
    family: "agent",
    declared: "WIRED",
    actual: "skeleton",
    bytesCanonical: 1113,
    bytesLegacy: 25583,
    liveCallers: 0,
    isComplete: false,
    frontend: false,
    routes: false,
    tests: false,
    organs: ["ai", "farmer", "lot", "spine", "reflex"],
    path: "backend/src/services/aiAgenticCompanionService.js",
    contract:
      "The farmer-cell companion: autonomous propose, human approve, memory of the last harvest, tools that mint lots and pause EMI. Not a chat widget.",
    silo: "module.json status WIRED, analysis.category SKELETON, isComplete false, hasMethods false. Canonical file is a 1.1KB re-export of legacy with zero live callers from index.js. Completeness: no frontend, no routes, no tests. Migrated from a Windows Downloads path.",
    plug: "agentic.propose { harvest.completed } → lot.mint + rupee path. Cell approves. Companion never executes a command alone.",
  },
  {
    id: "copilot",
    name: "AI Copilot",
    short: "Copilot",
    moduleId: "M455100_AICOPILOT",
    family: "agent",
    declared: "WIRED",
    actual: "skeleton",
    bytesCanonical: 1086,
    bytesLegacy: 27636,
    liveCallers: 0,
    isComplete: false,
    frontend: false,
    routes: false,
    tests: false,
    organs: ["ai", "farmer", "erp"],
    path: "backend/src/services/aiCopilotService.js",
    contract:
      "Copilot sits in the work: village books, lots, warehouse. It proposes the next keystroke. It does not open a second portal.",
    silo: "WIRED skeleton. Canonical 1.0KB re-export. Real 27KB lives under services/ai/. Frontend false, routes false. CopilotChat.jsx is a page, not a ligament.",
    plug: "copilot.suggest { organ, lotId } inside Books, not beside them.",
  },
  {
    id: "brain",
    name: "AI Brain",
    short: "Brain",
    moduleId: "M723100_AIBRAIN",
    family: "agent",
    declared: "WIRED",
    actual: "skeleton",
    bytesCanonical: 15171,
    bytesLegacy: null,
    liveCallers: 0,
    isComplete: false,
    frontend: true,
    routes: true,
    tests: false,
    organs: ["ai", "demand", "rupee"],
    path: "backend/src/services/aiBrainService.js",
    contract:
      "One brain. Scoring and recommendation that name the organ they moved. A brain page is a mouth.",
    silo: "AIBrainPage exists. 14 routes with no AI application inside them per the 2026-08-30 map. Sibling of orchestrator, coordinator, and nervousSystem.",
    plug: "brain.decide is orchestrator.decide. Two brains is a tumour.",
  },
  {
    id: "conversational",
    name: "Conversational AI",
    short: "Conversational",
    moduleId: "M407_CONVERSATIONAL_AI",
    family: "mouth",
    declared: "WIRED",
    actual: "skeleton",
    bytesCanonical: 1107,
    bytesLegacy: 18032,
    liveCallers: 0,
    isComplete: false,
    frontend: false,
    routes: true,
    tests: false,
    organs: ["ai", "farmer"],
    path: "backend/src/services/conversationalAIService.js",
    contract:
      "Voice of the companion, not a product. Talk is a tissue of agentic — not a module with its own portal.",
    silo: "1.1KB stub. Schema 021_conversational_ai_schema.sql exists. The mouth has a table. The cell has no companion.",
    plug: "conversational is a surface of agentic. Fold it. Do not ship another chat.",
  },
  {
    id: "voice",
    name: "Voice AI",
    short: "Voice",
    moduleId: "M477100_VOICEAI",
    family: "mouth",
    declared: "WIRED",
    actual: "skeleton",
    bytesCanonical: 1080,
    bytesLegacy: 15273,
    liveCallers: 0,
    isComplete: false,
    frontend: false,
    routes: true,
    tests: false,
    organs: ["ai", "farmer", "household"],
    path: "backend/src/services/voiceAIService.js",
    contract:
      "A farmer who cannot type still has a harvest. Voice is a door on the companion, in the language of the cell.",
    silo: "Stub plus advancedVoiceAI.js as a third copy. No harvest dictation. No household language pack.",
    plug: "voice.dictate harvest.completed in the cell’s language, into agentic, not into a demo.",
  },
  {
    id: "advisory",
    name: "AI Advisory",
    short: "Advisory",
    moduleId: "M472100_AIADVISORY",
    family: "domain",
    declared: "WIRED",
    actual: "skeleton",
    bytesCanonical: 1089,
    bytesLegacy: 9532,
    liveCallers: 0,
    isComplete: false,
    frontend: false,
    routes: false,
    tests: false,
    organs: ["ai", "soil", "crop", "farmer"],
    path: "backend/src/services/aiAdvisoryService.js",
    contract:
      "Advisory is a reflex with an explanation. weather.alert that does not freeze EMI is gossip.",
    silo: "1.0KB stub. weatherAdvisory remains a page. Advisory does not sit on the spine.",
    plug: "advisory.on weather.alert → cover window + EMI pause + rupee explanation.",
  },
  {
    id: "agricultural",
    name: "Agricultural AI",
    short: "Agri AI",
    moduleId: "M403_AGRICULTURAL_AI",
    family: "domain",
    declared: "WIRED",
    actual: "skeleton",
    bytesCanonical: 0,
    bytesLegacy: null,
    liveCallers: 0,
    isComplete: false,
    frontend: false,
    routes: false,
    tests: false,
    organs: ["crop", "soil", "farmer", "ai"],
    path: "backend/src/modules/M403_AGRICULTURAL_AI",
    contract:
      "Variety, season, and planting advice that writes into the genome organ — not a parallel agriculture chatbot.",
    silo: "Named module folder. cropService already exists. Two AIs for one genome. Neither publishes harvest.completed.",
    plug: "agri.advise writes crop_plantings. It does not open a new service.",
  },
  {
    id: "omnichannel",
    name: "Omnichannel AI",
    short: "Omnichannel",
    moduleId: "M639100_OMNICHANNELAI",
    family: "mouth",
    declared: "WIRED",
    actual: "skeleton",
    bytesCanonical: 1098,
    bytesLegacy: 24201,
    liveCallers: 0,
    isComplete: false,
    frontend: false,
    routes: true,
    tests: false,
    organs: ["marketplace", "demand", "ai"],
    path: "backend/src/services/omnichannelAIService.js",
    contract:
      "Channels are tissues of the market organ. WhatsApp, stall, and storefront share one lot body.",
    silo: "Stub plus a 24KB sibling under services/ai/. 15 routes and no AI application in the 2026-08-30 map.",
    plug: "omnichannel.list { lotId } — same sack, many doors. Never a second catalog.",
  },
  {
    id: "selfheal",
    name: "AI Self-Healing",
    short: "Self-heal",
    moduleId: "M317100_AISELFHEALING",
    family: "domain",
    declared: "WIRED",
    actual: "skeleton",
    bytesCanonical: 1098,
    bytesLegacy: 19522,
    liveCallers: 0,
    isComplete: false,
    frontend: true,
    routes: true,
    tests: false,
    organs: ["ai", "spine", "erp"],
    path: "backend/src/services/aiSelfHealingService.js",
    contract:
      "Heal broken requires and empty pumps. A self-heal page that cannot restart a missing harvest pulse is a status board.",
    silo: "1.0KB stub. AISelfHealingPage exists. Broken requires remain in COMPREHENSIVE_LINK_REPORT.csv.",
    plug: "selfheal.repair { missing: harvest.completed } or do not use the word heal.",
  },
  {
    id: "opsintel",
    name: "Operation Intelligence",
    short: "Ops intel",
    moduleId: "M699100_AIOPERATIONINTELLIGENCE",
    family: "domain",
    declared: "WIRED",
    actual: "skeleton",
    bytesCanonical: 1128,
    bytesLegacy: 18939,
    liveCallers: 0,
    isComplete: false,
    frontend: true,
    routes: true,
    tests: false,
    organs: ["ai", "erp", "rupee"],
    path: "backend/src/services/aiOperationIntelligenceService.js",
    contract:
      "Operations intel reads village books and names the fever. It does not invent a second dashboard for the same lots.",
    silo: "Stub. AIOperationIntelligencePage is another dashboard. Village books already exist in this app.",
    plug: "opsintel.read books.kpis — one ledger, one fever.",
  },
  {
    id: "complete",
    name: "Complete AI Integration",
    short: "Complete",
    moduleId: "M150100_COMPLETEAIINTEGRATION",
    family: "core",
    declared: "WIRED",
    actual: "unplugged",
    bytesCanonical: 40567,
    bytesLegacy: 42007,
    liveCallers: 0,
    isComplete: false,
    frontend: false,
    routes: true,
    tests: false,
    organs: ["ai", "spine", "farmer", "lot"],
    path: "backend/src/services/completeAIIntegrationService.js",
    contract:
      "The name claims the work. Integration means every named AI is a module of one nerve, plugged into organs.",
    silo: "40KB service plus a controller plus a module folder. Still a sibling. 'Complete' is the most dangerous word in this repo.",
    plug: "Delete the word complete. Plug agentic, copilot, and fabric. Then count.",
  },
  {
    id: "ecommerce",
    name: "Ecommerce AI",
    short: "Ecom AI",
    moduleId: "M807100_ECOMMERCEAI",
    family: "domain",
    declared: "WIRED",
    actual: "skeleton",
    bytesCanonical: 1092,
    bytesLegacy: 28771,
    liveCallers: 0,
    isComplete: false,
    frontend: false,
    routes: true,
    tests: false,
    organs: ["marketplace", "demand", "fvie"],
    path: "backend/src/services/ecommerceAIService.js",
    contract:
      "Rank by food-value, energy cost, and farmer rupee — not SKU affinity. Marketplace is a hand, not a shop AI.",
    silo: "1.0KB stub. Listings are not born from harvest. FVIE is missing, so there is nothing honest to rank.",
    plug: "ecom.rank { lotId, foodValue, energyPerKg, farmerPaise }.",
  },
  {
    id: "media",
    name: "Product Media AI",
    short: "Media AI",
    moduleId: "M714100_PRODUCTMEDIAAI",
    family: "domain",
    declared: "WIRED",
    actual: "skeleton",
    bytesCanonical: 1101,
    bytesLegacy: 11162,
    liveCallers: 0,
    isComplete: false,
    frontend: false,
    routes: true,
    tests: false,
    organs: ["marketplace", "trace", "lot"],
    path: "backend/src/services/productMediaAIService.js",
    contract:
      "A picture of a sack is a tissue of the lot, with the GI marker in the frame. Not a studio beside the catalog.",
    silo: "Stub. AIProductStudioPage and ValueChainStudio are more mouths. The lot still has no body.",
    plug: "media.attach { lotId, frame } at lot.mint. Never a second product.",
  },
  {
    id: "advanced",
    name: "Advanced AI",
    short: "Advanced",
    moduleId: "M409100_ADVANCEDAI",
    family: "domain",
    declared: "WIRED",
    actual: "skeleton",
    bytesCanonical: 1089,
    bytesLegacy: 59649,
    liveCallers: 0,
    isComplete: false,
    frontend: false,
    routes: false,
    tests: false,
    organs: ["ai"],
    path: "backend/src/services/advancedAIService.js",
    contract:
      "Forecast, score, classify, recommend — as capabilities of the fabric, not a 59KB grab-bag named Advanced.",
    silo: "Canonical stub. Legacy advancedAIService.js is the largest grab-bag. Eight 'AI applications' in the 2026-08-30 map, zero organ plugs.",
    plug: "Fold methods into fabric. Retire the word advanced.",
  },
];

export const MODULE_DIRS_ON_DISK = 544;
export const NAMED_AI_MODULE_FOLDERS = 18;
